### ISSUE TITLE
dumpprivkey needed

### ISSUE THREAD

**Issue by BitBargain** [ElementsProject/lightning#807] opened 2018-01-27 16:09 UTC
To start off, I understand I made a few mistakes, including trying this on mainnet and using a node with pruning enabled. In my defense the documentation said the only dependency was a node that is fully caught up. No mention about txindexes (as with another implementation) or pruning.

The end result is that none of the channels opened, the 'withdraw' command just hung the first time, and the second time it said "insufficient funds" and the confirmed funding TX disappeared from the "listfunds" output as well. The coin on the deposit addresss (obtained from 'newaddr') is still unspent, so no transactions actually took place. But now I have no way to access the coins and retrieve them.

I need 'dumpprivkey' or some fallback mechanism to get back the coins I deposited to lightningd. I imagine I won't be the last person to need this. Thanks for your kind consideration.

**Comment by BitBargain** [comment] 2018-01-27 22:07
Just in case anyone finds this and has similar issues: the solution was to remove the new outputs from the sqlite database to make it think the vout was spendable (which it was, because no transactions took place) and change the code to print the raw transaction before submitting it. Coins are back and safe.

**Comment by cdecker** [comment] 2018-01-27 23:00
I took the liberty of removing the "funds lost" from the issue title. This appears to be an issue in which we get out of sync with the blockchain, and believe funds to be spent, when they aren't. Possibly related to issue #803. We'll improve on the spentness tracking for our outputs.

**Comment by cdecker** [comment] 2018-01-28 21:44
Closing as a duplicate of #746

**Closed by cdecker** 2018-01-28 21:44 UTC
