### ISSUE TITLE
db fail to upgrade due rune table migration

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#6770] opened 2023-10-13 08:55 UTC
I am running the current master but I can't upgrade the db

```
023-10-13T08:53:43.341Z DEBUG   hsmd: pid 173246, msgfd 53
2023-10-13T08:53:43.342Z DEBUG   hsmd: capability +WIRE_HSMD_CHECK_PUBKEY
2023-10-13T08:53:43.342Z DEBUG   hsmd: capability +WIRE_HSMD_SIGN_ANY_DELAYED_PAYMENT_TO_US
2023-10-13T08:53:43.342Z DEBUG   hsmd: capability +WIRE_HSMD_SIGN_ANCHORSPEND
2023-10-13T08:53:43.342Z DEBUG   hsmd: capability +WIRE_HSMD_SIGN_HTLC_TX_MINGLE
2023-10-13T08:53:43.342Z DEBUG   hsmd: capability +WIRE_HSMD_SIGN_SPLICE_TX
2023-10-13T08:53:43.342Z INFO    lightningd: Updating database from version 234 to 236
2023-10-13T08:53:43.342Z **BROKEN** lightningd: query failed: wallet/wallet.c:5737: SELECT rune, last_used_nsec FROM runes
```

**Comment by vincenzopalazzo** [comment] 2023-10-14 10:57
Ok this looks like introduced in https://github.com/ElementsProject/lightning/commit/eacf0b502c28662b515eaec2f3e975ac51423f20

cc @ShahanaFarooqui

**Comment by ShahanaFarooqui** [comment] 2023-10-15 01:58
@vincenzopalazzo The issue has already been discussed in https://github.com/ElementsProject/lightning/issues/6700. 

It happened due to my rebase and merging confusion at db version 234. As suggested by @ddustin, the fix is: https://github.com/ElementsProject/lightning/issues/6700#issuecomment-1730040871

Let me know if anything else needs to be done about this or can we close it now.

**Comment by vincenzopalazzo** [comment] 2023-10-15 12:09
@ShahanaFarooqui Sorry but I am running 7bea339f2f8ac9558d635b88237958f1957f9803. It should contain the solution, but the bug still happens, so I understand the problem, but I do not understand what the fix is?

In the PR that you link, there is the following assertion

>And fixed that in further commits :)

It does not seem to be true(?)

**Comment by ShahanaFarooqui** [comment] 2023-10-15 22:27
@vincenzopalazzo Thanks. I was able to reproduce it with current master branch. I will look into it now.

Thank you for bringing it into my attention.

**Closed** 2023-10-23 05:23 UTC
Labels: bug
