### ISSUE TITLE
Very slow block sync

### ISSUE THREAD

**Issue by JavierRSobrino** [ElementsProject/lightning#3243] opened 2019-11-05 02:28 UTC
I had to start a resync of several months after a blockchain corruption. Using the current RPC mechanism, it is extremely slow even in a fast machine.
My calculations are from 1 second up to 3 second per block, so if you are several months syncing, it can take 30 to 40 hours to sync in my example, which is just too much.

My proposition is to change to something faster, like ZMQ like LND uses, Neutrino, or something that allows fast traversal of blocks.

Version 0.7.2.

**Comment by cdecker** [comment] 2019-11-05 15:49
Are you running in docker or as root? If yes that's a known regression that was fixed in 0.7.3 with this pull request https://github.com/ElementsProject/lightning/pull/3101.

**Comment by JavierRSobrino** [comment] 2019-11-05 16:19
I'm running as docker. I'm still waiting for the docker image to update.

**Comment by cdecker** [comment] 2019-11-05 17:44
Right, I updated the docker images (`elementsproject/lightningd:latest` and `elementsproject/v0.7.3`) today. Sorry for the delay :-)

**Comment by JavierRSobrino** [comment] 2019-11-05 18:14
Thank you for the update. I have now 0.7.3 in my docker.
Unfortunately, it is still slow to sync, around 3s per block.

**Comment by Saibato** [comment] 2019-11-06 10:23
@cdecker  can confirm this on a no docker pi that remote rpc's the bitcoin core full node up to 3s per block.

**Comment by JavierRSobrino** [comment] 2019-11-06 18:31
Here is the requested information:

1. bip32_max_index|280|292|
2. 13
3. 139
4. 65811

As you can see, yes, they are very high in some cases.

No, I'm runing in a good performance server, an i7 with 4 cores and 8 threads. The lightning db is in an SSD, but the blockchain is in an HDD. It's a decent speed SATA HDD anyway.

Anyway, my node hasn't been the biggest or even close of the nodes out there. I'm sure there are hundreds of nodes which had many more channels.

**Comment by Saibato** [comment] 2019-11-06 19:02
Thanks @cdecker for the hint, tfw you think slow is so goooooooood. :smile: 

I think now, this must somehow be reducable from potential worse than quadratic to N log*N,  in case of sync to blockheight  could we use db speedup magic and check once at the end against the final state or am I thinking to short here ?

**Comment by whitslack** [comment] 2019-11-08 17:43
For what it's worth, I was experiencing lightningd hanging for multiple *minutes* every time a new block was mined. The disks (6-drive RAID10) would grind the whole time, and `top` showed lightningd in disk sleep. All RPCs (even simple ones like `getinfo`) would hang during this time. When I migrated the SQLite database to PostgreSQL, the problem disappeared entirely.

**Comment by Saibato** [comment] 2019-11-08 18:33
Thanks @whitslack for the hint, when i realized why one of my nodes is so slow by the db hint and the numbers of @JavierRSobrino  I figured out that those utxos we track  are looped every block, so i like many utxos, but we need speedup here also for sqlite even if sqlite is a bit doomed for its lack of security if someone can insert in the db.

**Comment by JavierRSobrino** [comment] 2019-11-09 15:47
> For what it's worth, I was experiencing lightningd hanging for multiple _minutes_ every time a new block was mined. The disks (6-drive RAID10) would grind the whole time, and `top` showed lightningd in disk sleep. All RPCs (even simple ones like `getinfo`) would hang during this time. When I migrated the SQLite database to PostgreSQL, the problem disappeared entirely.

This might means that the code is having some problems with DB usage, blocking operations where it shouldn't. It shows up only when using sqlite because sqlite doesn't allow multiple writes at once, but postgresql does.

**Comment by darosior** [comment] 2020-01-08 13:46
@JavierRSobrino did #3274 solved this ?

**Comment by niftynei** [comment] 2020-04-07 19:13
Closing due to lack of updates; please comment if problem persists and we'll reopen.

**Closed by niftynei** 2020-04-07 19:13 UTC
Labels: bitcoind, docker
