### ISSUE TITLE
getpeers lists channel, but getchannels doesnt have it and no way to sendpay

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#237] opened 2017-08-26 17:54 UTC
I started 10 clients simultaneously, which ended up trying to fundchannel 8 times in parallel (2 of the nodes didnt get that far).

On the clients, they all seemed to get:
fundchannel -> ("Peer not ready for connection") err.0
waiting for CHANNELD_AWAITING_LOCKIN

the host side didnt look like it had any big errors:
lightningd_gossip(27669): UPDATE WIRE_GOSSIPSTATUS_PEER_NONGOSSIP
lightningd(27660): peer 03c9efc5c6261cc07bfdee0dc1619a83f68a6f3cd4bc74f9ec5c691f4cee9a6631: Gossip ended up receipt of WIRE_OPEN_CHANNEL
lightningd(27660): peer 03c9efc5c6261cc07bfdee0dc1619a83f68a6f3cd4bc74f9ec5c691f4cee9a6631: state: GOSSIPD -> OPENINGD
lightningd_opening(30068): pid 30068, msgfd 17
lightningd_opening(30068): REPLY WIRE_OPENING_FUNDEE_REPLY with 2 fds
lightningd_channel(30069): pid 30069, msgfd 26
lightningd(27660): peer 03c9efc5c6261cc07bfdee0dc1619a83f68a6f3cd4bc74f9ec5c691f4cee9a6631: state: OPENINGD -> CHANNELD_AWAITING_LOCKIN

but things just got stuck and none of the new clients got past the CHANNELD_AWAITING_LOCKIN

**Comment by cdecker** [comment] 2017-08-29 10:54
I can't reproduce this error. I just build a line successfully amoung 25 peers, and it all worked. Are you somehow mixing the `addfunds` calls so that some peers reuse the same outputs, or do peers reuse copies of the same `--lightning-dir`? Can you provide us with the detailed steps to reproduce this?

**Comment by jl777** [comment] 2017-08-29 11:22
i am running each instance in a separate VPS, it is a low end and not very fast. so everything is separate but the speed is on the slow side.

each VPS has a separate addfunds, but I am assuming each node is using a different set of HD addresses. I didnt verify this is actually the case but rely on each lightningd to use a random seed

my client code just connects (if not already connected), fundchannel (if no channel) and then gets rhash from the host node and does a sendpay.

It might be that I am issuing redundant sendpay calls to the same rhash, but that is low probability. Then again, things seem to work fine for dozens of sendpay. I will investigate more.

**Comment by jl777** [comment] 2017-08-29 11:35
maybe the issue is that the sendpay is stuck:

sendpay rhash.(4a6846966219d5faab09a2ec738a76b008c3f43a8af035ed1c97fed06d397d64) 0.00100000 to [{"id":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc","channel":"96660:1:1","msatoshi":100000000,"delay":100}] -> "still in progress" preimage.0000000000000000000000000000000000000000000000000000000000000000

the still in progress state...
only way i found to get things going again is to clear the SQL DB file (on both sides of the payment)
I did confirm that if you clear just one node, it obtains the channel info from the peer.

**Comment by cdecker** [comment] 2017-08-29 14:07
I'm still not clear how things are getting stuck. The channel establishment and the forwarding/sending/receiving of payments are orthogonal to each other. You can only `sendpay` after the channels in the route have reached state `CHANNELD_NORMAL`, not before (they should reject any payment immediately until the channel is usable).

So are you able to get all channels into `CHANNELD_NORMAL`? Does `lightning-cli getnodes` and `lightning-cli getchannels` report all channels as `active`? Notice that this might require you to generate blocks until they do on regtest, or wait for 6 confirmations on testnet.

**Comment by jl777** [comment] 2017-08-29 14:26
Do all channels need to be CHANNELD_NORMAL and active?
I am not checking for all channels, just between the pair of nodes (only using direct sendpay)
also, I am not checking for "active" state

maybe things get into a bad way if a sendpay comes in before everything is totally ready?

I will add more error checks and see if that fixes things

**Comment by jl777** [comment] 2017-08-29 14:42
That's probably the problem!

I am not calling getroute, but I generate the route JSON based on the rhash and channel, etc. You probably assume a getroute was called and returned a valid result.

It is all via a somewhat complex realtime networking code, that is still not ready for simple usage. I am hoping to get it much more stable over the next weeks.

**Comment by cdecker** [comment] 2017-08-29 14:49
Ok, but calling `getchannels` to verify that the channel is actually up and recognized by the endpoints would be really helpful to avoid at least known issues, would that be hard to add? Just to reduce false negatives :smiley:

**Comment by jl777** [comment] 2017-08-29 14:51
i do a getpeers and find the channel there, but I also have code that calls getchannels. and the route object I create seems to match the one from getroute, at least in the cases I tried.

I will just change to calling getroute.

**Comment by cdecker** [comment] 2017-08-29 15:11
Ok, then we can triage this a bit better, if `getpeers` shows `CHANNELD_NORMAL`, but `getchannels` doesn't show it as active then we have to wait for more confirmations. If `getchannels` shows the channel as active but `getroute` fails, then the routing logic may have a bug. If `getroute` works but then `sendpay` fails then we either have a transient failure (exhausted channel, temporary disconnect, ...) or we may have some forwarding logic error.

**Comment by jl777** [comment] 2017-08-29 16:22
thanks! I will implement the error checks for the above.
I think I will need to reset all the SQL DB files now as if I sendpay it never works and some nodes are at 100% CPU usage, probably I put it in some sort of crazy illegal state

**Comment by jl777** [comment] 2017-08-29 17:15
Aha! it seems when the reconnect logic was added, it exposed a bug in my code where I assumed that if there was a channel, it was ready to use. But there seem to be a long time where the channel is there and either the connected is false or connection not active.

more results as I fix things

**Comment by jl777** [comment] 2017-08-29 17:28
things are better, but now it is in a state where getpeers shows the channel, but getchannels is empty:

getpeers: 		{ "unique_id" : 0, "state" : "CHANNELD_NORMAL", "netaddr" : "::ffff:5.9.253.196:56998", "peerid" : "03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821", "connected" : true, "owner" : "lightningd_channel", "channel" : "96660:1:1", "msatoshi_to_us" : 23100000000, "msatoshi_total" : 101250000000 }, 

getchannels: { "channels" : 
	[  ] }

I cant do a fundchannel again using the same funds that the channel has locked. not sure what to do

**Comment by jl777** [comment] 2017-08-29 19:23
I think the illegal call sequences put the DB in a bad state. After clearing the DB files and starting over on all the nodes, I now have 9 nodes in the process of iterating 1000 sendpay

so far 50 sendpay on each node after a couple minutes. looking good. If it survives on all the nodes, I will close this bug, even though there does seem to be a way to get things into an illegal state, it was before I did all the checks you wrote about

**Comment by jl777** [comment] 2017-08-29 20:35
it almost got to the end properly. when the funds left in the channel gets low, I close the channel

but I didnt have enough margin so I ended up triggering the fault due to not enough funds (still seems harsh that it kills the program if you try to spend below the reserve)

**Comment by cdecker** [comment] 2017-08-29 20:39
Yeah, the crash definitely is a bug, you should not be able to go below the reserve, could you create a core dump along with the exact version you are using?

**Comment by cdecker** [comment] 2017-08-29 20:41
BTW I opened #247 for the unusable channels after restart. It seems that restarting an entire network, i.e., no one remembers the `channel_announcement` makes the channels unusable. That is assuming that they reached a depth of 6 before the restart because only then the `channel_announcement` is sent out and channels become really usable.

**Comment by jl777** [comment] 2017-08-29 21:15
I am using a forked version which has the recent onchaind changes merged in. I just do sendpay in a loop and it crashes everytime. I will try to get a core dump, but I remember it got a message 5, which was not enough funds and just killed itself. 

I will try to get a core dump next time I am testing the sendpay loop

**Comment by cdecker** [comment] 2017-08-29 21:28
Ok, I'll try to reproduce this on my end :smiley:

**Comment by jl777** [comment] 2017-08-29 21:57
got it!

lightningd_gossip(32754): REPLY WIRE_GOSSIP_GETCHANNELS_REPLY with 0 fds
channel.({"source":"03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821","destination":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc","active":true,"fee_per_kw":1,"last_update":1504041644,"flags":1,"delay":100,"short_id":"120793:1:1/1"})
lightningd_gossip(32754): REPLY WIRE_GOSSIP_GETROUTE_REPLY with 0 fds
getroute.({"route":[{"id":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc","channel":"120793:1:1","msatoshi":100000000,"delay":100}]})
lightningd(32745): Sending 100000000 over 1 hops to deliver 100000000
lightningd_channel(2415): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(2415): REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
lightningd(32745): FATAL SIGNAL 11 RECEIVED
Fatal signal 11. Log dumped in crash.log

990th sendpay 

but backtrace was disappointing:

(gdb) backtrace
No stack.

crash.log
+5177.002604000 lightningd_channel(2415):DEBUG: TRACE: Telling master we're about to commit...
+5177.002616290 lightningd_channel(2415):INFO: UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
+5177.077280661 lightningd_channel(2415):DEBUG: TRACE: Sending commit_sig with 0 htlc sigs
+5177.077301547 lightningd_channel(2415):DEBUG: TRACE: Adding HTLC 1002 gave 5
+5177.077311138 lightningd_channel(2415):INFO: REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
+5177.077343634 lightningd(32745):BROKEN: FATAL SIGNAL 11 RECEIVED

I remember before the DB syncing, it did do a useful backtrace. it was in the process of closing down channels

**Comment by cdecker** [comment] 2017-09-04 19:35
Closing since this has been addressed in 1cf33eefe2626ab3bcdfb200b6700ff634ce8826

**Closed by cdecker** 2017-09-04 19:35 UTC
Labels: bug
