### ISSUE TITLE
FATAL ERROR

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1721] opened 2018-07-19 09:33 UTC
When i run a command 
cli/lightning-cli listpeers
lightning-cli: reading response: Success

2018-07-19T09:33:07.462Z lightning_gossipd(21742): Received channel_update for channel 525199:817:0(1) now ACTIVE was ACTIVE (from subdaemon)
2018-07-19T09:33:08.603Z lightningd(21734): Connected json input
2018-07-19T09:33:08.603Z lightning_gossipd(21742): REPLY WIRE_GOSSIP_GETPEERS_REPLY with 0 fds
lightningd: Fatal signal 11 (version v0.6-94-gb876c60)
0x43150e crashdump
	common/daemon.c:37
0x7f42a1d0e4af ???
	???:0
0x7f42a1e489b0 ???
	???:0
0x423594 pubkey_eq
	./bitcoin/pubkey.h:20
0x4252a0 gossipd_getpeers_complete
	lightningd/peer_control.c:784
0x42b53a sd_msg_reply
	lightningd/subd.c:281
0x42ba97 sd_msg_read
	lightningd/subd.c:418
0x466694 next_plan
	ccan/ccan/io/io.c:59
0x46716b do_plan
	ccan/ccan/io/io.c:387
0x4671a9 io_ready
	ccan/ccan/io/io.c:397
0x468d15 io_loop
	ccan/ccan/io/poll.c:310
0x414b81 main
	lightningd/lightningd.c:444
0x7f42a1cf982f ???
	???:0
0x403618 ???
	???:0
0xffffffffffffffff ???
	???:0
2018-07-19T09:33:08.610Z lightningd(21734): FATAL SIGNAL 11 (version v0.6-94-gb876c60)
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: common/daemon.c:42 (crashdump) 0x43155e
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: (null):0 ((null)) 0x7f42a1d0e4af
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: (null):0 ((null)) 0x7f42a1e489b0
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: ./bitcoin/pubkey.h:20 (pubkey_eq) 0x423594
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: lightningd/peer_control.c:784 (gossipd_getpeers_complete) 0x4252a0
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: lightningd/subd.c:281 (sd_msg_reply) 0x42b53a
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: lightningd/subd.c:418 (sd_msg_read) 0x42ba97
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x466694
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x46716b
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x4671a9
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x468d15
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: lightningd/lightningd.c:444 (main) 0x414b81
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: (null):0 ((null)) 0x7f42a1cf982f
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: (null):0 ((null)) 0x403618
2018-07-19T09:33:08.610Z lightningd(21734): backtrace: (null):0 ((null)) 0xffffffffffffffff
Log dumped in crash.log
lightning_onchaind: lightning_channeld: lightning_channeld: Writing out status 65522Writing out status 65520: Writing out status 65522: : lightning_channeld: Broken pipe
Broken pipe
Broken pipe
Writing out status 65522: Broken pipe
Segmentation fault (core dumped)

**Comment by cdecker** [comment] 2018-07-19 12:08
Duplicate of #1680

**Closed by cdecker** 2018-07-19 12:08 UTC
Labels: duplicate
