### ISSUE TITLE
ONCHAIND_THEIR_UNILATERAL and Missing inputs

### ISSUE THREAD

**Issue by zooxit** [ElementsProject/lightning#839] opened 2018-01-29 11:34 UTC
Hi,
I am completely new here and would appreciate some guidance if possible.

While trying to make payment to blockstream (at the time I was connected to only one node which was correctly funded - was in state CHANNELD_NORMAL) something went wrong. The payment didn't go through and the channel started showing ONCHAIND_THEIR_UNILATERAL.
That was three days ago. The status is still the same:

```
{
  "id": "0273081ce642554d5a68a5236564fe88a3783457dc09e52812517f5724f36daefd",
  "connected": false,
  "channels": [
    {
      "state": "ONCHAIND_THEIR_UNILATERAL",
      "short_channel_id": "506193:629:0",
      "funding_txid": "732ee699a569758d4e9374eb5d9952af52e4a03ef86bb5868c530494e8148acf",
      "msatoshi_to_us": 1000000000,
      "msatoshi_total": 1000000000,
      "dust_limit_satoshis": 546,
      "max_htlc_value_in_flight_msat": 18446744073709552000,
      "channel_reserve_satoshis": 0,
      "htlc_minimum_msat": 0,
      "to_self_delay": 144,
      "max_accepted_htlcs": 483
    }
  ]
}
```

Now I am connected to 4 nodes, three of them are showing CHANNELD_NORMAL, but the above mentioned node is not changing.

 - If I try to close it: Peer is in state ONCHAIND_THEIR_UNILATERAL.
 - If I try to connect to it: channel ALL: Funding transaction spent
 - If I try to fund the channel: Peer is already ONCHAIND_THEIR_UNILATERAL

Lightning output: `lightningd(12221) Broadcasting tx 0200000........(long string): 25 error code: -25 error message: Missing inputs`

How can I close that channel (the node is acctualy from a friend, who also tried to close it, but it didn't work. Now on his side, he doesn't see me listed in listpeers)?

Any help appreciated.
best regards

**Comment by kubilay902** [comment] 2018-01-29 11:41
I have a similar issue too...

**Comment by cdecker** [comment] 2018-01-29 12:20
The missing inputs should be fine, `lightningd` is just trying to publish transactions it had queued as a reaction to the closing from the remote side.

The funds were returned to you in transaction `ea44d5b861a4a249f8a50c515be6f9853fe9eb146ec020e4e4b59ce5f57837eb:1`, which you then apparently used to open another channel with funding output `5818a2f047943fe7f8376152915973154af4ff91e3a02f9954827eba004bac16:0`. The channel remaining in that state is a known issue and we're trying to find the root cause of it. Can you restart (with `--log-leve=debug`) and provide us with the logs? In particular we're looking for logs generated by `onchaind`.

**Comment by zooxit** [comment] 2018-01-29 12:56
This is what I get with grep onchaind in logfile (debug):

{ "type" : "DEBUG", "time" : "420.848749040", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Tracking output 0 of
732ee699a569758d4e9374eb5d9952af52e4a03ef86bb5868c530494e8148acf:
FUNDING_TRANSACTION/FUNDING_OUTPUT" },
        { "type" : "DEBUG", "time" : "420.848832508", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Old remote per-commit
point: 035b17fe7613e0953db76f859e28cb282eeec3ba02bbc3e7f17662f2dcd9b7e028"
},
        { "type" : "DEBUG", "time" : "420.848871572", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: commitnum = 1,
revocations_received = 1" },
        { "type" : "DEBUG", "time" : "420.851978571", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Deconstructing
unilateral tx: 1 using keyset:  self_revocation_key:
02784081ffe699612ab796dd2988042cfa0e64517a190fe0187f7f5bb71e00faee
self_delayed_payment_key:
02ca5d847b2902ec97aee8807eda290f7247e8d4e409b89b64ab435c2401401301
self_payment_key:
03f6acf500e1c94abb9fc120745f7232570e2c37babce50f96c0d519321ae16843
other_payment_key:
03ea4bcb97a81e74357daeed91eb9536e3e14e978c7e6d96e6725f6b5d8d347086
self_htlc_key: 0277d615560a6d29ba2239bda4c4507580ad23dd6302b63c276bdddbd488e700fc
other_htlc_key:
0360ea8ca78015eeaaf55eb8c4c4f3725bc4c72894960e8b96afa609c829037cf7" },
        { "type" : "DEBUG", "time" : "420.852129796", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Output 0:
0020621c9a15f3583a785c209f07bfc1367adeb1423653f70913b2fd098ed6c8ecc3"
},
        { "type" : "DEBUG", "time" : "420.854528476", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Tracking output 0 of
ea44d5b861a4a249f8a50c515be6f9853fe9eb146ec020e4e4b59ce5f57837eb:
THEIR_UNILATERAL/OUR_HTLC" },
        { "type" : "DEBUG", "time" : "427.088234717", "source" :
"lightning_onchaind(30742):", "log" : "TRACE: Got new message
WIRE_ONCHAIN_SPENT" },
        { "type" : "BROKEN", "time" : "427.088282186", "source" :
"lightning_onchaind(30742):", "log" : "STATUS_FAIL_INTERNAL_ERROR:
THEIR_UNILATERAL/OUR_HTLC spent with weird witness 3" },
        { "type" : "INFO", "time" : "427.088340066", "source" :
"lightningd(12221):", "log" : "peer
0273081ce642554d5a68a5236564fe88a3783457dc09e52812517f5724f36daefd:
Peer transient failure in ONCHAIND_THEIR_UNILATERAL: Owning subdaemon
lightning_onchaind died (33536)" }

**Comment by nimm** [comment] 2018-02-01 06:29
I seem to have a similar problem with peer state ONCHAIND_THEIR_UNILATERAL.

In this case I performed a close which seemed to work (CLOSINGD_COMPLETE). I *think* I restarted lightningd at this point and then attempted to (re) connect to the same peer with error "channel ALL: Funding transaction spent". After this point I noticed the state had changed to ONCHAIND_OUR_UNILATERAL.

I was doing multiple things at once unfortunately so don't have exact steps. Also during this time I was trying to send payment from another node to myself which was failing (hence trying to close and open a new connection).

I've attached the complete debug log from a lightningd restart:

[lightningd.log](https://github.com/ElementsProject/lightning/files/1684400/lightningd.log)

**Comment by cdecker** [comment] 2018-02-01 11:25
We have recently merged PR #842 that should allow `lightningd` to correctly broadcast transactions again. In addition we created PR #864 so that users can sync with the UTXO set as seen by `bitcoind` which will thus recover funds that were marked as spent by an unsuccessful funding attempt.

@nimm @zooxit @kubilay902 could you pull the latest `master`, compile and use `dev-rescan-outputs` to recover funds and attempt to open a new channel (with another peer)?

**Comment by nimm** [comment] 2018-02-02 02:56
I've rebuilt and done a dev-rescan-output, i've also widthdrawn my old funds and created a new funding transaction (yesterday so confirmed already). At this point if I:
* list peers I still see the ONCHAIND_THEIR_UNILATERAL.
* try to connect to the same peer I still get the error "channel ALL: Funding transaction spent"
relevant logs for the connection below:
`2018-02-02T02:48:43.614Z lightning_gossipd(7380): TRACE: Connected out for 021dcd5ec6cc0a00b537ae919d8aed683e9f0cb9776d535d45cc3bee6bec714939
2018-02-02T02:48:43.614Z lightning_gossipd(7380): TRACE: Initiator: Act 1
2018-02-02T02:48:43.614Z lightning_gossipd(7380): TRACE: Initiator: Act 2
2018-02-02T02:48:44.118Z lightning_gossipd(7380): TRACE: Initiator: Act 3
2018-02-02T02:48:44.793Z lightning_gossipd(7380): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-02-02T02:48:44.793Z lightning_gossipd(7380): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-02-02T02:48:44.793Z lightningd(7372): peer 021dcd5ec6cc0a00b537ae919d8aed683e9f0cb9776d535d45cc3bee6bec714939: Peer has reconnected, state ONCHAIND_OUR_UNILATERAL
2018-02-02T02:48:44.793Z lightningd(7372):jcon fd 15: Failing: channel ALL: Funding transaction spent
2018-02-02T02:48:44.794Z lightning_gossipd(7380): TRACE: req: type WIRE_GOSSIPCTL_HAND_BACK_PEER len 250
2018-02-02T02:48:44.794Z lightning_gossipd(7380): TRACE: hand_back_peer 021dcd5ec6cc0a00b537ae919d8aed683e9f0cb9776d535d45cc3bee6bec714939: now local again
2018-02-02T02:48:44.794Z lightning_gossipd(7380): TRACE: 021dcd5ec6cc0a00b537ae919d8aed683e9f0cb9776d535d45cc3bee6bec714939: we sent them a fatal error, closing
`

Perhaps I'm doing something wrong here since I'm completely new to this :) Should I be doing anything first to clear things up!?

AFAIK I haven't actually lost any funds in all this. I transferred some across the original channel to the peer above, then afterwards tried to transfer some back which failed. The other end didn't lose any funds either so not sure why in this state...

**Comment by zooxit** [comment] 2018-02-02 11:14
Did as cdecker suggested.
The channel that was in ONCHAIND_THEIR_UNILATERAL is still in the same state, still cannot close it.
Otherwise it seems to work - opened and funded another channel yesterday and still looks ok.
My funds are correct, but they were also before dev-rescan-outputs.

Any idea how can I close the channel that is stucked in ONCHAIND_THEIR_UNILATERAL (almost for a week now) - it is my friends node, and would like to reconnect to it.

**Comment by cdecker** [comment] 2018-02-03 22:00
@zooxit the channel is actually closed, we simply don't forget it just yet, I'll add a new state to move into once a `onchaind` is done (all the unilateral states) and won't load it from the DB upon restart. That'll get rid of the channel from `listpeers` and should also allow you to reopen the channel (if the other endpoint also forgot about it).

**Comment by cdecker** [comment] 2018-03-09 18:14
This should have been addressed in the meantime. @zooxit can you confirm that the channel is indeed no longer there after upgrading to `master`?

**Closed** 2018-03-20 15:28 UTC
Labels: pending-fix-confirmation, question
