### ISSUE TITLE
more resilient, but a lot slower

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#236] opened 2017-08-26 16:17 UTC
with the DB saves at every step, things are over 10x slower. Compounding this is frequent:

lightningd(23778): peer 03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821: Peer transient failure in CHANNELD_NORMAL: 
lightningd(23778): 	peer 03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821: ... Owning subdaemon lightningd_channel died

The good news is that it does seem to recover and resume, so that is much,much better.

lightningd_channel(24084): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
after the sending commit message is where it seems to be taking most of its time, that is without any peer transient failures.

I havent seen any balance mismatches and now I fixed the expiration self-abort, it is avoiding the case of getting stuck with payment in progress. I extendeded the 1 block padding as frequently 2 blocks are found rapidly and with the slower time for the entire process the odds of crossing a block boundary are increased

**Comment by jl777** [comment] 2017-08-26 16:58
some more results.

I tweaked the various config.c settings and it is now much happier, it is over 300 sendpay this test and I am seeing go in fast bursts of up to 5 sendpay, then it gets stuck waiting for something.

invariably the screen is showing something about COMMITMSG when there is a several second pause. The throughput ends up being only 1 tx per second, when clearly it can easily go 10x faster if this pause went away. Not sure if 100 sendpay/second between two nodes is possible, but first need to get to the 10 sendpay/second level.

 I will test with multiple nodes all sendpay to a single node and see if it gets any better throughput. My feeling is at most 2x as half the time the send side is pausing and half the time the recv side is.

**Comment by jl777** [comment] 2017-08-26 17:40
well it did 990 sendpays before crashing:

lightningd(16758): Sending 100000000 over 1 hops to deliver 100000000
lightningd_channel(17008): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(17008): REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
lightningd(16758): FATAL SIGNAL 11 RECEIVED
Fatal signal 11. Log dumped in crash.log

this is due to trying to sendpay without enough left in reserve. A self-inflicted signal 11 seems overkill. why not just return an error "not enough funds"

**Comment by cdecker** [comment] 2017-08-29 10:49
The loss in speed was to be expected since we need to write to the DB on every commitment, otherwise we risk losing money in the case of an unlucky restart. We may be able to claw back some of the performance by doing incremental updates instead of writing the whole state on every commit, e.g., only update the shachain table if we receive a revoke, but we will definitely not be able to match the in-memory only speed we had before. So I'm marking this as <kbd>wontfix</kbd> for now.

**Closed by cdecker** 2017-08-29 10:49 UTC
Labels: wontfix

**Comment by rustyrussell** [comment] 2017-08-30 00:47
jl777 <notifications@github.com> writes:
> well it did 990 sendpays before crashing:
>
> lightningd(16758): Sending 100000000 over 1 hops to deliver 100000000
> lightningd_channel(17008): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
> lightningd_channel(17008): REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
> lightningd(16758): FATAL SIGNAL 11 RECEIVED
> Fatal signal 11. Log dumped in crash.log

OK, let me test this.

Yay, reproduced. Thanks, fix coming!

Cheers,
Rusty.
