### ISSUE TITLE
Node crashes after ~10 minutes

### ISSUE THREAD

**Issue by samjhill** [ElementsProject/lightning#1144] opened 2018-03-01 15:49 UTC
Pulled latest:
```
docker pull cdecker/lightningd:latest
latest: Pulling from cdecker/lightningd
Digest: sha256:ea02493d9525e2d7b94d482b18f20a6cc59812565354677b04ad640e18981cbf
Status: Image is up to date for cdecker/lightningd:latest
```

crash.log
```
DEBUG: 022d065a059294ff8796cf0b9df467ba76420c62eda92771a4063d15e7170020e0 chan #3: Funding tx 326d8c97c7ccd707328d0634cec19f983179f74b33f3eb6ee83f9950e7afdbc3 depth 5759 of 3
+1739.633018654 lightningd(1):BROKEN: FATAL SIGNAL 11 RECEIVED
+1739.640037974 lightningd(1):BROKEN: backtrace: lightningd/log.c:504 (log_crash) 0x414647
+1739.640201387 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0x7fa2027914af
+1739.640285884 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0x7fa2027aacc0
+1739.640359772 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0x7fa2027d2a48
+1739.640535840 lightningd(1):BROKEN: backtrace: ccan/ccan/tal/str/str.c:67 (do_vfmt) 0x46d500
+1739.640623259 lightningd(1):BROKEN: backtrace: ccan/ccan/tal/str/str.c:91 (tal_vfmt) 0x46d5c0
+1739.640729449 lightningd(1):BROKEN: backtrace: lightningd/log.c:264 (logv) 0x413a61
+1739.640767257 lightningd(1):BROKEN: backtrace: lightningd/log.c:320 (log_) 0x413de1
+1739.641112413 lightningd(1):BROKEN: backtrace: lightningd/peer_control.c:534 (funding_lockin_cb) 0x4211aa
+1739.641326083 lightningd(1):BROKEN: backtrace: lightningd/watch.c:221 (txw_fire) 0x429923
+1739.641410868 lightningd(1):BROKEN: backtrace: lightningd/watch.c:289 (watch_topology_changed) 0x429b87
+1739.641726478 lightningd(1):BROKEN: backtrace: lightningd/chaintopology.c:335 (updates_complete) 0x406cb7
+1739.641785708 lightningd(1):BROKEN: backtrace: lightningd/chaintopology.c:429 (get_new_block) 0x40712c
+1739.642040671 lightningd(1):BROKEN: backtrace: lightningd/bitcoind.c:630 (process_getblockhash) 0x405331
+1739.642146153 lightningd(1):BROKEN: backtrace: lightningd/bitcoind.c:173 (bcli_finished) 0x403e3f
+1739.642262618 lightningd(1):BROKEN: backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x463d1c
+1739.642333715 lightningd(1):BROKEN: backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x463d3c
+1739.642587260 lightningd(1):BROKEN: backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x46e604
+1739.642629314 lightningd(1):BROKEN: backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x46eab5
+1739.642692680 lightningd(1):BROKEN: backtrace: ccan/ccan/tal/tal.c:509 (tal_free) 0x46eec8
+1739.642824821 lightningd(1):BROKEN: backtrace: ccan/ccan/io/io.c:443 (io_close) 0x4629a4
+1739.642859464 lightningd(1):BROKEN: backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x46412b
+1739.643044054 lightningd(1):BROKEN: backtrace: lightningd/lightningd.c:403 (main) 0x412d4b
+1739.643126569 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0x7fa20277c82f
+1739.643208317 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0x403318
+1739.643288279 lightningd(1):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

### `getinfo` output

```
{ "id" : "02e40b82365cd2a3908a481b712ba09858a5dee4cac997351db6cbaa175129907b", "port" : 9735, "address" :
	[
		{ "type" : "ipv4", "address" : "67.205.191.68", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2092-g7c8883a", "blockheight" : 505632, "network" : "bitcoin" }
```

**Comment by ZmnSCPxj** [comment] 2018-03-01 23:15
Duplicates: #1114

**Comment by cdecker** [comment] 2018-03-01 23:26
Agreed, closing as a duplicate of #1114

**Closed by cdecker** 2018-03-01 23:26 UTC
Labels: duplicate
