### ISSUE TITLE
Peer ... does not support data lose protection

### ISSUE THREAD

**Issue by Iwson** [ElementsProject/lightning#2257] opened 2019-01-12 00:36 UTC
Hey, I have problem after update BTCPay. Now I have version: basedon-v0.6.3-rc1-modded. 
When i try make a channel then i receive message "Peer ... does not support data lose protection"
What can i do? Why i dont get this message before update?

My Node:

$ getinfo 
id: 021813a5300ac0cdc83ed5a0414dba7dd0c4bedd6cc389a2e03cda87bf5855dbaa
alias: “iwson.group”
color: 021813
num_peers: 1
num_pending_channels: 0
num_active_channels: 0
num_inactive_channels: 1
address:
  - type: ipv4
    address: 51.255.211.186
    port: 9735
binding:
  - type: ipv4
    address: 0.0.0.0
    port: 9735
version: basedon-v0.6.3-rc1-modded
blockheight: 558148
network: bitcoin
msatoshi_fees_collected: 6553

**Comment by cdecker** [comment] 2019-01-12 17:16
Duplicate of #2170

**Closed by cdecker** 2019-01-12 17:16 UTC
