### ISSUE TITLE
msat suffix not removed completely

### ISSUE THREAD

**Issue by sidiropo** [ElementsProject/lightning#6254] opened 2023-05-12 15:31 UTC
### Issue and Steps to Reproduce

The release notes of v23.05 state: "Removed msat suffix from all millisatoshi fields, as deprecated in v0.12.0.". However, the rpc calls for listchannels and listpeers still return some fields that contain this suffix.

**Comment by sidiropo** [comment] 2023-05-12 17:03
Yes, I have the v23.05. In listchannels the 'amount_msat' field contains the suffix. In listpeers the 'to_us_msat' and 'fee_base_msat'. In listforwards the 'fee_msat'.

**Comment by sidiropo** [comment] 2023-05-12 17:06
To clarify, this happens when performing the rpc calls from a python script. The command line interface "lightning-cli listpeers" etc works fine (it does not include any suffixes).

**Comment by vincenzopalazzo** [comment] 2023-05-12 20:02
>To clarify, this happens when performing the rpc calls from a python script. The command line interface "lightning-cli listpeers" etc works fine (it does not include any suffixes).

Ah ok I was worried because I just patched it :) we should take a look to the python library

**Comment by vincenzopalazzo** [comment] 2023-06-19 20:22
Mh I am not able to reproduce it, so are you sure that you had all updated?

Can you tell me what fields are still in string?

**Comment by vincenzopalazzo** [comment] 2023-06-19 21:15
Ok i reproduced it

**Comment by vincenzopalazzo** [comment] 2023-06-19 22:12
Closing this because the CI works pretty well https://github.com/ElementsProject/lightning/pull/6351

So feel free to reopen it if you are able to provide a reproducer!

**Comment by rustyrussell** [comment] 2023-06-20 04:36
I think your problem is that pyln-client interprets msat fields as Millisatoshi class.  If you turn that into a string, it appends "msat"?

**Comment by vincenzopalazzo** [comment] 2023-06-20 08:02
>I think your problem is that pyln-client interprets msat fields as Millisatoshi class. If you turn that into a string, it appends "msat"?

Yeah this is my guess too

**Comment by sidiropo** [comment] 2023-06-20 17:03
Yes, I believe this is the issue.

**Closed** 2023-07-06 07:20 UTC
Labels: bug, state::needinfo, pyln, in diagnostic
