### ISSUE TITLE
Host Name Resolution

### ISSUE THREAD

**Issue by molxyz** [ElementsProject/lightning#834] opened 2018-01-29 05:02 UTC
Errors in trying to connect to nodes with domain names... 

`~$ lightning-cli connect 03fdefe424b480b7d8f1a0b3dcb20f637ee56f330ee311402ad37049ebebce03f1 lnd.bitrefill.com 9735
{ "code" : -1, "message" : "host lnd.bitrefill.com:9735 not valid" }`

`~$ lightning-cli connect 03b0d54ece3b31934a96b8c425aa33759ee9acb876cc9b92bbfe8e1c19af6c11a2 skinneh.is-a-geek.com 8735
{ "code" : -1, "message" : "host skinneh.is-a-geek.com:8735 not valid" }`

Please change this as other implementations do not have this issue.  Thank you.

**Comment by ZmnSCPxj** [comment] 2018-01-29 10:13
Duplicate of #246

**Comment by ZmnSCPxj** [comment] 2018-01-29 10:14
Duplicate of #246 

(at least by my understanding. @cdecker?)

**Comment by cdecker** [comment] 2018-01-29 10:29
Not really, this one is about hostname resolution for `connect`, whereas #246 is about retrieving a peer's IP from its address.

**Closed** 2018-02-26 03:13 UTC
Labels: feature
