### ISSUE TITLE
lightningd: Config file /.lightning/config line 16: clnrest-port=3001: unknown option

### ISSUE THREAD

**Issue by TheMonsterz** [ElementsProject/lightning#7712] opened 2024-10-03 04:28 UTC
### Issue and Steps to Reproduce
Running `6.8.0-45-generic #45~22.04.1-Ubuntu`

After upgraded from 24.05 to 24.08, then 24.08.1 using:
`~/Downloads$ sudo tar -xvf clightning-v24.08rc3-Ubuntu-22.04.tar.xz -C /usr/local --strip-components=2`

I can't get cln to start anymore:
```
user@workstation:~$ lightningd
lightningd: Config file /home/user/.lightning/config line 16: clnrest-port=3001: unknown option

```
Looking at the log I'm thinking this looks relevant:
```

cln-log-2024-09-29T09:53:20.036Z INFO    plugin-clnrest: Killing plugin: disabled itself: No module named 'gevent'
cln-log-2024-09-29T09:53:20.051Z INFO    plugin-wss-proxy: Killing plugin: disabled itself: No module named 'websockets'
```

### `getinfo` output
```
"version": "v24.08.1-modded",
   "blockheight": 863910,
   "network": "bitcoin",
   "fees_collected_msat": ??????????,
   "lightning-dir": "/home/user/.lightning/bitcoin",
   "our_features": {
      "init": "08a0802a8a59a1",
      "node": "88a0802a8a59a1",
      "channel": "",
      "invoice": "02000002024100"
```

**Comment by cdecker** [comment] 2024-10-17 09:26
Sounds like the clnrest plugin is crashing due to a missing dependency. Please install `gevent` and try again. CLI options that are consumed by plugins are only available if the plugin has completed the startup dance.

**Comment by cdecker** [comment] 2024-10-17 15:05
Duplicate of #7665

**Closed by cdecker** 2024-10-17 15:05 UTC
Labels: plugin::clnrest

**Comment by ShahanaFarooqui** [comment] 2024-10-17 16:19
@TheMonsterz Until issue 7665 is resolved, you can manually follow the [Python plugins installation instructions](https://docs.corelightning.org/docs/installation#python-plugins) for them to work.

- For `clnrest` plugin dependencies:
```
sudo apt-get install python3-json5 python3-flask python3-gunicorn
pip3 install --user flask-cors flask-restx pyln-client flask-socketio gevent gevent-websocket
```

- For `wss-proxy` plugin dependencies:
```
pip3 install --user pyln-client websockets
```
