### ISSUE TITLE
Cannot open channel: Could not afford 1000000sat using all 0 available UTXOs

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#4109] opened 2020-10-05 11:15 UTC
### Issue and Steps to Reproduce
I deposited some funds to the clightning wallet and now intend to open a channel. The command:

```
lightning-cli fundchannel 0242a4ae0c5bef18048fbecf995094b74bfb0f7391418d71ed394784373f41e4f3 1000000 "slow" "false"
```

yields an error:

```
{
   "code": 301,
   "message": "Could not afford 1000000sat using all 0 available UTXOs: 1000160sat short"
}
```

However, the UTXO seems to be present and confirmed:

```
$ lightning-cli listfunds
{
   "outputs": [
      {
         "txid": "5b5f2348533ceb01fb5c10cc7acca45ef4c64192e1637d48179f550db495b898",
         "output": 0,
         "value": 2600000,
         "amount_msat": "2600000000msat",
         "scriptpubkey": "001441f6ca995471ef815489a64dedf22386e686513b",
         "address": "bc1qg8mv4x25w8hcz4yf5ex7mu3rsmngv5fmwq5sdk",
         "status": "confirmed",
         "blockheight": 651301,
         "reserved": true
      }
   ],
   "channels": []
```

I don't quite understand what `reserved` means though. The [documentation](https://lightning.readthedocs.io/lightning-fundchannel.7.html) says it shows "whether the UTXO is currently reserved for an in-flight tx". What does it mean? Can I use this UTXO to open a channel? Does the "in-flight tx" refer to an off-chain payment (I thought the convention was to refer to on-chain payments as transactions and to off-chain payments as payments)? I obviously don't have any in-flight off-chain payments, as I have no channels yet.

`unreserveinputs` may be relevant here ([docs](https://lightning.readthedocs.io/lightning-unreserveinputs.7.html)) but I don't understand a) what is the PSBT format this command expects; b) why is the UTXO reserved to begin with (I clearly was not trying to create a PSBT).

### `getinfo` output

```
{
   "id": "03525b5258e70dd12a1e3420be3601ceb9664294835ed780a74518cd19e691204f",
   "alias": "SILENTWATER",
   "color": "03525b",
   "num_peers": 1,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "ipv6",
         "address": "2001:a18:a:c3::11",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "0.9.1",
   "blockheight": 651370,
   "network": "bitcoin",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/stikhomirov/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment] 2020-10-05 17:23
`reserved` means that the UTXO was previously used by an on-chain transaction, that is not yet confirmed (or that we simply haven't seen being confirmed yet, in case we're lagging behind the blockchain head).

A number of RPC methods will reserve UTXOs, basically anything that ends up creating an on-chain transaction that isn't in response to a channel being closed, including `withdraw` or `fundchannel`. So it seems like there is a transaction that hasn't confirmed yet, and it is holding onto the UTXO.

You can most likely retrieve the transaction in question using the following:

```bash
sqlite3 ~/.lightning/bitcoin/lightningd.sqlite3 'SELECT hex(rawtx) FROM transactions WHERE blockheight IS NULL' | grep -i 98b895b40d559f17487d63e19241c6f45ea4cc7acc105cfb01eb3c5348235f5b
```

(Notice that I had to invert the `txid` since bitcoin choses to invert them when displaying them, which we replicate in our RPC, but the serialized tx has it non-inverted). Once you have the TX we can likely try and decipher what it was meant to do.

Reservations now always have a lifetime, after which the reservation is dropped, and the UTXO can be used again. You should be able to get the reservation timeout using the following:

```bash
sqlite3 ~/.lightning/bitcoin/lightningd.sqlite3 'SELECT HEX(prev_out_tx), prev_out_index, status, reserved_til FROM outputs'
```

**Comment by s-tikhomirov** [comment] 2020-10-06 09:58
Hmm, now the output is unreserved! Yesterday I left `bitcoind` running on the server but shut down `lightningd`. After relaunching `lightningd` now after ~20 hours and letting it sync, `listfunds` listed the UTXO with `reserved=false`, and `fundchannel` did open the channel (yay!).

I should have run the sqlite commands before opening the channel, but anyway: here is their output now (the UTXO is spent at this point):

```
$ sqlite3 ~/.lightning/bitcoin/lightningd.sqlite3 'SELECT hex(rawtx) FROM transactions WHERE blockheight IS NULL' | grep -i 98b895b40d559f17487d63e19241c6f45ea4cc7acc105cfb01eb3c5348235f5b
0200000000010198B895B40D559F17487D63E19241C6F45EA4CC7ACC105CFB01EB3C5348235F5B0000000000FDFFFFFF0240420F0000000000220020FDFCD16750FC9DDCCE55A7149BB1C2CCB98D5F724BA9BB33CA4821BA3FB751BE0A64180000000000160014336F4E215EA796E1FBCE8E890EBB5DFB03C08B550247304402205E4968688B6222D0A112D5DA3120A4429C7988840D75B816B759B10B9F66F049022069DCD029BF5390B18D2A2234AFDB48772227C1EC162B1AB5AC69419371919B74012103C0B7EEE0FD0DB3BA08BD944276D8BC37824ED632F82B7D962A3F0491504CF514F1F00900
$ sqlite3 ~/.lightning/bitcoin/lightningd.sqlite3 'SELECT HEX(prev_out_tx), prev_out_index, status, reserved_til FROM outputs'
98B895B40D559F17487D63E19241C6F45EA4CC7ACC105CFB01EB3C5348235F5B|0|1|651649
88EE28B9DC56AEBEFF4AB3065909D76E56864D52F745F0B187A14967E5F61F1D|1|0|
```

**Comment by cdecker** [comment] 2020-10-06 11:59
Indeed the first output indicates that it was reserved by an unconfirmed channel funding (output 0 has type `witness_v0_scripthash`). It appears that a funding was aborted (not completed and thus not cleaned up) or wasn't signed off by the remote endpoint.

So it seems everything worked as intended here. Reservations are always a bit thorny since we have a rather lengthy period in which we don't see the tx spending the outputs, but they might still confirm, so we tend to walk on the safe side, and avoiding what could potentially be an unintended double-spend with knock-on effects.

**Comment by s-tikhomirov** [comment] 2020-10-06 12:42
> So it seems everything worked as intended here.

Would it make sense to provide a more clear error message then? Something along the lines of "We know you have this output, it's confirmed, funds are safu, but it is marked as reserved because of (possible reasons) until (time). Wait until it's unreserved or (do something)."

**Comment by niftynei** [comment] 2020-11-10 00:31
@s-tikhomirov is it ok to close this issue?

**Comment by s-tikhomirov** [comment] 2020-11-10 10:18
@niftynei My particular problem was solved, but it still seems to me that the "reserved outputs" may look scary to users who don't fully understand the underlying mechanics. I would add a more clear error message if an output is reserved, maybe, estimating how long the user has to wait until it is unreserved. If you don't think it's a good idea, then it's a wontfix-close, i guess :)

**Closed** 2021-12-02 11:22 UTC
