### ISSUE TITLE
Peer transient failure in CHANNELD_SHUTTING_DOWN: lightning_channeld: Owning subdaemon lightning_channeld died

### ISSUE THREAD

**Issue by JohnnyBackflip** [ElementsProject/lightning#1592] opened 2018-06-16 17:29 UTC
Hey guys,

I have this weird error spamming when starting lightningd: 

```
>lightningd --bitcoin-rpcuser aaa --bitcoin-rpcpassword bbb --testnet
2018-06-16T17:18:29.359Z lightningd(26791): Server started with public key 02c1626677d61bf1217e2028372d90435046f44d93b133fa6d159dcf76ec8a2610, alias BLUESOUFFLE- (color #02c162) and lightningd v0.5.2-2016-11-21-2882-gf8da37ff
2018-06-16T17:18:29.392Z lightningd(26791): No fee estimate for Immediate: basing on default fee rate
2018-06-16T17:18:29.392Z lightningd(26791): No fee estimate for Normal: basing on Immediate rate
2018-06-16T17:18:29.392Z lightningd(26791): No fee estimate for Slow: basing on Immediate rate
2018-06-16T17:18:29.392Z lightningd(26791): No fee estimate for Slow: basing on Normal rate
2018-06-16T17:18:29.611Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Gossipd gave us bad send_gossip message 0bc80000
2018-06-16T17:18:29.611Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer connection lost
2018-06-16T17:18:29.611Z lightningd(26791): 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer transient failure in CHANNELD_SHUTTING_DOWN: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-06-16T17:18:29.828Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Gossipd gave us bad send_gossip message 0bc80000
2018-06-16T17:18:29.828Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer connection lost
2018-06-16T17:18:29.828Z lightningd(26791): 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer transient failure in CHANNELD_SHUTTING_DOWN: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-06-16T17:18:30.049Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Gossipd gave us bad send_gossip message 0bc80000
2018-06-16T17:18:30.049Z lightningd(26791): lightning_channeld-03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer connection lost
2018-06-16T17:18:30.049Z lightningd(26791): 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 chan #2: Peer transient failure in CHANNELD_SHUTTING_DOWN: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
```

Also I have channels stuck in CHANNELD_AWAITING_LOCKIN and CHANNELD_SHUTTING_DOWN.

```
{
  "peers": [
    {
      "id": "03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134", 
      "connected": false, 
      "channels": [
        {
          "state": "CHANNELD_SHUTTING_DOWN", 
          "channel_id": "4b2ad104c138c3bdb512c12496a238100a4a165d991ae9e8ef6ae868618878dc", 
          "funding_txid": "dc78886168e86aefe8e91a995d164a0a1038a29624c112b5bdc338c104d12a4b", 
          "msatoshi_to_us": 100000000, 
          "msatoshi_to_us_min": 100000000, 
          "msatoshi_to_us_max": 100000000, 
          "msatoshi_total": 100000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 1000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 99000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "to_self_delay": 6, 
          "max_accepted_htlcs": 483, 
          "status": [
            "CHANNELD_SHUTTING_DOWN:Reconnected, and reestablished."
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }, 
    {
      "id": "03193d512b010997885b232ecd6b300917e5288de8785d6d9f619a8952728c78e8", 
      "connected": false, 
      "channels": [
        {
          "state": "CLOSINGD_COMPLETE", 
          "channel_id": "f35f829a1094a41b679207ebee1079ca96f660d28c3ce1e83e8065588505866d", 
          "funding_txid": "6d8605855865803ee8e13c8cd260f696ca7910eeeb0792671ba494109a825ff3", 
          "msatoshi_to_us": 1000000000, 
          "msatoshi_to_us_min": 1000000000, 
          "msatoshi_to_us_max": 1000000000, 
          "msatoshi_total": 1000000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 10000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 990000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "to_self_delay": 6, 
          "max_accepted_htlcs": 483, 
          "status": [
            "Loaded from database"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }, 
    {
      "id": "02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e", 
      "connected": true, 
      "netaddr": [
        "54.236.55.50:9735"
      ], 
      "alias": "yalls.org", 
      "color": "f8e71c", 
      "channels": [
        {
          "state": "CHANNELD_AWAITING_LOCKIN", 
          "owner": "lightning_channeld", 
          "channel_id": "4d4aff791155e914a53494a4d6dc0ac0577605199caee23d72b7fead35bb4226", 
          "funding_txid": "2642bb35adfeb7723de2ae9c19057657c00adcd6a49434a514e9551179ff4a4d", 
          "msatoshi_to_us": 1000000000, 
          "msatoshi_to_us_min": 1000000000, 
          "msatoshi_to_us_max": 1000000000, 
          "msatoshi_total": 1000000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 10000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 990000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "to_self_delay": 6, 
          "max_accepted_htlcs": 483, 
          "status": [
            "CHANNELD_AWAITING_LOCKIN:Sent reestablish, waiting for theirs"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}
```

getinfo gives this:

```
{
  "id": "02c1626677d61bf1217e2028372d90435046f44d93b133fa6d159dcf76ec8a2610", 
  "port": 9735, 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }
  ], 
  "version": "v0.5.2-2016-11-21-2882-gf8da37ff", 
  "blockheight": 1202568, 
  "network": "testnet"
}
```

I don't know whats going on... Why  are my channels stuck and why am I getting this error spam? Does somebody know what to do ?

edit now the status has changes but I still don't know whats going on:

```
{
      "id": "02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e", 
      "connected": false, 
      "alias": "yalls.org", 
      "color": "f8e71c", 
      "channels": [
        {
          "state": "ONCHAIN", 
          "owner": "lightning_onchaind", 
          "short_channel_id": "1325543:65:0", 
          "channel_id": "4d4aff791155e914a53494a4d6dc0ac0577605199caee23d72b7fead35bb4226", 
          "funding_txid": "2642bb35adfeb7723de2ae9c19057657c00adcd6a49434a514e9551179ff4a4d", 
          "msatoshi_to_us": 1000000000, 
          "msatoshi_to_us_min": 1000000000, 
          "msatoshi_to_us_max": 1000000000, 
          "msatoshi_total": 1000000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 10000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 990000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "to_self_delay": 6, 
          "max_accepted_htlcs": 483, 
          "status": [
            "ONCHAIN:Tracking our own unilateral close", 
            "ONCHAIN:1 outputs unresolved: in 20 blocks will spend DELAYED_OUTPUT_TO_US (8758c1fc82a2f3b822862793e6d553bc73e105243a32334572b48e03855c4d75:0) using OUR_DELAYED_RETURN_TO_WALLET"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
```

I just want to make a test payment to yalls.org

**Comment by cdecker** [comment] 2018-06-18 10:59
The error in the first output seems to be a duplicate of #1587. Does this error persist across restarts? If yes, can you make a backup of the .lightning/gossip_store file, remove it and then restart the node? The backup would be useful for us to debug (it doesn't contain any private information btw).

The hanging connection to yalls is stuck because yalls isn't sending the re-establish message, so we can't proceed with the protocol. The closure is because your client gave up on waiting and decided to close it unilaterally. Once the 20 blocks timeout expires I suggest opening a channel to a peer that is connected to yalls indirectly and making the payment indirectly.

**Comment by JohnnyBackflip** [comment] 2018-06-18 11:59
The error persited a few times after restarting but it has stopped now. 
Thanks for clarifying the yalls issue. How do I find peers that are connected to yalls?

**Comment by cdecker** [comment] 2018-06-18 14:48
Oh I see, you were connected to endurance on testnet. You can probably just try to connect to yalls directly:

```
lightning-cli connect 02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e@testnet-lnd.yalls.org
```

**Comment by JohnnyBackflip** [comment] 2018-06-18 15:09
Hey,

seems like I'm connected, the Status says  "ONCHAIN:All outputs resolved: waiting 27 more blocks before forgetting channel" - what does that mean? Can I load funds on it now?

>{
  "peers": [
    {
      "id": "02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e", 
      "connected": false, 
      "alias": "yalls.org", 
      "color": "f8e71c", 
      "channels": [
        {
          "state": "ONCHAIN", 
          "owner": "lightning_onchaind", 
          "short_channel_id": "1325543:65:0", 
          "channel_id": "4d4aff791155e914a53494a4d6dc0ac0577605199caee23d72b7fead35bb4226", 
          "funding_txid": "2642bb35adfeb7723de2ae9c19057657c00adcd6a49434a514e9551179ff4a4d", 
          "msatoshi_to_us": 1000000000, 
          "msatoshi_to_us_min": 1000000000, 
          "msatoshi_to_us_max": 1000000000, 
          "msatoshi_total": 1000000000, 
          "dust_limit_satoshis": 546, 
          "max_htlc_value_in_flight_msat": 18446744073709551615, 
          "their_channel_reserve_satoshis": 0, 
          "our_channel_reserve_satoshis": 10000, 
          "channel_reserve_satoshis": 0, 
          "spendable_msatoshi": 990000000, 
          "htlc_minimum_msat": 0, 
          "their_to_self_delay": 6, 
          "our_to_self_delay": 144, 
          "to_self_delay": 6, 
          "max_accepted_htlcs": 483, 
          "status": [
            "ONCHAIN:Tracking our own unilateral close", 
            "ONCHAIN:All outputs resolved: waiting 27 more blocks before forgetting channel"
          ], 
          "in_payments_offered": 0, 
          "in_msatoshi_offered": 0, 
          "in_payments_fulfilled": 0, 
          "in_msatoshi_fulfilled": 0, 
          "out_payments_offered": 0, 
          "out_msatoshi_offered": 0, 
          "out_payments_fulfilled": 0, 
          "out_msatoshi_fulfilled": 0
        }
      ]
    }
  ]
}

**Comment by cdecker** [comment] 2018-06-18 18:12
No, that's closing the channel (probably due to a timeout again). 

You can go [here](https://explorer.acinq.co/n/02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e) and select any of the peers of that node and try to connect to that.

**Comment by rustyrussell** [comment] 2018-06-18 23:08
This was fixed recently, in https://github.com/ElementsProject/lightning/commit/f5ebf8e231bdf0890c123cac69ec9bd37cae6850

**Closed** 2018-06-19 08:01 UTC
Labels: duplicate, gossip, lnd-compat

**Comment by JohnnyBackflip** [comment] 2018-06-19 11:17
So I updated my project and after that everything looks good again. Thanks for the help.

I connected to 02212d3ec887188b284dbb7b2e6eb40629a6e14fb049673f22d2a0aa05f902090e and funded a channel again but my internet provider is giving me a lots of disconnects today. When I came back online it said 

>"status": [
            "ONCHAIN:Tracking our own unilateral close", 
            "ONCHAIN:2 outputs unresolved: in 140 blocks will spend DELAYED_OUTPUT_TO_US (c6477dab61f58b3a61ffcfc1a3de7698dacca5878a95cdbcbf96eb0e099b9385:0) using OUR_DELAYED_RETURN_TO_WALLET"
          ], 

am I not allowed to go offline after funding a channel or is yalls just going crazy again?

**Comment by cdecker** [comment] 2018-06-19 12:43
I don't like pointing fingers, but at this point I think it's yalls. I'll try myself once I'm online again. Disconnects should not have a huge effect, except when prolonged.
