### ISSUE TITLE
Can't spend sats from onchain utxos after failed channel opening

### ISSUE THREAD

**Issue by Funman2** [ElementsProject/lightning#6265] opened 2023-05-20 13:14 UTC
Hi I am using the new umbrel core lightning app and ride the lighting app.
After funding two utxos with one address 1000000m sats and one with 100000 sats on main net, I tried to open a channel to a connected peer, it somehow failed but the channel showed up on both apps until restart, then it was gone after restart of node. 
I am not very familiar with ssh command but should try anything. 
Now when I try to spend the onchain balance I always get the error 0 utxos available. See attached screen shots. I also have over sc data base stored from RTL app with peer data. 
Please tell me how I can get back control of my funds. 
I also was able to backup rsm secret.
![IMG_20230520_151221_196](https://github.com/ElementsProject/lightning/assets/105175715/f11f4ebb-443e-404b-ae52-79dcd3d24c4a)
![IMG_20230520_151123_504](https://github.com/ElementsProject/lightning/assets/105175715/9ed45ab0-ba3c-4a46-89f1-c6606b1c0f0e)
![IMG_20230520_151115_020](https://github.com/ElementsProject/lightning/assets/105175715/2aba8a0e-2c14-4625-8543-8d0a6102c8b4)

**Comment by vincenzopalazzo** [comment] 2023-05-20 13:42
Try `lightning-cli listfunds`; you should see your transaction id inside the `output`. Check if it is confirmed on the blockchain.

It looks like that your UTXO is not available

**Comment by Funman2** [comment] 2023-05-20 13:58
I have no clue how to run these commands in umbrel folder structure, I could ssh into the node with putty though, could you tell me how to run this command on umbrel?

**Comment by Funman2** [comment] 2023-05-20 14:42
The utxo confirmed many times though



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Vincenzo Palazzo ***@***.***>
Datum: 20.05.23 15:42 (GMT+01:00)
An: ElementsProject/lightning ***@***.***>
Cc: Funman2 ***@***.***>, Author ***@***.***>
Betreff: Re: [ElementsProject/lightning] Can't spend sats from onchain utxos after failed channel opening (Issue #6265)


Try lightning-cli listfunds; you should see your transaction id inside the output. Check if it is confirmed on the blockchain.

It looks like that your UTXO is not available

**Comment by vincenzopalazzo** [comment] 2023-05-20 14:46
>you tell me how to run this command on umbrel

No idea, sorry. cc @ShahanaFarooqui 

>The utxo confirmed many times though

Ok maybe the `reserved` is set to true?

**Comment by Funman2** [comment] 2023-05-20 14:49
Yes this could be but I don't know how to see this.
Would it be possible to uninstall and  reinstall core lightning app and then just paste the rsm secret file into the folder in order to restore the wallet? Or is it not working that way?



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Vincenzo Palazzo ***@***.***>
Datum: 20.05.23 16:46 (GMT+01:00)
An: ElementsProject/lightning ***@***.***>
Cc: Funman2 ***@***.***>, Author ***@***.***>
Betreff: Re: [ElementsProject/lightning] Can't spend sats from onchain utxos after failed channel opening (Issue #6265)


you tell me how to run this command on umbrel

No idea, sorry. cc @ShahanaFarooqui<https://github.com/ShahanaFarooqui>

The utxo confirmed many times though

Ok maybe the reserved is set to true?

**Comment by Funman2** [comment] 2023-05-20 14:50
Is it possible to change the reserved?



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Vincenzo Palazzo ***@***.***>
Datum: 20.05.23 16:46 (GMT+01:00)
An: ElementsProject/lightning ***@***.***>
Cc: Funman2 ***@***.***>, Author ***@***.***>
Betreff: Re: [ElementsProject/lightning] Can't spend sats from onchain utxos after failed channel opening (Issue #6265)


you tell me how to run this command on umbrel

No idea, sorry. cc @ShahanaFarooqui<https://github.com/ShahanaFarooqui>

The utxo confirmed many times though

Ok maybe the reserved is set to true?

**Comment by ShahanaFarooqui** [comment] 2023-05-20 15:58
@Funman2 reinstalling the application will not solve the issue. Because both applications are just showing you the information provided by core lightning. So if UTXO is not available in core lightning node, it cannot be available through the application as well.

Restoring the wallet will also give you the same results. If the UTXO has been spent/is reserved, it will not be changed with wallet restoration.

Changing the reserved status is not possible once the transaction has already been initialized/is pending.  I would suggest to search for your transaction status in the mempool first. If it is still in the queue then you can CPFP to get it confirmed sooner.

You can follow below steps to check funds in Umbre:
- ssh into umbrel
- docker container ps
- get the container id for `lncm/clightning:v22.11.1` image
- docker exec -it <container-id-from-prev-step> /bin/bash
- Run `lightning-cli listfunds`

**Comment by Funman2** [comment] 2023-05-20 16:05
Yes but the channel opening message did not provide the tx or at least I could not find it in mempool... then also after restart the channel was completely gone without a trace

**Comment by Funman2** [comment] 2023-05-20 16:13
I will try these steps once I am back home!

**Comment by ShahanaFarooqui** [comment] 2023-05-20 16:38
If your container doesn't have lightning-cli, please try other options described [here](https://community.corelightning.org/c/developers/core-lightning-calling-rpc-and-generating-a-rune) to call `listfunds` command instead.

**Comment by Funman2** [comment] 2023-05-20 17:03
Thanks to help from umbrel support i got this info with list funds:

lightning-cli: Some parameters are malformed, cannot create a valid JSON-RPC req                                                                                                                     uest: { "jsonrpc" : "2.0", "method" : "help", "id" : "cli:help#6807","filter": i                                                                                                                     ghtning-dir=~/umbrel/app-data/core-lightning/data/lightningd, "params" :[ ] }
umbrel@umbrel:~ $ sudo ~/umbrel/scripts/app compose core-lightning exec lightnin                                                                                                                     gd lightning-cli listfunds
{
   "outputs": [
      {
         "txid": "28d62f167fbb0b39a8b099a5fd232a9688c7d004a87d8d6fba3ff6c3fac92c                                                                                                                     8f",
         "output": 1,
         "value": 100000,
         "amount_msat": "100000000msat",
         "scriptpubkey": "00145eced8de1f33eba71d03e183da3d8caee9ffb79a",
         "address": "bc1qtm8d3hslx046w8gruxpa50vv4m5lldu6wx00n7",
         "status": "confirmed",
         "blockheight": 790498,
         "reserved": true,
         "reserved_to_block": 792517
      },
      {
         "txid": "e24fcf13402a0dd0648bfcc97eff563b656366a986fc97ce651ea41dd4972b                                                                                                                     8d",
         "output": 0,
         "value": 1000000,
         "amount_msat": "1000000000msat",
         "scriptpubkey": "00142a8a0e74e6e15cb05ca6ed7e9136df7a2a82786d",
         "address": "bc1q929qua8xu9wtqh9xa4lfzdkl0g4gy7rdzkhpcp",
         "status": "confirmed",
         "blockheight": 790501,
         "reserved": true,
         "reserved_to_block": 792517
      }
   ],
   "channels": []

**Comment by Funman2** [comment] 2023-05-20 17:05
unfortunately the block already passed but i still can not spend the funds still...:-(

**Comment by Funman2** [comment] 2023-05-20 18:08
sudo ~/umbrel/scripts/app compose core-lightning exec lightningd lightning-cli getinfo
> {
>    "id": "03e9031fdf5010fa7d28..................................................c",
>    "alias": "LIGHTNINGROUTE",
>    "color": "03e903",
>    "num_peers": 1,
>    "num_pending_channels": 0,
>    "num_active_channels": 0,
>    "num_inactive_channels": 0,

**Comment by vincenzopalazzo** [comment] 2023-05-20 19:14
looks like that your utxo are reserved, maybe you open some channels?

**Comment by Funman2** [comment] 2023-05-20 19:15
Yes I opened one  channel but it disappeared after node restart...

**Comment by Funman2** [comment] 2023-05-20 19:17
the only details i have is a downloaded csv file from Ride the Lightning app:
[Pending-inactive-channels.csv](https://github.com/ElementsProject/lightning/files/11523049/Pending-inactive-channels.csv)

**Comment by ShahanaFarooqui** [comment] 2023-05-22 21:03
@Funman2 Closing this issue as your utxos are currently reserved and will be available again after block 792517.

**Closed by ShahanaFarooqui** 2023-05-22 21:03 UTC
Labels: in diagnostic
