### ISSUE TITLE
ubuntu clnrest plugin dependencies

### ISSUE THREAD

**Issue by mdance** [ElementsProject/lightning#7706] opened 2024-10-01 01:00 UTC
### Issue and Steps to Reproduce

How do I get the clnrest plugin dependencies installed on Ubuntu 23.04?

pip install -r requirements.txt                                                                                                         heads/v23.08 * [ 6:57 PM ]
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

I've tried installed things through python -m venv .venv and pip installing things, but then I dont know how to get the plugin=bla to run it through the venv, I've tried creating a bash script to activate the environment, that complains about the get manifest, I've tried pyinstaller --onefile --add-data "utilities:utilities" --hidden-import=json5 --hidden-import=pyln --hidden-import=pyln.client clnrest.py to build the god damn thing into a binary

I can't believe its this difficult to get this up and running

**Comment by cdecker** [comment] 2024-10-17 15:04
Duplicate of #7665

**Closed by cdecker** 2024-10-17 15:04 UTC
