### ISSUE TITLE
Is it too extreme to close a channel with an almost acceptable fee?

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1219] opened 2018-03-15 05:39 UTC
### Issue and Steps to Reproduce

2018-03-14T00:40:48.802Z lightningd(11525): lightning_channeld-024b82d69859d63f9fce375041a34e61f4bfd445494b41d873ae7505322323d384 chan #108: peer_in WIRE_ERROR
2018-03-14T00:40:48.802Z lightningd(11525): 024b82d69859d63f9fce375041a34e61f4bfd445494b41d873ae7505322323d384 chan #108: Peer permanent failure in CHANNELD_NORMAL: lightning_channeld: received ERROR channel cc6662f20caa17519b94957572319e18fd0b8f8de1cda1dbf84ee75bac9a70f5: update_fee 13318 outside range 523-13290

The channel subsequently closed.  I think we closed it, right?

Why would their relatively close fee to my range be considered such an outliar?  It seems extreme to me that a fee that is 0.2% different from the max fee but the max fee is 2,500% different from the min fee seems extreme to close the channel, causing an on-chain Bitcoin fee costing me far more than a potential LN fee level.  Does their node know my max fee range?

I need to understand fees better and how this dynamic works.

### `getinfo` output
"version" : "v0.5.2-2016-11-21-2278-g74a444e", "blockheight" : 513591, "network" : "bitcoin" }

**Comment by ZmnSCPxj** [comment] 2018-03-15 06:49
Unfortunately this is a slippery slope.  If we accept just 28 over the limit, we increase the limit by 28.  Should we accept a feerate just 28 over the new limit now?  Then we increased the limit again!  Where do we stop?

(note also that it is the **other** side which is complaining --- it says "received ERROR", it is not our own error.  Notice also the peer_***in*** `WIRE_ERROR`.)

https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#updating-fees-update_fee `update_fee` is about onchain fees, not about LN fee level.

So what happened is this:

1.  You established a channel with another node.  Both of you could agree on a fee to put on the commitment transaction.
2.  Your bitcoin node decides that fees should be higher.  You propose the higher fees to the counterparty via `update_fee` so that the commitment transaction can be updated.
3.  The counterparty asks its own bitcoin node.  That one says the fees are beyond the recommended range of 523-13290.
4.  The counterparty thinks you want too high fees.  Since there is a disagreement between you (you want higher fees, your counterparty wants lower fees) you really cannot keep operating the channel.
5.  The channel closes unilaterally (both of you will attempt to broadcast due to the error message, and whichever one the miners pick up is the close that happened).  Note that the commitment transactions are old transactions that both of you have previously agreed as having reasonable fees.
6.  The two of you cannot make a bilateral close --- remember, both of you have a disagreement on what reasonable fees are!  So the only recourse is to use what the two of you have agreed upon.

**Comment by Ulmo** [comment] 2018-03-17 15:16
Is there a stage at which one side can back off if the negotiation for increase failed?  For instance, at step 4, can I say "ok, fine, let's keep the old range for a while"?  To me, this is a race condition, where I have an earlier view into higher fees, and raise the fee a bit, and the other side is lagging in this realization and correctly denies that, and I can say "ok, well, I'll try again later", and then when the other side drops out of my range of negotiation, then I say "it's over, thanks".  So, there should be a negotation range where their counteroffer is acceptable, but outside of which it is not, so that as things change through time, there aren't hard edges slicing up the funds.  Do the BOLTs allow this counteroffer backoff type thing?

**Comment by ZmnSCPxj** [comment] 2018-03-17 15:48
There is no negotiation for onchain fees yet.  There was a discussion started about a change in onchain fee scheme: https://lists.linuxfoundation.org/pipermail/lightning-dev/2018-January/000935.html you could try to revive it.

As is, there is a SHOULD in the BOLT#2 text:

>    - if the `update_fee` is too low for timely processing, OR is unreasonably large:
>        - SHOULD fail the channel.

There is no protocol for negotiating back and forth for a "reasonable" fee range: there is no `reject_update_fee` for the counterparty to use to request to keep the fee range down.

The "SHOULD" gives us a little leeway, though.

The best we can do now without a spec change is something like this:

1.  If the funding side requests an unreasonably low or high fee rate beyond our range:
    - If this is the first time they went outside our range, and it is within +/-50% of the previous, acceptable fee rate, accept it.
    - otherwise fail the channel.
2.  If the funding side requests a reasonable fee rate:
    - clear the flag we use above for the "first time".

Over all, it might be better to bring this up in the lightning-dev mailinglist, as it affects multiple implementations.

**Comment by ZmnSCPxj** [comment] 2019-06-13 05:44
#1650 implements smoothing of our proposed `update_fee` value, which is really the root cause here (i.e. the `lnd` node disagreed with our proposed fee).  Can we close this?

**Comment by ZmnSCPxj** [comment] 2019-06-17 04:04
Closing, since root cause seems to have gotten fixed anyway.

**Closed by ZmnSCPxj** 2019-06-17 04:04 UTC
Labels: fee, pending-fix-confirmation, question
