### ISSUE TITLE
listpeers crashes lightningd

### ISSUE THREAD

**Issue by fixone** [ElementsProject/lightning#1694] opened 2018-07-13 13:59 UTC
After starting lightningd a simple ```listpeers``` command crashes lightningd with log showing

```
2018-07-13T13:57:25.379Z lightning_gossipd(22864): Received channel_update for channel 1297023:14:0(1) now ACTIVE was ACTIVE (from subdaemon)
2018-07-13T13:57:26.198Z lightning_gossipd(22864): Failed connected out for 0343d2535901b68df40047a6fd8e8caba81709ec18108852472acb9c30e75ecc12
2018-07-13T13:57:26.199Z lightning_gossipd(22864): ...will try again in 64 seconds
2018-07-13T13:57:26.982Z lightning_gossipd(22864): Failed connected out for 034c00822bf35de2e18c174a722ba92819047bdf8d4caa3c335ac48cac404c2277
2018-07-13T13:57:26.982Z lightning_gossipd(22864): ...will try again in 64 seconds
2018-07-13T13:57:36.074Z lightningd(22855): Connected json input
2018-07-13T13:57:36.074Z lightning_gossipd(22864): REPLY WIRE_GOSSIP_GETPEERS_REPLY with 0 fds
2018-07-13T13:57:36.084Z lightningd(22855): FATAL SIGNAL 11 (version v0.6-64-g14c6310)
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: common/daemon.c:42 (crashdump) 0x431a49
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: (null):0 ((null)) 0x7841abd744af
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: (null):0 ((null)) 0x7841abeae9b0
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: ./bitcoin/pubkey.h:20 (pubkey_eq) 0x423888
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: lightningd/peer_control.c:784 (gossipd_getpeers_complete) 0x425592
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: lightningd/subd.c:307 (sd_msg_reply) 0x42b8cf
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: lightningd/subd.c:444 (sd_msg_read) 0x42be2c
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x466910
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x4673e7
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x467425
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x468f91
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: lightningd/lightningd.c:442 (main) 0x414f10
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: (null):0 ((null)) 0x7841abd5f82f
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: (null):0 ((null)) 0x4035d8
2018-07-13T13:57:36.084Z lightningd(22855): backtrace: (null):0 ((null)) 0xffffffffffffffff
```

**Comment by fixone** [comment] 2018-07-13 14:11
same thing with the latest git version
```
2018-07-13T14:10:21.606Z lightning_gossipd(28335): Received channel_update for 1346823:24:0 with old time 1530268192
2018-07-13T14:10:21.607Z lightning_gossipd(28335): Received channel_update for 1346855:6:0 with old time 1530271473
2018-07-13T14:10:21.646Z lightning_gossipd(28335): Received channel_update for 1346955:49:0 with old time 1530280351
2018-07-13T14:10:21.653Z lightning_gossipd(28335): Received channel_update for 1346964:38:0 with old time 1530280816
2018-07-13T14:10:25.233Z lightning_gossipd(28335): Received channel_update for channel 1297023:14:0(1) now ACTIVE was ACTIVE (from subdaemon)
2018-07-13T14:10:30.201Z lightningd(28327): Connected json input
2018-07-13T14:10:30.202Z lightning_gossipd(28335): REPLY WIRE_GOSSIP_GETPEERS_REPLY with 0 fds
2018-07-13T14:10:30.221Z lightningd(28327): FATAL SIGNAL 11 (version v0.6-68-g891dee7)
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: common/daemon.c:42 (crashdump) 0x431aaf
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: (null):0 ((null)) 0x7cb794ad44af
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: (null):0 ((null)) 0x7cb794c0e9b0
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: ./bitcoin/pubkey.h:20 (pubkey_eq) 0x4238ee
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: lightningd/peer_control.c:784 (gossipd_getpeers_complete) 0x4255f8
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: lightningd/subd.c:307 (sd_msg_reply) 0x42b935
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: lightningd/subd.c:444 (sd_msg_read) 0x42be92
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x466976
2018-07-13T14:10:30.221Z lightningd(28327): backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x46744d
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x46748b
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x468ff7
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: lightningd/lightningd.c:442 (main) 0x414f10
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: (null):0 ((null)) 0x7cb794abf82f
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: (null):0 ((null)) 0x4035d8
2018-07-13T14:10:30.222Z lightningd(28327): backtrace: (null):0 ((null)) 0xffffffffffffffff

```

**Comment by Xian001** [comment] 2018-07-13 15:29
Well, good to know I'm not entirely crazy, and others are experiencing this same issue. 

I thought I might have been related to the f#cked up state of one of my configs...

**Comment by sumBTC** [comment] 2018-07-13 22:21
Confirm this issue (also as reported by Xian001) Went back to version: v0.5.2-2016-11-21-2867-g56046d4 (via: git reflog followed by git reset --hard 56046d4)

**Comment by cdecker** [comment] 2018-07-14 11:42
Duplicate of #1680

**Closed by cdecker** 2018-07-14 11:42 UTC
