### ISSUE TITLE
node is crashing after upgrade...

### ISSUE THREAD

**Issue by gonzzza007** [ElementsProject/lightning#2726] opened 2019-06-09 14:39 UTC
After latest upgrade (b6b548a) my node is crashing with an error message:

```
2019-06-09T14:37:35.485Z lightning_gossipd(6557): gossip_store node_announcement 1144022 replaces 1144022!
2019-06-09T14:37:35.485Z lightning_gossipd(6557): pending node_announcement <298 character hash> malformed? (version v0.7.0-525-g9e511cb)
2019-06-09T14:37:35.485Z lightning_gossipd(6557): backtrace: common/daemon.c:45 (send_backtrace) 0x4b0857
2019-06-09T14:37:35.485Z lightning_gossipd(6557): backtrace: common/status.c:192 (status_failed) 0x4b5ab4
2019-06-09T14:37:35.486Z lightning_gossipd(6557): backtrace: gossipd/routing.c:1315 (process_pending_node_announcement) 0x4a4b74
2019-06-09T14:37:35.486Z lightning_gossipd(6557): backtrace: gossipd/routing.c:1892 (routing_add_channel_update) 0x4a6026
2019-06-09T14:37:35.486Z lightning_gossipd(6557): backtrace: gossipd/gossip_store.c:582 (gossip_store_load) 0x4a1285
2019-06-09T14:37:35.486Z lightning_gossipd(6557): backtrace: gossipd/gossipd.c:1862 (gossip_init) 0x4abaad
2019-06-09T14:37:35.488Z lightningd(6545): --------------------------------------------------
2019-06-09T14:37:35.488Z lightningd(6545): Server started with public key <node public key>, alias <alias> (color #<color>) and lightningd v0.7.0-525-g9e511cb
2019-06-09T14:37:35.491Z lightning_gossipd(6557): backtrace: gossipd/gossipd.c:2702 (recv_req) 0x4adb74
2019-06-09T14:37:35.492Z lightning_gossipd(6557): backtrace: common/daemon_conn.c:31 (handle_read) 0x4b0d1c
2019-06-09T14:37:35.493Z lightning_gossipd(6557): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x4d101a
2019-06-09T14:37:35.493Z lightning_gossipd(6557): backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x4d1a32
2019-06-09T14:37:35.493Z lightning_gossipd(6557): backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x4d1a6f
2019-06-09T14:37:35.493Z lightning_gossipd(6557): backtrace: ccan/ccan/io/poll.c:445 (io_loop) 0x4d3bb7
2019-06-09T14:37:35.494Z lightning_gossipd(6557): backtrace: gossipd/gossipd.c:2827 (main) 0x4ade7e
2019-06-09T14:37:35.494Z lightning_gossipd(6557): backtrace: (null):0 ((null)) 0xb7be4e80
2019-06-09T14:37:35.497Z lightning_gossipd(6557): backtrace: (null):0 ((null)) 0x49c432
2019-06-09T14:37:35.498Z lightning_gossipd(6557): STATUS_FAIL_INTERNAL_ERROR: pending node_announcement <298 character hash> malformed?
2019-06-09T14:37:35.498Z lightning_gossipd(6557): Status closed, but waitpid 6557 says No child processes
```
I am using Ubuntu 18.04.2 LTS
4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:34:06 UTC 2019 i686 i686 i686 GNU/Linux
ps. I have removed node announcement hash, public key and alias

**Comment by m-schmoock** [comment] 2019-06-09 15:14
Duplicate of https://github.com/ElementsProject/lightning/issues/2719

**Comment by ZmnSCPxj** [comment] 2019-06-11 01:08
#2719 has been closed, will also close this.

**Closed by ZmnSCPxj** 2019-06-11 01:08 UTC
