### ISSUE TITLE
error: code = Code(202) desc = feerate_per_kw 7500 above maximum 6305

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1233] opened 2018-03-17 16:28 UTC
### Issue and Steps to Reproduce

On my LND node, I tried to open a channel:

        lncli openchannel 03a3c1fc0a489e2872a2afe8fa16c2714b5fe80d52d8c1ce8ecc4361a77391da82 9000000 7000000

The interpretation is:

           lncli openchannel [command options] node-key local-amt push-amt
        
           The channel will be initialized with local-amt satoshis local and push-amt
  satoshis for the remote node.

The response I get comes from the C-Lightning node, which I know, since their spelling of the variable is different than LND's:

        [lncli] rpc error: code = Code(202) desc = feerate_per_kw 7500 above maximum 6305

"feerate_per_kw" is round in the C-Lightning source, but not the LND source; LND calls it "fee_per_kw".  That way, I know the error comes from the other end.  Plus, the logs of both also agree with that interpretation.  Here's the error message from my C-Lightning node:

        2018-03-17T16:24:11.016Z lightningd(17595): 03b1be68b8f564fe53f5456cf4bec901ba968fb72ed7291279ab0c87e0d22f1f49 chan #141: Opening channel: sent ERROR feerate_per_kw 7500 above maximum 6305

I seem to have found some discussion of what that means in the source code, which refers to:

https://github.com/lightningnetwork/lightning-rfc/blob/master/03-transactions.md

in the section Fees.

### `getinfo` output
        { "id" : "031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a", "port" : 9735, "address" : 

                [ 

                        { "type" : "ipv4", "address" : "24.4.228.213", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2347-g4ffd5e2", "blockheight" : 513962, "network" : "bitcoin" }

**Comment by ZmnSCPxj** [comment] 2018-03-17 16:44
Root cause is same as #1219, i.e. feerate disagreement.

**Comment by ZmnSCPxj** [comment] 2018-03-17 16:54
You can use `dev-setfees` command to force feerates your c-lightning nodes accept.

**Comment by Ulmo** [comment] 2018-03-17 16:56
Yes, I just figured that out again, but the problem is they become persistent and it won't auto-regulate after that.

**Comment by cdecker** [comment] 2019-01-06 21:12
This has mostly been addressed by the fee smoothing implemented in PR #1650

**Closed by cdecker** 2019-01-06 21:12 UTC
Labels: fee
