### ISSUE TITLE
make check ends with "… documented but not in schema!"

### ISSUE THREAD

**Issue by jsarenik** [ElementsProject/lightning#4904] opened 2021-11-04 13:30 UTC
### Issue and Steps to Reproduce

When I compile locally and run `make check` I get following error:

```
max-dust-htlc-exposure-msat undocumented!
```

@vincenzopalazzo

**Comment by jsarenik** [comment] 2021-11-04 13:32
By the way, for local compilation I always use following magic `fresh-build.sh` script which no one should try to run if at home alone:

```
#!/bin/sh -e

cd ~/src/lightning
git submodule deinit --all --force
git clean -xffd
git tag -l | xargs git tag -d && git fetch -t
git fetch origin
git rebase origin/master
git submodule update --init --recursive
./configure --enable-developer
make -j4
```

**Comment by vincenzopalazzo** [comment] 2021-11-04 15:07
Mh, it looks like that we have missed the propriety in some doc files. This should be fixed the `make check` and fixed the regression on this side by adding the check on the doc with the integration testing.

Commit: https://github.com/ElementsProject/lightning/pull/4782/commits/272fb7245da55be082eb158d3384f4a19c73a22f

**Comment by jsarenik** [comment] 2021-11-05 08:03
Yes. The patch works well. Thank you @vincenzopalazzo ! I tested and ACKed the PR. Once #4782 is merged, this issue can be closed.

**Closed** 2021-11-28 00:25 UTC
