### ISSUE TITLE
consistent FATAL SIGNAL 11 RECEIVED + segfault after broadcasting revoked commit-tx

### ISSUE THREAD

**Issue by SimonVrouwe** [ElementsProject/lightning#1160] opened 2018-03-03 16:33 UTC
### Issue and Steps to Reproduce
Today I did 'make clean' 'git pull' and 'sudo make' and cleaned .lightning folders, on a Debian machine and on an OpenSUSE machine connected by LAN. I created a channel between the two peers, did a payment an then manually broadcast the 'old' (revoked) commit tx using bitcoin-cli sendrawtransaction. The other peer then broadcasted penalty tx which confirmed. But then when trying to exit lightningd using 'lightning-cli stop' command, it crashes, or was already crashed. Lightningd keeps crashing when trying to restart. This happens on both peers. Starting with a clean .lightning folder runs fine. The crashing .lightning settings folder of one peer is here:
[lightning_crash.tar.gz](https://github.com/ElementsProject/lightning/files/1777640/lightning_crash.tar.gz)

### `getinfo` output
{ "id" : "03643bdacd334a9ced1754f1ea4c2bdd351d25ffa968fd289f21e190e0cd7d9e98", "port" : 9735, "address" : 
        [  ], "version" : "v0.5.2-2016-11-21-2175-g35ce1317", "blockheight" : 1287175, "network" : "testnet" }

stdout with segfault:
2018-03-03T16:09:32.217Z lightningd(28259): 0303358663d5186a8c5a6fbdee1474833ecb49acce47a225cff3dace685145a0de chan #2: Funding tx c7e5e50541983de988d80ddc843449e5cc666c9915018464d0a460dfddda3b2a depth 21 of 1
2018-03-03T16:09:32.218Z lightningd(28259): FATAL SIGNAL 11 RECEIVED
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/log.c:504 (log_crash) 0x41584d
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: (null):0 ((null)) 0x7fed8cf9cfdf
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: (null):0 ((null)) 0x7fed8cfb2351
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: (null):0 ((null)) 0x7fed8cfdb2f8
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: ccan/ccan/tal/str/str.c:67 (do_vfmt) 0x46b330
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: ccan/ccan/tal/str/str.c:91 (tal_vfmt) 0x46b3f0
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/log.c:264 (logv) 0x414c8c
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/log.c:320 (log_) 0x414fff
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/peer_control.c:534 (funding_lockin_cb) 0x422593
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/watch.c:221 (txw_fire) 0x42aa85
2018-03-03T16:09:32.222Z lightningd(28259): backtrace: lightningd/watch.c:289 (watch_topology_changed) 0x42acee
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: lightningd/chaintopology.c:335 (updates_complete) 0x407227
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: lightningd/chaintopology.c:429 (get_new_block) 0x40768f
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: lightningd/bitcoind.c:657 (process_getblockhash) 0x40589d
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: lightningd/bitcoind.c:186 (bcli_finished) 0x40435a
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x461de1
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x461e00
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x46c3ea
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x46c88d
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/tal/tal.c:509 (tal_free) 0x46cc97
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/io/io.c:443 (io_close) 0x460a7d
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ccan/ccan/io/poll.c:314 (io_loop) 0x4621f0
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: lightningd/lightningd.c:405 (main) 0x413f90
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: (null):0 ((null)) 0x7fed8cf88724
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: ../sysdeps/x86_64/start.S:118 ((null)) 0x4037a8
2018-03-03T16:09:32.223Z lightningd(28259): backtrace: (null):0 ((null)) 0xffffffffffffffff

Fatal signal 11. 0x415933 log_crash
        lightningd/log.c:530
0x7fed8cf9cfdf ???
        ???:0
0x7fed8cfb2351 ???
        ???:0
0x7fed8cfdb2f8 ???
        ???:0
0x46b330 do_vfmt
        ccan/ccan/tal/str/str.c:67
0x46b3f0 tal_vfmt
        ccan/ccan/tal/str/str.c:91
0x414c8c logv
        lightningd/log.c:264
0x414fff log_
        lightningd/log.c:320
0x422593 funding_lockin_cb
        lightningd/peer_control.c:534
0x42aa85 txw_fire
        lightningd/watch.c:221
0x42acee watch_topology_changed
        lightningd/watch.c:289
0x407227 updates_complete
        lightningd/chaintopology.c:335
0x40768f get_new_block
        lightningd/chaintopology.c:429
0x40589d process_getblockhash
        lightningd/bitcoind.c:657
0x40435a bcli_finished
        lightningd/bitcoind.c:186
0x461de1 destroy_conn
        ccan/ccan/io/poll.c:183
0x461e00 destroy_conn_close_fd
        ccan/ccan/io/poll.c:189
0x46c3ea notify
        ccan/ccan/tal/tal.c:240
0x46c88d del_tree
        ccan/ccan/tal/tal.c:400
0x46cc97 tal_free
        ccan/ccan/tal/tal.c:509
0x460a7d io_close
        ccan/ccan/io/io.c:443
0x4621f0 io_loop
        ccan/ccan/io/poll.c:314
0x413f90 main
        lightningd/lightningd.c:405
0x7fed8cf88724 ???
        ???:0
0x4037a8 ???
        ../sysdeps/x86_64/start.S:118
0xffffffffffffffff ???
        ???:0
Log dumped in crash.log
Segmentation fault (core dumped)

**Comment by cdecker** [comment] 2018-03-03 18:44
Probably a duplicate of #1114

**Comment by SimonVrouwe** [comment] 2018-03-04 17:12
e3a09ddac926254ca253117ae4b06f117ee161ed fixed it, thanks!

**Comment by cdecker** [comment] 2018-03-04 21:48
@SimonVrouwe thanks for the confirmation, glad we could find the issue and solve it :wink:

**Closed by cdecker** 2018-03-04 21:48 UTC
Labels: bug, duplicate
