### ISSUE TITLE
Dinner for c-lightning contributors

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#3187] opened 2019-10-20 12:01 UTC
### Issue and Steps to Reproduce

We're having a c-lightning contributor dinner tonight in Berlin at 7. Find us for details!

**Comment by m-schmoock** [comment] 2019-10-20 13:54
I'm sorry I can't attend since I booked my holidays few weeks before the LN conference was even announced . Have fun and see you next time for sure!

**Comment by practicalswift** [comment] 2019-10-20 17:35
Thanks for the invitation! I can't attend but I hope you all have an amazing dinner!

**Comment by conscott** [comment] 2019-10-20 18:41
Ah, I missed this email until now :(

**Comment by renepickhardt** [comment] 2019-10-20 20:14
You forgot to add the output of `lightning-cli getinfo` it's really hard to debug this. Maybe we could reproduce this in future?

**Comment by cdecker** [comment] 2019-10-20 21:38
> You forgot to add the output of `lightning-cli getinfo` it's really hard to debug this. Maybe we could reproduce this in future?

Agreed, best to add an integration test to run on every PR :-)

**Comment by darosior** [comment] 2019-10-21 07:52
> Agreed, best to add an integration test to run on every PR :-)

Definitely to be included before 0.7.3!

**Comment by niftynei** [comment] 2019-10-22 13:49
closing this, unable to reproduce locally :'(

**Closed by niftynei** 2019-10-22 13:49 UTC
Labels: gossip

**Comment by Saibato** [comment] 2019-10-22 14:07
> closing this, unable to reproduce locally :'(

I have this feeling the bug hint was in the late dessert, irreproduceable tACK , Thx :heart_eyes:

**Comment by jb55** [comment] 2019-10-23 13:12
awesome dinner, thanks for the invite!
