### ISSUE TITLE
Funds with status unconfirmed

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/lightning#1215] opened 2018-03-14 09:02 UTC
My funds appear unconfirmed when they have been confirmed.

```
{
    "channels": [
        {
            "channel_sat": 9390,
            "channel_total_sat": 100000,
            "funding_txid": "63ec8362b477d8443a31dd82fcbdfaab771c53242d7bc3634461732aac6be59c",
            "peer_id": "0270762bf41cd8f022877f8ae4f6cd9fc3ba26ed020705a6313f1e91ceeb729ca3",
            "short_channel_id": "512284:2048:1"
        }
    ],
    "outputs": [
        {
            "output": 0,
            "status": "unconfirmed",
            "txid": "32d8b3380b0df4365ed8b506f611ae15c187e181f4a5b108b1aef105c0aa974e",
            "value": 861
        },
        {
            "output": 0,
            "status": "unconfirmed",
            "txid": "923425bd56c06cd5c817ce87caca75843ee4338d2b3189cfea91c4b8b7756083",
            "value": 96608
        }
    ]
}
```

**Comment by djmelik** [comment] 2018-03-14 09:32
I can also confirm this issue. 

```
    "outputs": [
        {
            "output": 0,
            "status": "unconfirmed",
            "txid": "69ca3332ba2b3933fd6900045a02e0e2e62f468a2a6392ead73f531d45ccc53f",
            "value": 5020
        },
        {
            "output": 0,
            "status": "unconfirmed",
            "txid": "fb60120bf713eb8409e9dbd3a16bf27c5e3a1387c299ba9832716314f58f3ba9",
            "value": 42881
        }
    ]
```

```
$ lightning-cli dev-rescan-outputs | egrep '69ca3332|fb60120b'
		{ "txid" : "fb60120bf713eb8409e9dbd3a16bf27c5e3a1387c299ba9832716314f58f3ba9", "output" : 0, "oldstate" : 0, "newstate" : 0 },
		{ "txid" : "69ca3332ba2b3933fd6900045a02e0e2e62f468a2a6392ead73f531d45ccc53f", "output" : 0, "oldstate" : 0, "newstate" : 0 },
```

I am running c-lightning with debug logging enabled. When I ran dev-rescan-outputs, I saw bitcoin-cli gettxout being called against each of my outputs. I didn't see those two specific txids being called. I hope this helps.

**Comment by cdecker** [comment] 2018-03-14 14:34
This is a known issue (see #1209 for details). The problem is that the `their_unilateral/to_us` output is not sent to an address from the HD key derivation, but is injected by `onchaind`. We therefore don't track it in the `outpoint_filter` that updates the `spend_height`. The good news though is that the confirmed/unconfirmed status is not used for coin selection yet, so it has no impact on the `withdraw` and `fundchannel` calls, i.e., you can just withdraw them and creats channels normally.

**Comment by cdecker** [comment] 2018-03-14 14:35
Duplicate of #1209

**Comment by NicolasDorier** [comment] 2018-03-14 15:49
feel free to close the duplicate

**Closed** 2018-03-14 17:01 UTC
Labels: duplicate, wallet
