### ISSUE TITLE
HSM did not give init reply

### ISSUE THREAD

**Issue by brandoncollins7** [ElementsProject/lightning#2156] opened 2018-12-10 01:46 UTC
Running via example docker-compose elementsproject/lightningd:latest connected to a remote node I am receiving the following error:

lightning             | C-Lightning starting
lightning             | 2018-12-10T01:45:15.826Z lightningd(6): testing /usr/bin/lightning_channeld
lightning             | 2018-12-10T01:45:15.827Z lightningd(6): testing /usr/bin/lightning_closingd
lightning             | 2018-12-10T01:45:15.828Z lightningd(6): testing /usr/bin/lightning_connectd
lightning             | 2018-12-10T01:45:15.829Z lightningd(6): testing /usr/bin/lightning_gossipd
lightning             | 2018-12-10T01:45:15.829Z lightningd(6): testing /usr/bin/lightning_hsmd
lightning             | 2018-12-10T01:45:15.830Z lightningd(6): testing /usr/bin/lightning_onchaind
lightning             | 2018-12-10T01:45:15.830Z lightningd(6): testing /usr/bin/lightning_openingd
lightning             | 2018-12-10T01:45:15.867Z lightning_hsmd(16): pid 16, msgfd 13
lightning             | lightningd: HSM did not give init reply

Also, I am following the instructions here: https://medium.com/coinmonks/installing-lightning-network-part-2-here-we-go-again-ed5a84f9cade. When I run "docker exec lightning lightning-cli getinfo" I am shown the error, "lightning-cli: Connecting to 'lightning-rpc': No such file or directory". Not sure if these are somehow related?

**Comment by cdecker** [comment] 2018-12-10 08:49
Can you tell us which docker image is being run here?

```
docker images
docker ps -a
```

This should give you a good idea. It could be that this inadvertently pulled a dev version since the compose file does not specify a tag. You can specify the tag by adding `:v0.6` to the `image` field.

**Comment by brandoncollins7** [comment] 2018-12-10 14:39
I also tried with v0.6 and I received one new message in the log:

lightning             | C-Lightning starting
lightning             | 2018-12-10T02:57:32.629Z lightningd(6): testing /usr/bin/lightning_channeld
lightning             | 2018-12-10T02:57:32.630Z lightningd(6): testing /usr/bin/lightning_closingd
lightning             | 2018-12-10T02:57:32.631Z lightningd(6): testing /usr/bin/lightning_gossipd
lightning             | 2018-12-10T02:57:32.632Z lightningd(6): testing /usr/bin/lightning_hsmd
lightning             | 2018-12-10T02:57:32.633Z lightningd(6): testing /usr/bin/lightning_onchaind
lightning             | 2018-12-10T02:57:32.634Z lightningd(6): testing /usr/bin/lightning_openingd
**lightning             | 2018-12-10T02:57:32.933Z lightningd(6): Client: Received message 11 from client**
lightning             | lightningd: HSM did not give init reply

**Comment by brandoncollins7** [comment] 2018-12-10 19:34
It appears it might have been some issue with the way I mapped the volume to my local drive on windows. 
This is what I have, I saw the folder and db created on my drive when I start the container.
volumes:
      - "./clightning:/root/.lightning"

After changing it to the following, it seems to work but then I have no persistence of my lightning data between container restarts:
volumes:
      - "./clightning:/root/.lightning"

**Comment by Kukks** [comment] 2018-12-10 19:49
Same issue with windows and latest docker. Must be one of the crappy windows docker volume limitations

**Comment by brandoncollins7** [comment] 2018-12-10 19:57
What could the limitation be given the entire db file with schema and data is populated just fine on the drive?

**Comment by Kukks** [comment] 2018-12-10 20:48
If I remember correctly, any volumes mapped to the local file system in Windows are forced to have specific permissions that probably trigger some security mechanism?  I am guessing `hsmd` is `hardware security module daemon`   so that could be the cause but I'm just spitballing.

**Comment by brandoncollins7** [comment] 2018-12-10 21:58
Interesting, the drive is shared in the docker daemon, it should have full permissions. I guess a workaround for this is to just use a normal docker volume. It appears to be working and persisting my data, although I haven't tried it directly in Windows... I am using the Ubuntu shell now by following these directions: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly. Oddly, using the path in the link:

volumes:
      - "/scratch/bitcoin/mainnet/clightning:/root/.lightning"

Still does not seem to create the file system entry on the ubuntu machine. But it does run ok.

**Comment by cdecker** [comment] 2018-12-11 14:16
Oh, that's interesting. I had never tried Docker on windows. Would you know how it is implemented? I expect it to be virtualbox based like the Mac version and volumes are NFS mounts.

**Comment by Kukks** [comment] 2018-12-11 14:39
The old windows docker tool used VirtualBox. Nowadays it hooks up with HyperV somehow( which causes the issue that you can't use VirtualBox and Docker at the same time)

**Comment by cdecker** [comment] 2019-01-06 20:55
Ok, not too familiar with HyperV, but it seems like a good solution for docker on windows.

Can I conclude from your comment above that a working solution was found and we can close this issue?

**Comment by darosior** [comment] 2019-11-04 13:24
@brandoncollins7 

> Still does not seem to create the file system entry on the ubuntu machine. But it does run ok.

So this can be closed ?

**Closed** 2019-11-26 11:20 UTC
Labels: docker, windows
