### ISSUE TITLE
Do not route over channels with insufficient funds

### ISSUE THREAD

**Issue by noledge** [ElementsProject/lightning#873] opened 2018-02-01 19:14 UTC
### Issue and Steps to Reproduce
I had 2 open&funded channels (removed channels in other states here)

```
{ "peers" : 
        [ 
                { "id" : "0371190acfb2e92bd1faa6ce4d12ff248798515a92ac903ac14d31b5172d9b2917", "connected" : true, "netaddr" : 
                        [ "176.9.113.240:9735" ], "channels" : 
                        [ 
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "507126:1253:1", "funding_txid" : "dca90fd531f2c958af70000302bf7425957a52fa425b560c2a70cf17619182ae", "msatoshi_to_us" : 470000000, "msatoshi_total" : 470000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },  
                { "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "connected" : true, "netaddr" : 
                        [ "78.63.23.25:9735" ], "channels" : 
                        [ 
                                { "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "507098:1364:1", "funding_txid" : "134a2fbe120229ba0fba4088f322d118fe93348c98b15295a32f2e2d19d9b4b2", "msatoshi_to_us" : 250000000, "msatoshi_total" : 250000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }
```

one has 250000000 msat and one has 470000000 msat.

routing for a payment at blockstream-store gets me the following route:

```lightning-cli getroute 02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432 322917498 0
{ "route" : 
        [ 
                { "id" : "035f1498c929d4cefba4701ae36a554691f526ff60b1766badd5a49b3c8b68e1d8", "channel" : "507098:1364:1", "msatoshi" : 322919242, "delay" : 167 }, 
                { "id" : "02fc7ef232bd958209a2180fb18844388babc48a81d31434e343ecc4d7dd1a9186", "channel" : "505385:1195:1", "msatoshi" : 322917920, "delay" : 23 }, 
                { "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "channel" : "506867:1487:1", "msatoshi" : 322917498, "delay" : 9 } ] }
```

It wants to route a payment over 322919242 msat over a channel that only has 250000000 msat (there are possible routes to the blockstream node over the other channel).

no surprise, the payment fails:

```lightning-cli pay lnbc[...]
lightningd(30192): Sending 322919242 over 3 hops to deliver 322917498
{ "code" : -1, "message" : "failed: WIRE_TEMPORARY_CHANNEL_FAILURE (WIRE_TEMPORARY_CHANNEL_FAILURE: Maximum value exceeded)" }
```

Is it possible to force it over a different route? But the routing algorithm shouldn't pick a channel with unsufficient funds in the first place, especially when there are some with more than enough funds.

### `getinfo` output
```lightning-cli getinfo
{ "id" : "026eb6a8a7d7157a0fefa8597ff9dc7b9c4cf18ad9a79bbbf34b24ff68cbca96c7", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv6", "address" : "xx:5::40", "port" : 9735 }, 
                { "type" : "ipv4", "address" : "x.x.5.40", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1770-g8fcb45c", "blockheight" : 507136, "network" : "bitcoin" }
```

FWIW, I closed that channel (so I can't further try here) to force the payment down the other channel (which has its own problems now, but that's not the scope of this issue)

**Comment by cdecker** [comment] 2018-02-01 21:41
Hm, from your `getinfo` it appears you already have PR #638, so reattempting the payment should have worked. This is because channel failures are now communicated to `gossipd` which updates the local view of the network.

**Comment by ZmnSCPxj** [comment] 2018-02-02 01:19
Yes currently the routing algo completely ignores local channel state.

For now #638 mitigates this by reporting local channel failures which will cause, the routing algo to avoid such a channel for a long time... another issue though.

**Comment by ZmnSCPxj** [comment] 2018-02-02 03:43
An improvement to make later for routing:

1.  Instead of `getroute` calling `find_route` with the local node as source, instead first select a local channel for outgoing payment.
2.  Choose a channel directly connected to the destination node if it has capacity, otherwise select the channel with the lowest capacity that can still fit the payment (best-fit).
3.  Route starting from the corresponding peer to the destination (rather than from ourself).

Why best-fit? Because consider if channels have 5mBTC, 3mBTC, and 2mBTC.  Then we need to make 1.5mBTC payment.  If we chose the 5mBTC channel (worst-fit), then future call, we cannot spend more than 3.5mBTC.  If instead we choose the best-fit channel (2mBTC) we can spend 5mBTC in the future.

Note that if we expose `find_route` more directly, we can also do things like support transferring funds between our own channels, as we would be able to query a route between the corresponding peers, then just extend the route as necessary to go to ourself and come from ourself.

**Comment by rustyrussell** [comment] 2018-02-14 04:38
I think this is a sub-case of #863 really.

**Comment by ZmnSCPxj** [comment] 2018-02-14 05:06
@rustyrussell maybe closer to #611?

**Comment by cdecker** [comment] 2018-02-14 15:25
Yep, @ZmnSCPxj's suggestion is closer, closing as a duplicate.

Duplicate of #611

**Closed by cdecker** 2018-02-14 15:25 UTC
Labels: duplicate
