### ISSUE TITLE
'withdraw all' fails when 'utxos' specified; leaves UTxOs unavailable

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#3591] opened 2020-03-14 11:52 UTC
### Issue and Steps to Reproduce
```
$ newaddr=$(lightning-cli newaddr | jq -r .bech32)

$ lightning-cli withdraw "${newaddr}" all 3333perkb 0 '["(my txid):(vout)"]'
{
   "code": 301,
   "message": "Cannot afford transaction with 138sat sats of fees"
}
```
Attempting the same withdrawal a second time yields:
```
{
   "code": -32602,
   "message": "No matching utxo was found from the wallet. You can get a list of the wallet utxos with the `listfunds` RPC call."
}
```
Indeed, the specified `<txid>:<vout>` is no longer returned in `lightning-cli listfunds`. The UTxO does appear again after a `dev-rescan-outputs`, but obviously this is risky and shouldn't be needed.

So there are really **two problems** here:
1. C-Lightning should not be marking UTxOs as spent if it didn't actually spend them.
1. C-Lightning apparently doesn't understand how to spend `all` of a specified set of UTxOs while deducting enough from their total value to satisfy the specified fee rate.

### `getinfo` output
```
$ lightning-cli getinfo | jq '{binding, version, blockheight, network, "lightning-dir"}'
{
  "binding": [
    {
      "type": "ipv6",
      "address": "::",
      "port": 9735
    },
    {
      "type": "ipv4",
      "address": "0.0.0.0",
      "port": 9735
    }
  ],
  "version": "0.8.1",
  "blockheight": 621608,
  "network": "bitcoin",
  "lightning-dir": "/var/lib/lightning/bitcoin"
}
```

**Comment by whitslack** [comment] 2020-03-15 01:16
Problem \#1 also occurs when attempting to `fundchannel` with a specified UTxO but the channel funding fails because the auto-connection to the target node failed. Specifically, C-Lightning keeps the UTxO reserved, even though no attempt was actually made to spend it.

**Comment by darosior** [comment] 2020-03-15 18:29
I experienced it too with `fundchannel`. And even funnier things happen when you try to `fundchannel_cancel` the peer.. Giving a look to withdraw now.

**Comment by whitslack** [comment] 2020-03-15 22:29
> You should not specify `all`, but we shouldn't crash.

@darosior: Okay, then what is the recommended way to withdraw (or fund a channel with) exactly a set of UTxOs without producing a change output? The `all` keyword seems like the most logical choice to me. I expect it to take all coins available in the specified set of UTxOs and send them, minus a specified mining fee.

**Comment by darosior** [comment] 2020-03-15 22:36
Hmm `all` specifies to spend `all` the available funds from the wallet.
But you are right that it would be nice to be able to condition it to the specified utxos..

**Comment by whitslack** [comment] 2020-03-15 23:12
> to answer the question clearly, you should set the amount explicitly if you provide a list of utxos.

But I don't know what the fee will be. If I specify the whole sum of the UTxOs, then there won't be anything left for the fee, and if I specify too little a sum, then I'll inadvertently generate a change output, which is what I'm trying to avoid.

**Comment by darosior** [comment] 2020-03-15 23:45
Yes, that's the well-known problem of fees computation, that's why it's better automated :-)
Though note that we won't create a dust output, which leaves some room for approximation.

**Comment by darosior** [comment] 2020-03-16 00:16
@whitslack ok I tried to reproduce and I think I understood the root cause : were you using unconfirmed utxos ?

**Comment by whitslack** [comment] 2020-03-16 00:23
> were you using unconfirmed utxos ?

@darosior: No. I was specifying exactly one confirmed UTxO, and I was specifying an explicit feerate using the `perkb` suffix. I have some tiny, confirmed UTxOs that I am willing to try withdrawing from my C-Lightning wallet if you'd like me to do any tests. Everytime I've tried before, using the `all` keyword, I get the `Cannot afford transaction with ___sat sats of fees` error. (Side note: That error message says "sat" twice.)

**Comment by darosior** [comment] 2020-03-16 00:41
Weird.. Then I cannot reproduce on current master. Cf  #3593 for the unconfirmed case..

**Comment by whitslack** [comment] 2020-03-16 12:25
Maybe it's already been fixed since the 0.8.1 release. I'll retest after the next release and update here with my findings.

**Comment by niftynei** [comment] 2020-04-07 19:52
@whitslack has this been fixed?

**Comment by whitslack** [comment] 2020-04-07 20:10
@niftynei: I don't know. There hasn't been a new release since 0.8.1. I'll update this issue again after there's been a new release and I've retested.

**Comment by niftynei** [comment] 2020-04-08 00:27
Oh I see, apologies I didn't quite grok that you were waiting til the next release to test :)

**Comment by ZmnSCPxj** [comment] 2020-06-09 10:59
We already handle this correctly, as these tests show, and these tests are in released 0.8.2.1:

https://github.com/ElementsProject/lightning/blob/7a7b15412d79e9a628fa25c49e100315784eef45/tests/test_wallet.py#L172

https://github.com/ElementsProject/lightning/blob/7a7b15412d79e9a628fa25c49e100315784eef45/tests/test_connection.py#L876

@whitslack please confirm if ok to close.

**Comment by whitslack** [comment] 2020-06-09 17:35
I just tested this again on 0.8.2.1 and got a different failure:

```
{
   "code": -1,
   "message": "Error broadcasting transaction: error code: -26\\nerror message:\\nmin relay fee not met, 109 < 110 (code 66). Unsent tx discarded"
}
```

I was withdrawing with `feerate=1000perkb`, which should be the minimum-allowed fee rate. Indeed, `bitcoin-cli getmempoolinfo` reports:

```
{
  "loaded": true,
  "size": 15097,
  "bytes": 9207924,
  "usage": 32831760,
  "maxmempool": 64000000,
  "mempoolminfee": 0.00001000,
  "minrelaytxfee": 0.00001000
}
```

So it looks like there's somewhere that C-Lightning is rounding down where it ought to be rounding up.

On the plus side, the UTxO that I tried to spend is still listed in `listfunds` after the failure.

**Comment by darosior** [comment] 2020-06-09 17:38
FWIW, you can use 253perkw for the moment.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by whitslack** [comment] 2020-06-09 17:40
> 253perkw

That worked. And my withdraw spent only the UTxO that I asked it to, and it spent the whole thing without creating a change output. :+1:

**Comment by darosior** [comment] 2020-06-09 17:43
I'll give the rounding error a look (greping logs on my nodes currently to check it doesn't happen on other code path.. Which might be worrying).

**Comment by ZmnSCPxj** [comment] 2020-06-10 07:17
1000perkb == 250perkw.  It may have to do with us rounding down consistently as in C, and Bitcoin rounding up consistently because they have magic C++ code to do that or something (or maybe they just consistently round up from sheer code review).  In practice we should probably use 253perkw as a minimum and also check that perkb units are greater than 253perkw when converted.

**Comment by ZmnSCPxj** [comment] 2020-06-16 05:39
Filed #3771, closing this.

**Closed by ZmnSCPxj** 2020-06-16 05:39 UTC
