### ISSUE TITLE
Segfault in wallet_payment_add in response to revocation

### ISSUE THREAD

**Issue by nothingmuch** [ElementsProject/lightning#827] opened 2018-01-28 19:47 UTC
I attempted to send a payment on mainnet, initially the RPC client of the initial `pay` hung and the payment status was "pending" when calling `listpayments`. I stopped lightningd via the RPC, and restarted it, and upon issuing `getroute` with the same parameters, it segfaulted. I believe the `getroute` call was not related, as upon a restart it happened again, with a similar backtrace, this time without any actions on my part.

Backtrace:

```
+32.519438230 lightningd(26573):BROKEN: backtrace: lightningd/log.c:436 (log_crash) 0x4105bb
+32.523643271 lightningd(26573):BROKEN: backtrace: (null):0 ((null)) 0x76c9f7e6c0df
+32.524100135 lightningd(26573):BROKEN: backtrace: wallet/wallet.c:1388 (wallet_payment_add) 0x44dae6
+32.525332793 lightningd(26573):BROKEN: backtrace: lightningd/peer_htlcs.c:874 (update_out_htlc) 0x41fdc8
+32.525374000 lightningd(26573):BROKEN: backtrace: lightningd/peer_htlcs.c:899 (changed_htlc) 0x41fe9b
+32.525419916 lightningd(26573):BROKEN: backtrace: lightningd/peer_htlcs.c:1189 (peer_got_revoke) 0x420dcb
+32.526072263 lightningd(26573):BROKEN: backtrace: lightningd/peer_control.c:1902 (channel_msg) 0x41ab26
+32.526652050 lightningd(26573):BROKEN: backtrace: lightningd/subd.c:476 (sd_msg_read) 0x422cc0
+32.526836233 lightningd(26573):BROKEN: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x45614e
+32.526856550 lightningd(26573):BROKEN: backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x456c23
+32.526856550 lightningd(26573):BROKEN: backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x456c61
+32.526960186 lightningd(26573):BROKEN: backtrace: ccan/ccan/io/poll.c:305 (io_loop) 0x458507
+32.527146285 lightningd(26573):BROKEN: backtrace: lightningd/lightningd.c:350 (main) 0x40f012
+32.527157816 lightningd(26573):BROKEN: backtrace: (null):0 ((null)) 0x76c9f7e58b44
+32.527165417 lightningd(26573):BROKEN: backtrace: (null):0 ((null)) 0x4030d8
+32.527174581 lightningd(26573):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```

Preceding events from crash.log (since this is on mainnet I do not want to attach the full log):

```
+32.483015679 lightning_channeld(26634):DEBUG: TRACE: HTLC 11[LOCAL] => RCVD_ADD_REVOCATION
+32.483056983 lightning_channeld(26628):DEBUG: TRACE: Read decrypt [bit vomit]
+32.483152760 lightning_gossipd(26585):DEBUG: TRACE: Received channel_update for channel 505809:262:1(1)
+32.483181549 lightning_channeld(26624):DEBUG: TRACE: peer_in WIRE_CHANNEL_UPDATE
+32.483209451 lightning_channeld(26627):DEBUG: TRACE: peer_in WIRE_CHANNEL_UPDATE
+32.483234772 lightning_channeld(26631):DEBUG: TRACE: Read decrypt [bit vomit]
+32.483264145 lightning_channeld(26639):DEBUG: TRACE: peer_in WIRE_CHANNEL_UPDATE
+32.483306154 lightning_channeld(26634):DEBUG: TRACE: Sending master 1022
+32.483334318 lightning_channeld(26628):DEBUG: TRACE: peer_in WIRE_CHANNEL_ANNOUNCEMENT
+32.483368982 lightning_gossipd(26585):DEBUG: TRACE: Replacing existing update
+32.483435033 lightning_channeld(26624):DEBUG: TRACE: Read decrypt [bit vomit]
+32.483473833 lightning_channeld(26627):DEBUG: TRACE: Read decrypt [bit vomit]
+32.483506329 lightning_channeld(26631):DEBUG: TRACE: peer_in WIRE_CHANNEL_UPDATE
+32.483534215 lightning_channeld(26639):DEBUG: TRACE: Read decrypt [bit vomit]
+32.483583365 lightning_channeld(26634):DEBUG: UPDATE WIRE_CHANNEL_GOT_REVOKE
+32.483627980 lightningd(26573):DEBUG: peer [bit vomit]: got revoke 167: 1 changed
+32.483654430 lightningd(26573):BROKEN: FATAL SIGNAL 11 RECEIVED
```

The redacted peer was not the destination node, but a routing peer.

**Comment by nothingmuch** [comment] 2018-01-28 20:07
I forgot to specify this was on e91a8df, but on af26c91 it appears the crash is no longer occurring.

**Comment by cdecker** [comment] 2018-01-28 21:31
The payment system has been revamped some days ago, to avoid storing payments that are not committed yet. The issue you report is likely an uninitialized value for `id` in `struct wallet_payment`. I checked and there should be no code path that leads there without resetting the `id` anymore.

Closing, since it can no longer be reproduced.

**Closed by cdecker** 2018-01-28 21:31 UTC
