### ISSUE TITLE
CHANNELD_AWAITING_LOCKIN:We've confirmed funding, they haven't yet.

### ISSUE THREAD

**Issue by dumm98** [ElementsProject/lightning#1331] opened 2018-04-05 21:11 UTC
i've opened a channel but after 20+ blocks im still getting CHANNELD_AWAITING_LOCKIN
i am connected and synced.

is there anything i can do? or it's a problem on the other side?
### `getinfo` output

{ "id" : "03a8f92735a6e7aac231ec46d51f0b9e84aeed6ce8abd76431849b4e76e9745bfb", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "88.99.164.229", "port" : 9735 },
                { "type" : "ipv6", "address" : "2a01:4f8:10a:3524::2", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2473-g1a55147", "blockheight" : 516810, "network" : "bitcoin" }

### `listpeers` output
```
{ "peers" :
        [
                { "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : true, "netaddr" :
                        [ "104.198.32.198:9735" ], "alias" : "SLEEPYARK-6-11-21-2360-g044705a5", "color" : "02f672", "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "short_channel_id" : "516778:1569:1", "channel_id" : "e52f963dec9b31aa28ca3c45337b290a5984ec8825e7ba1f736b5b1fd0322f11", "funding_txid" : "102f32d01f5b6b731fbae72588ec84590a297b33453cca28aa319bec3d962fe5", "msatoshi_to_us" : 4999000000, "msatoshi_total" : 4999000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "their_to_self_delay" : 144, "our_to_self_delay" : 144, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_AWAITING_LOCKIN:We've confirmed funding, they haven't yet." ], "in_payments_offered" : 0, "in_msatoshi_offered" : 0, "in_payments_fulfilled" : 0, "in_msatoshi_fulfilled" : 0, "out_payments_offered" : 0, "out_msatoshi_offered" : 0, "out_payments_fulfilled" : 0, "out_msatoshi_fulfilled" : 0 } ] },
                { "state" : "GOSSIPING", "id" : "0327049d8d63f0c40193cdf3afc61817c8647808a4e482de0716fcef74e6d92ebf", "alias" : "FederalReserve", "color" : "42f45d", "netaddr" :
                        [ "35.184.46.254:9735" ], "connected" : true, "owner" : "lightning_gossipd" },
                { "state" : "GOSSIPING", "id" : "024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed", "alias" : "Bitrefill", "color" : "3399ff", "netaddr" :
                        [ "52.16.240.222:9735" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
```

**Comment by cdecker** [comment] 2018-04-05 22:00
Yep, sleepyark is having a hard time catching up with the blockchain currently. Workin on this.

This is a duplicate of #1179

**Closed** 2018-04-25 12:33 UTC
Labels: duplicate
