### ISSUE TITLE
lightningd froze

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1039] opened 2018-02-19 12:23 UTC
### Issue and Steps to Reproduce

lightningd froze, 100% cpu:

```
24227 ulmo      20   0   20576  12548   1984 R  99.3  0.0  16:10.59 lightning_gossi                      
```

Nothing in log since two days ago:

```
2018-02-17T04:13:38.927Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_out WIRE_CHANNEL_UPDATE
2018-02-17T04:13:39.113Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_in WIRE_CHANNEL_UPDATE
2018-02-17T04:13:39.113Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_in WIRE_CHANNEL_UPDATE
2018-02-17T04:13:39.113Z lightning_gossipd(24227): Received channel_update for channel 508690:1415:0(0) now ACTIVE
2018-02-17T04:13:39.113Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_in WIRE_CHANNEL_UPDATE
2018-02-17T04:13:39.113Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_in WIRE_CHANNEL_UPDATE
2018-02-17T04:13:39.113Z lightning_gossipd(24227): Received channel_update for channel 506083:919:0(1) now ACTIVE
2018-02-17T04:13:46.796Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: peer_in WIRE_FUNDING_LOCKED
2018-02-17T04:13:46.796Z lightningd(24200): lightning_channeld-0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: UPDATE WIRE_CHANNEL_GOT_FUNDING_LOCKED
2018-02-17T04:13:46.796Z lightningd(24200): 0351daec0b59bc39f0180fefd40c516ff4a3366711e955469747d6ec743f3e07ac chan #99: Got funding_locked
```

### `getinfo` output

frozen process; no info available.  Process started Feb16, so the version was from on or before Feb16.

**Comment by cdecker** [comment] 2018-02-19 12:28
Strange, can you try to get a core-dump with `gcore [pid]`?

**Comment by Ulmo** [comment] 2018-02-19 12:59
Sorry that I didn't see that message first before restarting.  Next time, I will try that.

**Comment by cdecker** [comment] 2018-02-20 21:00
No problem @Ulmo, I'll close this issue for now, since we can't reproduce it right now. Please ping me if it happens again :wink:

**Closed by cdecker** 2018-02-20 21:00 UTC
