### ISSUE TITLE
Channel opening issue when experimental-dual-fund enabled and only initiating peer puts funding into the channel

### ISSUE THREAD

**Issue by devastgh** [ElementsProject/lightning#5255] opened 2022-05-13 07:07 UTC
### Issue and Steps to Reproduce
Situation: My cln version: 0.11 . Both me, and my peer had experimental dual fund enabled. My peer opened a channel to me, that was not a dual-funded channel, only he put funding into it. I had no liquidity ads present. listpeers for that peer had 2 parts in it for me: one owner:dualopend and one owner:channeld. Once the channel got established onchain, it started working properly, owner:channeld status was established, announced, the channel is working fine. However, owner:dualopend did not disappear and was stuck in init, for 1-2 weeks. After a node restart, owner:dualopend part disappeared, however my log is now full with `Unknown channel 5fa36123c25df987af2282ee39384d8ef0f468f270c569fa596e55b1c6d37ddc for WIRE_CHANNEL_REESTABLISH` . 

Relevant part of my logs:
when the channel was established, everything looking fine:
```
2022-04-27T08:10:41.616Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1976: State changed from DUALOPEND_OPEN_INIT to DUALOPEND_AWAITING_LOCKIN
2022-04-27T08:43:33.119Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1976: State changed from DUALOPEND_AWAITING_LOCKIN to CHANNELD_NORMAL
```
After that i started getting this in the log:

```
2022-04-27T08:55:22.718Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (62208)
2022-04-27T11:55:39.117Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (62208)
2022-04-27T12:06:11.160Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (62208)
2022-04-27T14:13:47.120Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (62208)
2022-04-27T14:17:50.851Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (62208)
2022-04-28T04:44:40.734Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (9)
2022-04-29T20:07:52.586Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (9)
2022-04-30T04:06:01.941Z INFO    xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#1974: Peer transient failure in DUALOPEND_OPEN_INIT: dualopend: Owning subdaemon dualopend died (9)
```
In cln getinfo my num_active channels was the correct number (the channel for this peer was counted here), however i had one num_pending_channel, i guess this was the owner:dualopend part that was stuck in init. Ride the lightning showed that the channel was stuck in dual open initialized. The owner:dualopend that was stuck had an unique channel id, different than the owner:channeld.
After a restart it's trying to reestablish the channel id, that was in the owner:channeld part, that was never online, every minute or so:

`2022-05-13T07:06:30.585Z UNUSUAL xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-lightningd: Unknown channel 5fa36123c25df987af2282ee39384d8ef0f468f270c569fa596e55b1c6d37ddc for WIRE_CHANNEL_REESTABLISH`

After consulting with niftynei i'm opening this issue.
I can not provide the old listpeers output that had owner:dualopend, since it's not there anymore.
Just my guess is: cln expected me to put funding into the channel, and it was waiting for an onchain transaction. If i remember correctly, i had a funding txid in owner:dualopend, that was actually never done, since i did not put any funding into the channel.

**Comment by heyambob** [comment] 2022-05-25 10:09
Turns out the limbo channel prevent my node to connect to his. When I connected, the connect command never returned and I got this in my log,

```
2022-05-25T09:20:32.298Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: Connected out, starting crypto
2022-05-25T09:20:32.907Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: Connect OUT
2022-05-25T09:20:32.907Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_out WIRE_INIT
2022-05-25T09:20:33.529Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_in WIRE_INIT
2022-05-25T09:20:33.529Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-gossipd: seeker: disabling gossip
2022-05-25T09:20:33.530Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-chan#22180: Peer has reconnected, state AWAITING_UNILATERAL: telling connectd to make active
2022-05-25T09:20:33.530Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: Handed peer, entering loop
2022-05-25T09:20:33.531Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_out WIRE_GOSSIP_TIMESTAMP_FILTER
2022-05-25T09:20:33.531Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-lightningd: Telling connectd to send error 00115fa36123c25df987af2282ee39384d8ef0f468f270c569fa596e55b1c6d37ddc00194177616974696e6720756e696c61746572616c20636c6f7365
2022-05-25T09:20:33.532Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: destroy_subd: 1 subds, to_peer conn 0x56520b87f008, read_to_die = 0
2022-05-25T09:20:33.532Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_out WIRE_ERROR
2022-05-25T09:20:33.532Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_out WIRE_ERROR
2022-05-25T09:20:33.864Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-connectd: peer_conn_closed
2022-05-25T09:20:33.864Z DEBUG   03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-lightningd: peer_disconnect_done
2022-05-25T09:20:33.865Z DEBUG   plugin-funder: Cleaning up inflights for peer id 03xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

How can I clear this limbo channel out of my db ? I wonder, since I'm unable to connect to him, maybe it's a reason that makes the limbo channel stay on forever.

**Comment by vincenzopalazzo** [comment] 2023-06-20 20:57
Looks like that this problem is no longer reproducible https://github.com/ElementsProject/lightning/issues/6255

So I am closing this and feel free to reopen it if this happens on new releases

**Closed by vincenzopalazzo** 2023-06-20 20:57 UTC
Labels: in diagnostic
