### ISSUE TITLE
What does "sendrawtx exit 25, gave error code: -25 error message: Missing inputs" mean?

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#767] opened 2018-01-25 03:47 UTC
While reading the log, I ran across an undefined error "exit 25".  Here's the log:

[logexcerpt.txt](https://github.com/ElementsProject/lightning/files/1662504/logexcerpt.txt)

**Comment by cdecker** [comment] 2018-01-25 11:17
That's perfectly fine, it just means that the transaction `lightningd` attempted to send, i.e., a close transaction, could not be added since the outputs were already spent (the other side started a unilateral close which triggered all of this in the first place). So `lightningd` is just going through the motions, attempts to doublespend the unilateral closing transaction, and fails, but it'll continue to watch the blockchain, react to future state change and grab its funds from the unilateral close.

**Comment by eightywon** [comment] 2018-01-25 20:26
I'm getting similar, repeated periodically and printed to the console:

`
lightningd(19592): Broadcasting tx 0200000000010156cf4392dc89b6ec28110fabb2e0ea9e924866349257468ba1941f0735bd1e8d010000000032701380016ee50200000000002200203fec729a2d769587e813fc96589d79c6fa0769fff8ac6b60508421ada48bf57a0400473044022044afc33d7e7c99b7eb676e23de656e3c20d425dc088be2892b0806d2b077a457022004fb9054463d27103b3354d5a2ae63ecfa57e96efcaec7f5fd348f533a6aba0a01473044022026dc16dab55b29ec3baaea1b17ac97a9b6f6c2179010c11ecf1f65d15e41c343022068e89387959f56ffdb610fe770c2fa02995742c2796ae0ab0f7d9af55d63460f01475221026b0d1eda41da055250fdaed1c2a6bbea3c4bbd8a3c901475e95e93c0da98efa021029f5ad31eaba8db76934327d499427db46ea33ac13ede4550e0d867f4537b82ff52aefb045c20: 25 error code: -25
error message:
Missing inputs
`

...and I indeed had a peer close the channel which is in _ONCHAIND_THEIR_UNILATERAL_ state:

`                { "id" : "0207481a19a3f51a48f134e95afa67cfeffdb38a99b5ad3494a320c4918aaaf579", "connected" : false, "channels" :
                        [
                                { "state" : "ONCHAIND_THEIR_UNILATERAL", "owner" : "lightning_onchaind", "short_channel_id" : "505925:1687:1", "funding_txid" : "8d1ebd35071f94a18b465792346648929eeae0b2ab0f1128ecb689dc9243cf56", "msatoshi_to_us" : 200000000, "msatoshi_total" : 200000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },
`

I haven't seen the funds returned (listfunds) which sounds like it's as expected. If I'm understanding correctly, we need to wait for the timeout (or whatever the term is) because it was a unilateral close. Once the timeout is met, the transaction will be closed on the blockchain and the funds returned to my node?

Any way (or plans) to let a node agree to a unilateral close to speed the settling process up (noting that I don't fully understand the protocol so this may not even be allowed/possible)? I tried a plain old close hoping to make it mutual but couldn't because of the state of the channel (their unilateral).

Thanks!

**Comment by cdecker** [comment] 2018-01-25 21:31
I would appear that the funds are settled on-chain, and that the other party didn't get any funds out of it hence the settlement has only one output, yours I presume: 1f7cb43168e6c00ed0cf1221901f30d024a102a44080fc546ab056aa3ae72ce7:0. So you don't see any output matching those criteria in the `listfunds` result?

**Comment by eightywon** [comment] 2018-01-25 22:11
I don't believe so, no:

> pi@dev:~/lightning $ lightning-cli listfunds
{ "outputs" :
        [
                { "txid" : "8d1ebd35071f94a18b465792346648929eeae0b2ab0f1128ecb689dc9243cf56", "output" : 0, "value" : 3412 } ] }

I appear to be up to date in terms of the blockchain (not sure if that is relevant here):

> pi@dev:~/lightning $ lightning-cli getinfo
{ "id" : "038d1572c28f4ea9b07557dd59c52d8805a55743c02569e8bb52e42a1daf2baed9", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "IP.GOES.HERE", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1659-gfeb7340", "blockheight" : 506107, "network" : "bitcoin" }


> pi@dev:~/lightning $ bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 506107,
  "headers": 506107,
   ...

The other party not receiving funds would make sense as I opened the channel yesterday and they closed (or at least their node did) unexpectedly.

**Comment by cdecker** [comment] 2018-01-25 22:16
Ok, I might have an idea what happened. Did you restart `lightningd` or were you offline while their_unilateral_close confirmed?

**Comment by eightywon** [comment] 2018-01-25 22:30
Certainly possible that I was offline. There were a few times I restarted lightningd, and a few times it crashed yesterday as well. That is, there were no extended periods when I had it offline.

I'm not entirely sure how to determine when the transaction settled. I looked at the original funding tx (8d1ebd35071f94a18b465792346648929eeae0b2ab0f1128ecb689dc9243cf56) and see the 2mBTC output on blockchain.info, but the couple of block explorers I looked at can't show the address/tx info for that one.

**Comment by cdecker** [comment] 2018-01-25 22:35
So my hunch is that we are not storing the their_unilateral/to_us address in the `txfilter` across restarts, hence we are not triggering when seeing the output after a restart. Is `onchaind` being launched after the restart?

**Comment by eightywon** [comment] 2018-01-25 22:42
Hopefully this is what you're looking for:

> pi@dev:~/lightning $ ps aux | grep onchain
pi        6917  0.0  0.1   4276  1852 pts/1    S+   16:36   0:00 grep --color=auto onchain
pi       22030  0.0  0.1   5496  1552 pts/1    S    Jan24   0:00 /home/pi/lightning/lightningd/lightning_onchaind

... then ran lightnind, and:

```
pi@dev:~/lightning $ lightning-cli getinfo
{ "id" : "0...9", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "IP.GOES.HERE.LOL", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1659-gfeb7340", "blockheight" : 506013, "network" : "bitcoin" }
pi@dev:~/lightning $ ps aux | grep onchain
pi        8111  0.0  0.2   4276  1900 pts/1    S+   16:39   0:00 grep --color=auto onchain
pi@dev:~/lightning $
```

**Comment by cdecker** [comment] 2018-02-22 22:43
@eightywon terribly sorry for not following up on this, what's the current status? Could you try to update to the latest version and try to restart `lightningd` again?

**Closed** 2018-02-27 15:06 UTC
Labels: question
