### ISSUE TITLE
Duplicate channel_announcements cause gossipd to abort

### ISSUE THREAD

**Issue by fixone** [ElementsProject/lightning#1334] opened 2018-04-06 19:08 UTC
lightningd was running fine, but had some problems receiving payments (from and Eclair Wallet) so I did a ```git pull``` + ```make clean && make``` and after compilation lightningd won't start 
```
 lightningd: lightning_gossipd failed (exit status 242), exiting.
```

and log shows
```
2018-04-06T19:03:42.854Z lightningd(415): Adding block 1283896: 00000000000004471e6adcce501a50f780c1a52d6b4ed609cfd599d90e3cb603
2018-04-06T19:03:42.909Z lightning_gossipd(423): req: type WIRE_GOSSIPCTL_INIT len 126
2018-04-06T19:03:42.909Z lightning_gossipd(423): Creating IPv6 listener on port 9735
2018-04-06T19:03:42.909Z lightning_gossipd(423): STATUS_FAIL_INTERNAL_ERROR: Announcement 010083a97a21d92b7f4077b1bb1396e5c634f33127a6d4f6b392c0abf992565500f428f1a4b361c51e89cfacc8238f28d6c803b047d61669695181c106b11b6189f763af1927e17f475eadf5ae486244eb79eab05004f6b0da5ae288451c6445ca7602b23fc1a1c4ff26fe2b0437660d0668a2b172bb073a215bbee73600a9448847248cadc07b3799b097f2de43ce441d04954f65e18b7fd2e28c8d5e414b65725f5c87efa73a9e63fbece02b14e0b227a63b5c2edd2e37b0df8aa2210540126e5c973f043622c3817e80205d01b31d0bb3ecf605d77935a426d87264e2ee5ce8b56708299e74fe7ffb46cf0a4c1bfb501d15494290f167211403be928b1e3f1ad0000043497fd7f826957108f4a30fd9cec3aeba79972084e90ead01ea33090000000013a8de0000070000038f80b541c3a9c1bbd54b4b15a379db83221e3fb50d5ffc543cef6d62a7f7163103eca120d4d74b1d0cdbb4c8c66d36aceba0ed5a21c404cf672379f7bd43c61e460317fe38cfbbae93ee25f3b4d4bf3c00bc95a7632051ea2e9fbe611314712223180369bb6d303fb4c06379d6a2afd8b974f60404a4375936f59a1826eb6486c5a934 was replaced?
```

**Comment by fixone** [comment] 2018-04-07 06:03
i've gone back commit by commit and recompiled each version up to ```daa14f48``` , the daemon won't start so it's probably not related to the version (unless the first run with ```249b1a``` somehow corrupted the store)

**Comment by cdecker** [comment] 2018-04-07 10:25
That appears to have originated from the `gossip_store` file, yes. I have been trying to hunt down the cause for this occasional failure, but with the gossip-persistence this might now be a really annoying error. Not making the error fatal results in null-pointers later in the execution, which is really strange, it seems it would also cause us to accept a `channel_update` without matching `channel_announcement`.

It's proving hard to debug since this is a rather rare event, and I'm afraid that checking the `gossip_store` for duplicates won't help much either since that doesn't tell us how we came to accept two `channel_announcement`s in the first place. My best guess is that we have a timing issue when calling out to check for funding `txout`s.

**Comment by ZmnSCPxj** [comment] 2018-04-07 14:37
If you need to get your node started up soonest, removing the `gossip_store` should work.

I am uncertain if investigating your `gossip_store` file will help @cdecker debug it, we should wait for him to ask, for now please retain a copy of it elsewhere.

**Comment by Ulmo** [comment] 2018-04-07 15:07
Apparently my crash report #1341 is a duplicate of this.  Here, he called it duplicate, but I called it by the name of the crash error:   "Announcement ... was replaced?".  That's why I didn't see it in the list of reports.  Sorry.

**Comment by fixone** [comment] 2018-04-12 18:57
I still have the gossip_store since the crash time, replacing the current one will do? In the meantime there were some channels opened and others closed, will this have any impact if swapping the store?

**Comment by fixone** [comment] 2018-04-13 09:44
I updated to the latest version ```f27cd3e4``` , replaced the gossip_store with the one at the moment of the crash and indeed lightningd started without any hiccups

**Comment by cdecker** [comment] 2018-04-13 14:34
Perfect, thank you very much @fixone for testing this :+1:

**Closed by cdecker** 2018-04-13 14:34 UTC
Labels: gossip, pending-fix-confirmation
