### ISSUE TITLE
'channel ALL: internal error' when reconnecting to node

### ISSUE THREAD

**Issue by hkjn** [ElementsProject/lightning#1018] opened 2018-02-16 16:47 UTC
### Issue and Steps to Reproduce

Running two c-lightning nodes, node A (`02640[..]`) built at https://github.com/ElementsProject/lightning/commit/d5effc and node B (`02d2ea[..]`) built at https://github.com/ElementsProject/lightning/commit/e97ee3.

I connected node B to node A (status `GOSSIPING`), then did `fundchannel` to open a channel from A to B. Status was now `CHANNELD_AWAITING_LOCKIN`, as expected.

At this point I restarted node B, then noticed it was `connected: false` for B in node A's `listpeers` output and attempted to reconnect, which failed with `channel ALL: Internal error`:

```
$ lightning-cli connect 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb
18a9ec0084 ::ffff:174.138.11.8
{ "code" : -1, "message" : "channel ALL: Internal error" }
```

Node A's logs show the following:
```
lightningd(5400): Connected json input
lightning_gossipd(5408): req: type WIRE_GOSSIPCTL_PEER_ADDRHINT len 54
lightning_gossipd(5408): req: type WIRE_GOSSIPCTL_REACH_PEER len 35
lightning_gossipd(5408): Connected out for 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084
lightning_gossipd(5408): Initiator: Act 1
lightning_gossipd(5408): Initiator: Act 2
lightning_gossipd(5408): Initiator: Act 3
lightning_gossipd(5408): peer_out WIRE_INIT
lightning_gossipd(5408): peer_in WIRE_INIT
lightning_gossipd(5408): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightning_gossipd(5408): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightningd(5400): peer 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084: Peer has reconnected, state CHANNELD_AWAITING_LOCKIN
lightningd(5400):jcon fd 14: Failing: channel ALL: Internal error
lightning_gossipd(5408): req: type WIRE_GOSSIPCTL_HAND_BACK_PEER len 239 
lightning_gossipd(5408): hand_back_peer 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084: now local again
lightning_gossipd(5408): peer_out WIRE_ERROR 
lightning_gossipd(5408): 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084: we sent them a fatal error, closing
```

This seems to be reproducible, and at the same time shows following in debug logs on node B:
```
lightning_gossipd(13): Responder: Act 1
lightning_gossipd(13): Responder: Act 2
lightning_gossipd(13): Responder: Act 3
lightning_gossipd(13): peer_out WIRE_INIT
lightning_gossipd(13): peer_in WIRE_INIT
lightning_gossipd(13): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightning_gossipd(13): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightningd(5): peer 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510: Peer has reconnected, state CHANNELD_AWAITING_LOCKIN
lightning_gossipd(13): req: type WIRE_GOSSIPCTL_HAND_BACK_PEER len 287
lightning_gossipd(13): hand_back_peer 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510: now local again
lightning_gossipd(13): peer_out WIRE_ERROR
lightning_gossipd(13): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510: we sent them a fatal error, closing
```

Both nodes still show their counterpart as in `CHANNELD_AWAITING_LOCKIN`. 

### `getinfo` output

Node A:
```
$ lightning-cli getinfo
{ "id" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "163.172.162.18", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1908-gd5effcb9", "blockheight" : 509474, "network" : "bitcoin" }
```

Node B:
```                                    
$ lightning-cli getinfo
{ "id" : "02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084", "port" : 9735, "address" :                                                                                                    
        [                                          
                { "type" : "ipv6", "address" : "::ffff:174.138.11.8", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1937-ge97ee3d1", "blockheight" : 509474, "network" : "bitcoin" }
```

**Comment by hkjn** [comment] 2018-02-16 17:25
Fwiw, I tried bringing node B up to version https://github.com/ElementsProject/lightning/commit/e48a97, after which the issue persisted, although the error message became (incorrectly?) lengthier:
```
$ $ lightning-cli connect 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 163.172.162.18
{ "code" : -1, "message" : "channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: Internal error" }
```

**Comment by ZmnSCPxj** [comment] 2018-02-17 07:13
First off, node B encountered an error for its channel. It propagated the error to node A.  The "channel ALL:" on log of A means that it got an error on all channels from B.  The proper response, would be to close the channel unilaterally on both sides (whoever moves first, does the unilateral close).  The question is two-fold: what error did node B encounter that made it to send that error to A, and, why are they not performing a unilateral close?

(maybe the funding tx was never properly broadcast?)

C-lightning always reports errors as "channel ALL" --- arguably we should be reporting the specific channel, but we only support one channel per peer anyway. So if both sides handle things correctly, then, it should be OK to always report errors as "channel ALL".  For c-lightning, this channel ALL is simply "the channel I have with this peer".

**Comment by ZmnSCPxj** [comment] 2018-02-17 09:33
An "Internal  error" being reported by node B should show some log print at the BROKEN level, which should get printed at almost all levels.

On B, could you try `lightning-cli getlog`?

**Comment by hkjn** [comment] 2018-02-17 12:57
Thanks @ZmnSCPxj.

I was also surprised not to see any more logging about the brokenness from node B; `lightning-cli getlog | grep -i BROKEN` comes up clean.

Full `getlog` output from node B is available (temporarily) at [http://[::ffff:ae8a:b08]:8080/nodeb.log](http://[::ffff:ae8a:b08]:8080/nodeb.log).

The only bits that seem relevant to me are:
```
469 }, 
		{ "type" : "UNUSUAL", "time" : "510.609296675", "source" : "lightningd(1):", "log" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: Peer permanent failure in CHANNELD_AWAITING_LOCKIN: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: Internal error (tx 8ca8aa90e5f6cdd5cb692f27377174b3fc5837c084c686e27b515250f3d3382a)" }, 
```

**Comment by ZmnSCPxj** [comment] 2018-02-18 00:12
Hmm, it seems there are more issues than are easily visible at the surface level.

One of the reactions to an `error` is to actually also send an `error` to the peer ourselves. And it seems possible that what happens here is that B first send an `error` message to A, then A reflected it back to B, then B reflected it back to A.

The other seems to be that the transaction to establish the channel is not getting broadcasted.

**Comment by ZmnSCPxj** [comment] 2018-02-18 05:15
Okay, the root of the problem is that the channel funding transaction `8ca8aa90e5f6cdd5cb692f27377174b3fc5837c084c686e27b515250f3d3382a`is spending a transaction `c6d6b02093a54a59588a27b6e65ae4705987a0c9fbfde510b7172972daedce1a` that I cannot find in either testnet or mainnet.

Then one of the nodes fail because it cannot succeed to broadcast that transaction.  It sends the `error` message to the other, which receives it.  Once receiving it, it also sends an `error`. They pingpong this back and forth, with the error message becoming lengthier each time as each one prepends "`channel ALL: lightning_channeld received: ERROR `"

**Comment by ZmnSCPxj** [comment] 2018-02-18 06:26
Here is the code that handles received `error` message: https://github.com/ElementsProject/lightning/blob/e48a97ffd43977282450a0f3892c9a15c89d735a/lightningd/subd.c#L390-L407

it calls the function `channel_fail_permanent`.  This contains the code: https://github.com/ElementsProject/lightning/blob/e48a97ffd43977282450a0f3892c9a15c89d735a/lightningd/channel.c#L207-L217

Meaning this pingpong should not happen anymore if both are at latest.

You mentioned node A is at d5effcb96167c90fc681d0eace6b5bba00b94102, and did not mention upgrading it.  In that revision, `channel_fail_permanent` is still named `peer_fail_permanent`, but still contains similar code: https://github.com/ElementsProject/lightning/blob/d5effcb96167c90fc681d0eace6b5bba00b94102/lightningd/peer_control.c#L206-L216

So I am unsure why there is a pingpong happening.  I expect at most B will error, then A will error in response, and B will report the error in the log but will not reflect it back to A again...

**Comment by hkjn** [comment] 2018-02-19 14:42
Thanks for looking into this, @ZmnSCPxj.

Agreed that the funding tx for the channel `c6d6b02093a54a59588a27b6e65ae4705987a0c9fbfde510b7172972daedce1a` does not seem to have been broadcast, or at least it hasn't been mined into a block..

So trying to summarize (for my own benefit too):

1. Channel opening tx was failed to be broadcast or mined for unknown reason
2. Channel should now be failed unilaterally by whichever node first notices the issue, but for unknown reason instead remains in `CHANNELD_AWAITING_LOCKIN`
3. Error reporting when trying to connect seems to recursively ping-pong between nodes for unknown reason

How can we move forward to address these issues? Should I try to `close` or `dev-fail` the channel, or do you want me to keep it in this state and try to get better debug info?

**Comment by ZmnSCPxj** [comment] 2018-02-19 23:32
You could send the database file to me, or to @cdecker or @rustyrussell (as I am a randomly generated Internet person, you might not want to trust me...).

Database files contain records of how much you moved, but not any private keys.  So it is a privacy leak to send the db file, but I will not be able to steal your money.

I want to see the db file since I want to see the contents of the `outputs` table --- this contains the UTXOs that c-lightning thinks you own.  Unfortunately `listfunds` only lists the `outputs` entries that are marked unspent --- if it uses a UTXO to build your funding transaction, then, it will no longer be listed there, and it is very likely to be that.

Is this mainnet or testnet?  Have you received funds that were marked RBF and then were replaced out?  @cdecker is more knowledgeable of UTXO tracking here, though.

**Comment by rustyrussell** [comment] 2018-02-20 06:30
Obviously internal errors should not happen: the most likely culprit here is (since we can't find the tx) that somehow broadcast failed: I'd expect that was the internal error.  As this should not happen, we don't ever get out of this state :(

I'd be really curious to know why: does your node think it owns funds that it doesn't?  Did you switch between mainnet and testnet?  What does 'dev-rescan-outputs' give?

**Comment by hkjn** [comment] 2018-02-20 11:45
@ZmnSCPxj: I'm fine sharing the full `lightningd.sqlite3` file or any results of specific queries. (I expect no privacy while I'm learning about LN, I am after all running a publicly accessible monitoring tool showing all state for what I call "node A" here at https://ln.hkjn.me..)

@rustyrussell: Especially for node A it's always possible it's in a confused state for whatever reason (it's been running the HEAD commit over the last several weeks, seen any number of crashes both related to bugs with c-lightning and otherwise like e.g. OOM). It has not been switched between mainnet and testnet though; always been running against mainnet. Node B controls no outputs, so `dev-rescan-outputs` is a no-op.

Node A did see some outputs change state with `dev-rescan-outputs`, both from `output_state_spent` to `output_state_available` and vice versa. Full output is available (temporarily) at http://admin2.hkjn.me/fundsdiff.txt. Net result was that about 2x as many satoshi were seen as spendable (as shown by `listfunds`) after the rescan than before.

**Comment by hkjn** [comment] 2018-02-20 13:05
I can't say for sure if it's related, but I noticed another channel on node A in a similar state.

Here too the funding tx doesn't seem to have been broadcast, so c-lightning is of the opinion that we can wait for the tx to get confirmed, which won't happen:

```
$ lightning-cli listpeers | grep -A3 03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1
{ "id" : "03cbf298b068300be33f06c947b9d3f00a0f0e8089da3233f5db37e81d3a596fe1", "connected" : true, "netaddr" :
  [ "[::ffff:45.55.47.17]:50876" ], "channels" :
    [{ "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "a747eef31bf24bdea2ffa3ca65f8e372297b11924ef43a64e5c38c61dd65ae5c", "msatoshi_to_us" : 350000000, "msatoshi_total" : 350000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] },

$ bitcoin-cli getrawtransaction a747eef31bf24bdea2ffa3ca65f8e372297b11924ef43a64e5c38c61dd65ae5c 1
error code: -5
error message:
No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
```

This channel has been in this state for 10+ days.

**Comment by hkjn** [comment] 2018-02-20 13:10
Ah, I had missed some of @ZmnSCPxj's questions:
> Is this mainnet or testnet?

Mainnet.

> Have you received funds that were marked RBF and then were replaced out?

No, none of the funds sent to the c-lightning addresses should have been marked as RBF or double-spent while waiting to be mined.

**Comment by ZmnSCPxj** [comment] 2018-02-20 13:58
Ah, missed that the channel was funded by A to B.  So A is the one trying to broadcast a transaction and failing to do so, which triggers an internal error somehow (I think it should not?).  So we need to look at outputs and `dev-rescan-outputs` on A, not B.

**Comment by hkjn** [comment] 2018-02-20 14:31
@ZmnSCPxj: Yup. B has no funds, so not much to see there. Contents of A's `outputs` table and the results of doing `dev-rescan-outputs` is shown in http://admin2.hkjn.me/fundsdiff.txt as per my earlier reply. (It wasn't clear from your reply if I had made this clear.)

**Comment by ZmnSCPxj** [comment] 2018-02-20 15:07
This line is the `c6d6b02093a54a59588a27b6e65ae4705987a0c9fbfde510b7172972daedce1a` transaction which we cannot find on mainnet.

    1ACEEDDA722917B710E5FDFBC9A0875970E45AE6B6278A58594AA59320B0D6C6        1       298267  our_change      output_status_available

Note that we store the transaction hash in the correct order in-db, but Bitcoin standardly expresses txid in reverse byte order of hash.  So the txid starting with `c6 d6 b0 20 ...` has the in-db hash  ending with `... 20 B0 D6 C6`.

Notice how this line becomes `output_status_spent` after the `dev-rescan-outputs` command.  This is normal: what this command really does is simply to set the output to "spent" if it cannot be found in the UTXO set by bitcoind; this state ("cannot be found in UTXO set") can be either the transaction containing it never confirming and already dropped from mempools (and possibly even double-spent out of the realm of possibility), or the output has been spent.  So even a nonexistent transaction output can be marked "spent" by `dev-rescan-outputs`, rather than deleted.

Looking at `dev-rescan-outputs` log, it seems some outputs that were originally marked spent are now marked unspent.  This suggests to me that the transaction `c6d6b02093a54a59588a27b6e65ae4705987a0c9fbfde510b7172972daedce1a` originally was a transaction that either withdrew money from node A, or created some other channel that is now failed between A and some other node (not necessarily B).  This event (`withdraw` or `fundchannel`) caused an unspent output to be added to the outputs table (the above), which a later `fundchannel` from A to B tried to use.  Unfortunately the parent transaction was not successfully broadcast, and the later transaction for the A to B `fundchannel` had no parent and was not spending anything, leading to our current situation.

**Comment by hkjn** [comment] 2018-02-21 14:48
That all makes sense. So the current theory is that c-lightning state for some outputs had drifted away from the actual state of the UTXO set, after which attempting to open a channel tried to use a non-existing output for the funding tx, which falls into the "shouldn't happen" category and triggered the internal error, and here we are.

Could this situation be made less likely somehow? I.e. doing an extra check with `bitcoind` just before forming the funding tx to verify that all outputs we picked are still in the UTXO set?

I'll bring one or both nodes to a new build after picking up 9842e32 to see if I can get some more telemetry.

**Comment by hkjn** [comment] 2018-02-21 15:29
Running https://github.com/ElementsProject/lightning/commit/3dbace on node B, connecting to node A now seems to succeed:

```
$ lightning-cli connect 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 163.172.162.18                                                                                                    
{ "id" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510" }                       
```

But it still shows the peer as `connected=false`:                                                                                                                                                            
```
$ lightning-cli listpeers
{ "peers" :     
        [               
                { "id" : "0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510", "connected" : false, "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "funding_txid" : "c6d6b02093a54a59588a27b6e65ae4705987a0c9fbfde510b7172972daedce1a", "msatoshi_to_us" : 0, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 144, "max_accepted_htlcs" : 483 } ] } ] }
```

I'm not sure why the `connect` command now would return without errors, unlike the earlier output, which reported the internal error..

Logs show similar error as earlier, but there also seems to be some more info reported (but not due to 9842e32, unless I'm mistaken?):
```
lightningd(1): Connected json input
lightning_gossipd(13): req: type WIRE_GOSSIPCTL_PEER_ADDRHINT len 42
lightning_gossipd(13): req: type WIRE_GOSSIPCTL_REACH_PEER len 35
lightning_gossipd(13): Connected out for 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510
lightning_gossipd(13): Initiator: Act 1
lightning_gossipd(13): Initiator: Act 2
lightning_gossipd(13): Initiator: Act 3
lightning_gossipd(13): peer_out WIRE_INIT
lightning_gossipd(13): peer_in WIRE_INIT
lightning_gossipd(13): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightning_gossipd(13): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: Peer has reconnected, state CHANNELD_AWAITING_LOCKIN
lightningd(1): Client: Received message 1 from client
lightningd(1): Client: Received message 9 from client
lightningd(1): lightning_channeld-0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: pid 1870, msgfd 59
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: Waiting for funding confirmations
lightningd(1):jcon fd 55: Success
lightningd(1): lightning_channeld-0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: init REMOTE: remote_per_commit = 0316635fe0a16d5d78b0b14fce37131f14db1c57504896f23e4aebe211bb5e011c, old_remote_per_commit = 0316635fe0a16d5d78b0b14fce37131f14db1c57504896f23e4aebe211bb5e011c next_idx_local = 1 next_idx_remote = 1 revocations_received = 0 feerates 1250/1250 (range 1250-6300)
lightningd(1): lightning_channeld-0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: peer_out WIRE_CHANNEL_REESTABLISH
lightningd(1): lightning_channeld-0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: peer_in WIRE_ERROR
lightningd(1): 0264089bc3a4afde671b87740d72e03d899b7f0783fbb756786cb7632b2e1db510 chan #1: Peer permanent failure in CHANNELD_AWAITING_LOCKIN: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: Internal error
lightningd(1):          (tx 8ca8aa90e5f6cdd5cb692f27377174b3fc5837c084c686e27b515250f3d3382a)
```

I'll bring node A to the same commit once the armv7l build finishes and check if connecting A->B produces better failure info.

Though unless I'm missing something I think @ZmnSCPxj's theory seems likely, so apart from verifying that 9842e32 produces better telemetry in this case I'm not sure what else to check for this issue, so unless someone disagrees I'll try to `dev-fail` the channel in a few days.

**Comment by hkjn** [comment] 2018-02-22 15:25
With node A on https://github.com/ElementsProject/lightning/commit/3dbace, the message when connecting A->B doesn't seem to include any more info from the fatal error:
```
lightning_gossipd(2710): Connected out for 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084
lightning_gossipd(2710): Initiator: Act 1
lightning_gossipd(2710): Initiator: Act 2
lightning_gossipd(2710): Initiator: Act 3
lightning_gossipd(2710): peer_out WIRE_INIT
lightning_gossipd(2710): peer_in WIRE_INIT
lightning_gossipd(2710): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightning_gossipd(2710): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightningd(2702): 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084 chan #46: Peer has reconnected, state CHANNELD_AWAITING_LOCKIN
lightningd(2702):jcon fd 15: Failing: channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: lightning_channeld: received ERROR channel ALL: Internal error
lightning_gossipd(2710): req: type WIRE_GOSSIPCTL_HAND_BACK_PEER len 527
lightning_gossipd(2710): hand_back_peer 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084: now local again
lightning_gossipd(2710): peer_out WIRE_ERROR
lightning_gossipd(2710): 02d2eabbbacc7c25bbd73b39e65d28237705f7bde76f557e94fb41cb18a9ec0084: we sent them a fatal error, closing
```

I'm doing the default `make` during build (c.f https://github.com/hkjn/src/blob/master/bitcoin/Dockerfile#L48) and not overriding `DEVELOPER=0`, so I'm not sure why the added logging in 9842e32 doesn't seem to take effect..

The ping-ponging behavior that tacks on more `lightningd_channeld: received ERROR channel ALL` messages each connection attempt also seems like something that could be improved.

**Comment by hkjn** [comment] 2018-02-28 13:41
To follow up here, I did `dev-forget-channel` on both nodes to get out of this state, after which I was able to `fundchannel` to establish a channel that did end up in `CHANNELD_NORMAL` and able to route payments.

It sounds like we understand how the nodes ended up in this state (see earlier comments), so feel free to close this issue if you feel like there's nothing more to do here.

**Comment by ZmnSCPxj** [comment] 2018-04-25 03:57
I think the issue has been largely fixed in recent extensive changes in blockchain monitoring, so closing now.

**Closed by ZmnSCPxj** 2018-04-25 03:57 UTC
