### ISSUE TITLE
renepay crash on assert amount_msat_less_eq

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#7363] opened 2024-06-03 12:38 UTC
I'm hitting this assert quite often @Lagrang3 :

```
Jun 03 14:33:56  lightningd: cln-renepay: plugins/renepay/mcf.c:472: linearize_channel: Assertion `amount_msat_less_eq(extra_half->htlc_total, extra_half->known_max)' failed.
Jun 03 14:33:56  lightningd: cln-renepay: FATAL SIGNAL 6 (version v24.05rc2)
Jun 03 14:33:56  lightningd: 0x563575b18ffb send_backtrace
Jun 03 14:33:56  lightningd:         common/daemon.c:33
Jun 03 14:33:56  lightningd: 0x563575b19083 crashdump
Jun 03 14:33:56  lightningd:         common/daemon.c:75
Jun 03 14:33:56  lightningd: 0x7f720560b04f ???
Jun 03 14:33:56  lightningd:         ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
Jun 03 14:33:56  lightningd: 0x7f7205659e2c __pthread_kill_implementation
Jun 03 14:33:56  lightningd:         ./nptl/pthread_kill.c:44
Jun 03 14:33:56  lightningd: 0x7f720560afb1 __GI_raise
Jun 03 14:33:56  lightningd:         ../sysdeps/posix/raise.c:26
Jun 03 14:33:56  lightningd: 0x7f72055f5471 __GI_abort
Jun 03 14:33:56  lightningd:         ./stdlib/abort.c:79
Jun 03 14:33:56  lightningd: 0x7f72055f5394 __assert_fail_base
Jun 03 14:33:56  lightningd:         ./assert/assert.c:92
Jun 03 14:33:56  lightningd: 0x7f7205603eb1 __GI___assert_fail
Jun 03 14:33:56  lightningd:         ./assert/assert.c:101
Jun 03 14:33:56  lightningd: 0x563575af9e69 linearize_channel
Jun 03 14:33:56  lightningd:         plugins/renepay/mcf.c:472
Jun 03 14:33:56  lightningd: 0x563575afa4c9 init_linear_network
Jun 03 14:33:56  lightningd:         plugins/renepay/mcf.c:744
Jun 03 14:33:56  lightningd: 0x563575afb6bf minflow
Jun 03 14:33:56  lightningd:         plugins/renepay/mcf.c:1648
Jun 03 14:33:56  lightningd: 0x563575b002c3 get_routes
Jun 03 14:33:56  lightningd:         plugins/renepay/routebuilder.c:213
Jun 03 14:33:56  lightningd: 0x563575b05181 compute_routes_done
Jun 03 14:33:56  lightningd:         plugins/renepay/mods.c:765
Jun 03 14:33:56  lightningd: 0x563575b0a81f handle_rpc_reply
Jun 03 14:33:56  lightningd:         plugins/libplugin.c:993
Jun 03 14:33:56  lightningd: 0x563575b0a9c3 rpc_read_response_one
Jun 03 14:33:56  lightningd:         plugins/libplugin.c:1183
Jun 03 14:33:56  lightningd: 0x563575b0aa70 rpc_conn_read_response
Jun 03 14:33:56  lightningd:         plugins/libplugin.c:1207
Jun 03 14:33:56  lightningd: 0x563575b36697 next_plan
Jun 03 14:33:56  lightningd:         ccan/ccan/io/io.c:60
Jun 03 14:33:56  lightningd: 0x563575b36b1e do_plan
Jun 03 14:33:56  lightningd:         ccan/ccan/io/io.c:408
Jun 03 14:33:56  lightningd: 0x563575b36bb7 io_ready
Jun 03 14:33:56  lightningd:         ccan/ccan/io/io.c:418
Jun 03 14:33:56  lightningd: 0x563575b3843b io_loop
Jun 03 14:33:56  lightningd:         ccan/ccan/io/poll.c:455
Jun 03 14:33:56  lightningd: 0x563575b0adef plugin_main
Jun 03 14:33:56  lightningd:         plugins/libplugin.c:2209
Jun 03 14:33:56  lightningd: 0x563575af7c3b main
Jun 03 14:33:56  lightningd:         plugins/renepay/main.c:418
Jun 03 14:33:56  lightningd: 0x7f72055f6249 __libc_start_call_main
Jun 03 14:33:56  lightningd:         ../sysdeps/nptl/libc_start_call_main.h:58
Jun 03 14:33:56  lightningd: 0x7f72055f6304 __libc_start_main_impl
Jun 03 14:33:56  lightningd:         ../csu/libc-start.c:360
Jun 03 14:33:56  lightningd: 0x563575af6a50 ???
Jun 03 14:33:56  lightningd:         ???:0
Jun 03 14:33:56  lightningd: 0xffffffffffffffff ???
Jun 03 14:33:56  lightningd:         ???:0
Jun 03 14:33:56  lightningd: cln-renepay: FATAL SIGNAL 11 (version v24.05rc2)
Jun 03 14:33:56  lightningd: 0x563575b18ffb send_backtrace
Jun 03 14:33:56  lightningd:         common/daemon.c:33
Jun 03 14:33:56  lightningd: 0x563575b19083 crashdump
Jun 03 14:33:56  lightningd:         common/daemon.c:75
Jun 03 14:33:56  lightningd: 0x7f720560b04f ???
Jun 03 14:33:56  lightningd:         ./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
Jun 03 14:33:56  lightningd: 0x0 ???
Jun 03 14:33:56  lightningd:         ???:0
Jun 03 14:33:56  lightningd[443803]: INFO    plugin-cln-renepay: Killing plugin: exited during normal operation
```

**Comment by Lagrang3** [comment] 2024-08-07 11:53
Closing this as a duplicate of #7535.

**Closed by Lagrang3** 2024-08-07 11:53 UTC
