### ISSUE TITLE
After restarting lightning errors in logs

### ISSUE THREAD

**Issue by pooleja** [ElementsProject/lightning#794] opened 2018-01-26 19:34 UTC
After restarting, I am seeing the same error repeated over and over in the logs:

```
Jan 26 19:31:34 ip-10-0-2-181 lightningd[338]: lightning_channeld(21175): STATUS_FAIL_PEER_IO: Failed reading reestablish: Success
Jan 26 19:31:34 ip-10-0-2-181 lightningd[338]: lightningd(338): peer 034cb559e7946ad169989d4c05d0420f43703b830c1de03dcae2994760f9a8f2a5: Peer transient failure in CHANNELD_AWAITING_LOCKIN: Owning subdaemon lightning_channeld died (33792)
```

Is there anything I can provide to help debug this?  It is taking a long time to catch back up to the latest block in bitcoind.  

Update: It seems like the sync is halting and it falls behind bitcoind and the only logs are similar to this reporting that the subdaemon died.

**Comment by pandabit** [comment] 2018-01-29 21:26
I'm having the same issue, right now.

**Comment by jb55** [comment] 2018-01-29 21:52
I'm pretty sure this message occurs when channeld loses connection with the peer.

Duplicate of #619

**Closed** 2018-02-06 15:27 UTC
