### ISSUE TITLE
getroute behavior differs without exclude and with empty exclude

### ISSUE THREAD

**Issue by s-tikhomirov** [ElementsProject/lightning#3521] opened 2020-02-14 21:44 UTC
### Issue and Steps to Reproduce

Here are two commands that I expect to produce the same result but they don't (this is testnet):
```
$ lightning-cli getroute -k id=0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d riskfactor=1 maxhops=1 fromid=038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9 exclude='[]' msatoshi=1000
{
   "code": 205,
   "message": "Could not find a route"
}
$ lightning-cli getroute -k id=0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d riskfactor=1 maxhops=1 fromid=038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9 msatoshi=1000
{
   "route": [
      {
         "id": "0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d",
         "channel": "1480431x33x0",
         "direction": 1,
         "msatoshi": 1000,
         "amount_msat": "1000msat",
         "delay": 9,
         "style": "tlv"
      }
   ]
}

```
The nodes in question are [0303ba](https://1ml.com/testnet/node/0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d) and [038863](https://1ml.com/testnet/node/038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9). Note that there are multiple channels between them (e.g. [1414833x248x0](https://1ml.com/testnet/channel/1555625334877454336), [1439990x40x0](https://1ml.com/testnet/channel/1583285748883783680), [1480431x33x0](https://1ml.com/testnet/channel/1627751098622214144)). Here is the full list from my node's point of view:
```
[
   "1297159x151x0",
   "1297159x151x0",
   "1297749x728x0",
   "1297749x728x0",
   "1297846x919x0",
   "1297846x919x0",
   "1297929x8x0",
   "1297929x8x0",
   "1316396x8x0",
   "1316396x8x0",
   "1414744x78x1",
   "1414744x78x1",
   "1415009x73x0",
   "1415009x73x0",
   "1415192x47x1",
   "1415192x47x1",
   "1480206x11x0",
   "1480206x11x0",
   "1570065x147x0",
   "1570065x147x0",
   "1571601x34x0",
   "1571601x34x0"
]
```

### `getinfo` output
```
{
   "id": "026e7cb4237b4042db75a991af29c2d7704780c8e7fbebe5fdbad8f38e958dfba5",
   "alias": "clightningM",
   "color": "026e7c",
   "num_peers": 6,
   "num_pending_channels": 0,
   "num_active_channels": 4,
   "num_inactive_channels": 3,
   "address": [],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9737
      }
   ],
   "version": "v0.8.0-40-g899f5de",
   "blockheight": 1665888,
   "network": "testnet",
   "msatoshi_fees_collected": 0,
   "fees_collected_msat": "0msat",
   "lightning-dir": "/home/sergei/.lightning/testnet"
}
```

**Comment by darosior** [comment] 2020-02-15 14:58
Hi,

I looked into it and could reproduce with a testcase (we need to test all combinations or it would randomly success):
```patch
+    for l in [l1, l2, l3, l4, l5]:
+        for ll in [i for i in [l1, l2, l3, l4, l5] if i != l]:
+            assert (l.rpc.getroute(ll.info['id'], 1, 1, exclude=None) ==
+                    l.rpc.getroute(ll.info['id'], 1, 1, exclude=[]))
+
```
```bash
$ make -j10 && PYTHONPATH=$PYTHONPATH:$PWD/contrib/pyln-testing:$PWD/contrib/pyln-client:$PWD/contrib/pyln-proto VALGRIND=0 pytest tests/ -vvvk test_getroute_exclude -n2

>               assert (l.rpc.getroute(ll.info['id'], 1, 1, exclude=None) ==
                        l.rpc.getroute(ll.info['id'], 1, 1, exclude=[]))
E               AssertionError: assert {'route': [{'amount_msat': 2msat,\n            'channel': '117x1x0',\n            'delay': 15,\n            'direction': 0,\n            'id': '032cf15d1ad9c4a08d26eab1918f732d8ef8fdc6abb9640bf3db174372c491304e',\n            'msatoshi': 2,\n            'style': 'legacy'},\n           {'amount_msat': 1msat,\n            'channel': '119x1x1',\n            'delay': 9,\n            'direction': 0,\n            'id': '0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199',\n            'msatoshi': 1,\n            'style': 'tlv'}]} == {'route': [{'amount_msat': 2msat,\n            'channel': '103x3x1',\n            'delay': 15,\n            'direction': 1,\n            'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59',\n            'msatoshi': 2,\n            'style': 'tlv'},\n           {'amount_msat': 1msat,\n            'channel': '110x1x0',\n            'delay': 9,\n            'direction': 0,\n            'id': '0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199',\n            'msatoshi': 1,\n            'style': 'tlv'}]}
E                 Differing items:
E                 {'route': [{'amount_msat': 2msat, 'channel': '117x1x0', 'delay': 15, 'direction': 0, ...}, {'amount_msat': 1msat, 'channel': '119x1x1', 'delay': 9, 'direction': 0, ...}]} != {'route': [{'amount_msat': 2msat, 'channel': '103x3x1', 'delay': 15, 'direction': 1, ...}, {'amount_msat': 1msat, 'channel': '110x1x0', 'delay': 9, 'direction': 0, ...}]}
E                 Full diff:
E                   {
E                    'route': [{'amount_msat': 2msat,
E                 -             'channel': '117x1x0',
E                 ?                          ^^  --
E                 +             'channel': '103x3x1',
E                 ?                          ^^^^
E                               'delay': 15,
E                 -             'direction': 0,
E                 ?                          ^
E                 +             'direction': 1,
E                 ?                          ^
E                 -             'id': '032cf15d1ad9c4a08d26eab1918f732d8ef8fdc6abb9640bf3db174372c491304e',
E                 +             'id': '022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59',
E                               'msatoshi': 2,
E                 -             'style': 'legacy'},
E                 ?                        ^^^^^
E                 +             'style': 'tlv'},
E                 ?                       + ^
E                              {'amount_msat': 1msat,
E                 -             'channel': '119x1x1',
E                 ?                           ^   ^
E                 +             'channel': '110x1x0',
E                 ?                           ^   ^
E                               'delay': 9,
E                               'direction': 0,
E                               'id': '0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199',
E                               'msatoshi': 1,
E                               'style': 'tlv'}],
E                   }

tests/test_gossip.py:1263: AssertionError
```

However, with `fuzzpercent` set to `0`, the test will always pass:
```patch
diff --git a/tests/test_gossip.py b/tests/test_gossip.py
index e678a0755..cd68e7bdd 100644
--- a/tests/test_gossip.py
+++ b/tests/test_gossip.py
@@ -1258,6 +1258,13 @@ def test_getroute_exclude(node_factory, bitcoind):
     with pytest.raises(RpcError):
         l1.rpc.getroute(l4.info['id'], 1, 1, exclude=[chan_l2l3, l5.info['id'], chan_l2l4])
 
+    for l in [l1, l2, l3, l4, l5]:
+        for ll in [i for i in [l1, l2, l3, l4, l5] if i != l]:
+            assert (l.rpc.getroute(ll.info['id'], 1, 1, exclude=None,
+                                   fuzzpercent=0) ==
+                    l.rpc.getroute(ll.info['id'], 1, 1, exclude=[],
+                                   fuzzpercent=0))
+
```
This seems kind of weird to me since I requested a route for only `1msat` !

**Comment by ZmnSCPxj** [comment] 2020-02-16 23:20
If the `fuzzpercent` is hitting, then it might not be about "whether `exclude` is `None` or `[]`" but rather "whether the RNG hates you or not".  Maybe try without `fuzzpercent=0` and `exclude=None` both times?

**Comment by s-tikhomirov** [comment] 2020-02-17 00:38
The same commands with `fuzzpercent=0` produce the same result (show a route).

**Comment by ZmnSCPxj** [comment] 2020-02-17 00:52
Try *without* `fuzzpercent` but with multiple calls ***without*** `exclude`.  Because the difference in output is likely to be because of the randomization.

**Comment by s-tikhomirov** [comment] 2020-02-17 00:58
Trying without `fuzzpercent` and without `exclude`. It's inconsistent:
```
$ lightning-cli getroute -k id=0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d riskfactor=1 maxhops=1 fromid=038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9 msatoshi=1000
{
   "route": [
      {
         "id": "0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d",
         "channel": "1415068x147x0",
         "direction": 1,
         "msatoshi": 1000,
         "amount_msat": "1000msat",
         "delay": 9,
         "style": "tlv"
      }
   ]
}
$ lightning-cli getroute -k id=0303ba0fed62039df562a77bfcec887a9aa0767ff6519f6e2baa1309210544cd3d riskfactor=1 maxhops=1 fromid=038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9 msatoshi=1000
{
   "code": 205,
   "message": "Could not find a route"
}
```

**Comment by ZmnSCPxj** [comment] 2020-02-17 01:02
Okay, I suspect this is `wontfix`, because the difference in behavior is not because of `exclude`, but because of `fuzzpercent`.  The `fuzzpercent` should not really cause a "Could not find a route" (and you already filed #3528 / #3523 for that), but if `fuzzpercent` is non-zero (the default) then you *will* get randomly-selected routes each call, `exclude` or not.

**Comment by ZmnSCPxj** [comment] 2020-02-19 06:43
Closing, as root cause is route randomization.

**Closed by ZmnSCPxj** 2020-02-19 06:43 UTC
