### ISSUE TITLE
peer transient failures in master

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#5958] opened 2023-02-05 02:01 UTC
After updating to 554cbf08c39cdbc68a977868f1101341acbb7aa0 there are a ton of peers that keep getting disconnected with this error: 

```
Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
```

**Comment by vincenzopalazzo** [comment] 2023-02-05 08:35
Is nothing in the changelog that can help? I will update my testnet nodes to see if I can reproduce it

**Comment by grubles** [comment] 2023-02-05 14:11
Not sure which changelog you're referring to. One thing to note is it seems the same set of peers keep getting disconnected despite restarting `lightningd`.

**Comment by vincenzopalazzo** [comment] 2023-02-05 19:40
Sorry I was mean the log, I did not know why I wrote changelog!

**Comment by grubles** [comment] 2023-02-06 20:42
I dug out some more log messages that might be more helpful:

```
2023-02-06T20:36:07.287Z DEBUG   REDACTED-connectd: Connect OUT
2023-02-06T20:36:07.287Z DEBUG   REDACTED-connectd: peer_out WIRE_INIT            
2023-02-06T20:36:07.403Z DEBUG   REDACTED-connectd: peer_in WIRE_INIT
2023-02-06T20:36:07.403Z DEBUG   REDACTED-gossipd: seeker: disabling gossip
2023-02-06T20:36:07.403Z INFO    REDACTED-chan#14262: Peer transient failure in CHANNELD_NORMAL: Disconnected                                           
2023-02-06T20:36:07.403Z DEBUG   REDACTED-lightningd: Peer says it sees our address as:                                                                                                                 
2023-02-06T20:36:07.403Z DEBUG   REDACTED-chan#14262: Peer has reconnected, state CHANNELD_NORMAL: connectingsubd                                      
2023-02-06T20:36:07.408Z DEBUG   REDACTED-channeld-chan#14262: pid 679883, msgfd 145                                                                                                                                          
2023-02-06T20:36:07.408Z DEBUG   REDACTED-chan#14262: Already have funding locked in (and ready to announce)                                                                                                                  
2023-02-06T20:36:07.409Z DEBUG   lightningd: update_feerates: feerate = 998, min=253, max=45465, penalty=720                                
--                                                                    
2023-02-06T20:36:07.412Z DEBUG   hsmd: Client: Received message 18 from client                
2023-02-06T20:36:07.412Z DEBUG   REDACTED-channeld-chan#14262: peer_out WIRE_CHANNEL_REESTABLISH                                                                                                                              
2023-02-06T20:36:07.412Z DEBUG   REDACTED-channeld-chan#14262: billboard: Sent reestablish, waiting for theirs  
2023-02-06T20:36:07.605Z INFO    REDACTED-channeld-chan#14262: Peer connection lost                             
2023-02-06T20:36:07.605Z DEBUG   REDACTED-channeld-chan#14262: Status closed, but not exited. Killing            
2023-02-06T20:36:07.605Z INFO    REDACTED-chan#14262: Peer transient failure in CHANNELD_NORMAL: channeld: Owning subdaemon channeld died (62208)
2023-02-06T20:36:07.605Z DEBUG   REDACTED-connectd: peer_in WIRE_WARNING
2023-02-06T20:36:07.606Z INFO    REDACTED-connectd: Received WIRE_WARNING: warning: Feature 28 requires feature 20
2023-02-06T20:36:07.606Z DEBUG   connectd: drain_peer
2023-02-06T20:36:07.606Z DEBUG   connectd: drain_peer draining subd!
```

**Comment by endothermicdev** [comment] 2023-02-06 21:26
I'm pretty sure this is a consequence of #5670, specifically db88b7bc6d3a74bd9850f4e80e53f18483fb3f87.

**Comment by grubles** [comment] 2023-02-06 23:02
Ok I commented out `experimental-dual-fund` and I'm able to reconnect!

**Comment by vincenzopalazzo** [comment] 2023-02-07 08:42
Ok closing this because it is expected, thanks @grubles  for reporting, and @endothermicdev for the solution!

**Closed by vincenzopalazzo** 2023-02-07 08:42 UTC
Labels: in diagnostic
