### ISSUE TITLE
Unilateral channel closure

### ISSUE THREAD

**Issue by gallizoltan** [ElementsProject/lightning#4485] opened 2021-04-21 16:38 UTC
### Issue and Steps to Reproduce
My clightning client unilaterally closed one of my channels:
```
$ lightning-cli listpeers 0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0    
{
   "peers": [
      {
         "id": "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0",
         "connected": false,
         "channels": [
            {
               "state": "ONCHAIN",
               "scratch_txid": "43428dc5a8d8bf5c59b99b3d37b43fc6ac6536b5c20810114d71e5984ef64f6e",
               "last_tx_fee": "60339000msat",
               "feerate": {
                  "perkw": 67341,
                  "perkb": 269364
               },
               "owner": "onchaind",
               "short_channel_id": "668538x1376x1",
               "direction": 1,
               "channel_id": "d96348632825f05587c690ef569cd311a3e0040ab67ca4746f42759907eabeb2",
               "funding_txid": "b3beea079975426f74a47cb60a04e0a311d39c56ef90c68755f02528634863d9",
               "close_to_addr": "bc1qehsczk386dk85gf7afu6l0sdwvdudefupfsyfa",
               "close_to": "0014cde1815a27d36c7a213eea79afbe0d731bc6e53c",
               "private": false,
               "opener": "local",
               "closer": "remote",
               "features": [
                  "option_static_remotekey"
               ],
               "funding_allocation_msat": {
                  "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0": 0,
                  "03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5": 8000000000
               },
               "funding_msat": {
                  "0390b5d4492dc2f5318e5233ab2cebf6d48914881a33ef6a9c6bcdbb433ad986d0": "0msat",
                  "03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5": "8000000000msat"
               },
               "msatoshi_to_us": 4347902133,
               "to_us_msat": "4347902133msat",
               "msatoshi_to_us_min": 1047961410,
               "min_to_us_msat": "1047961410msat",
               "msatoshi_to_us_max": 8000000000,
               "max_to_us_msat": "8000000000msat",
               "msatoshi_total": 8000000000,
               "total_msat": "8000000000msat",
               "fee_base_msat": "1000msat",
               "fee_proportional_millionths": 400,
               "dust_limit_satoshis": 546,
               "dust_limit_msat": "546000msat",
               "max_htlc_value_in_flight_msat": 18446744073709551615,
               "max_total_htlc_in_msat": "18446744073709551615msat",
               "their_channel_reserve_satoshis": 80000,
               "their_reserve_msat": "80000000msat",
               "our_channel_reserve_satoshis": 80000,
               "our_reserve_msat": "80000000msat",
               "spendable_msatoshi": 3663782435,
               "spendable_msat": "3663782435msat",
               "receivable_msatoshi": 3572097867,
               "receivable_msat": "3572097867msat",
               "htlc_minimum_msat": 0,
               "minimum_htlc_in_msat": "0msat",
               "their_to_self_delay": 144,
               "our_to_self_delay": 961,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2021-01-31T22:14:35.726Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_NORMAL",
                     "cause": "user",
                     "message": "Lockin complete"
                  },
                  {
                     "timestamp": "2021-04-21T13:16:28.648Z",
                     "old_state": "CHANNELD_NORMAL",
                     "new_state": "AWAITING_UNILATERAL",
                     "cause": "protocol",
                     "message": "Offered HTLC 36765 SENT_ADD_ACK_REVOCATION cltv 680014 hit deadline"
                  },
                  {
                     "timestamp": "2021-04-21T13:17:59.195Z",
                     "old_state": "AWAITING_UNILATERAL",
                     "new_state": "FUNDING_SPEND_SEEN",
                     "cause": "onchain",
                     "message": "Onchain funding spend"
                  },
                  {
                     "timestamp": "2021-04-21T13:18:00.647Z",
                     "old_state": "FUNDING_SPEND_SEEN",
                     "new_state": "ONCHAIN",
                     "cause": "onchain",
                     "message": "Onchain init reply"
                  }
               ],
               "status": [
                  "CHANNELD_NORMAL:Reconnected, and reestablished.",
                  "ONCHAIN:Tracking our own unilateral close",
                  "ONCHAIN:5 outputs unresolved: in 942 blocks will spend DELAYED_OUTPUT_TO_US (43428dc5a8d8bf5c59b99b3d37b43fc6ac6536b5c20810114d71e5984ef64f6e:2) using OUR_DELAYED_RETURN_TO_WALLET"
               ],
               "in_payments_offered": 406,
               "in_msatoshi_offered": 181247746784,
               "in_offered_msat": "181247746784msat",
               "in_payments_fulfilled": 239,
               "in_msatoshi_fulfilled": 46419519304,
               "in_fulfilled_msat": "46419519304msat",
               "out_payments_offered": 37103,
               "out_msatoshi_offered": 8395838277368,
               "out_offered_msat": "8395838277368msat",
               "out_payments_fulfilled": 206,
               "out_msatoshi_fulfilled": 50071617171,
               "out_fulfilled_msat": "50071617171msat",
               "htlcs": [
                  {
                     "direction": "out",
                     "id": 36765,
                     "msatoshi": 437114698,
                     "amount_msat": "437114698msat",
                     "expiry": 680014,
                     "payment_hash": "87bb6457a72f31a548d8f9b7f8156bd58f56990eda86a921f35c31486a8771d4",
                     "state": "SENT_ADD_ACK_REVOCATION"
                  }
               ]
            }
         ]
      }
   ]
}
```
Could someone please tell me why did this happen? I don't understand the message: "Offered HTLC 36765 SENT_ADD_ACK_REVOCATION cltv 680014 hit deadline".

And **what could I do to avoid this in the future?** I mean I definitely did not want to close that channel, and the closure cost me a lot of money at the current Mempool conditions.

### `getinfo` output
```
$ lightning-cli getinfo
{
   "id": "03d67f36c4f81789e2fe425028bacc96b199813eae426c517f589a45f1136c1fe5",
   "alias": "Jubilee",
   "color": "dc42f4",
   "num_peers": 33,
   "num_pending_channels": 0,
   "num_active_channels": 30,
   "num_inactive_channels": 1,
   "address": [
      {
         "type": "ipv4",
         "address": "212.96.34.143",
         "port": 9735
      },
      {
         "type": "torv2",
         "address": "yqygrtvwihl3exb2.onion",
         "port": 9735
      },
      {
         "type": "torv3",
         "address": "ihhsjdncang7ve2rvhuunvy45bxvmh2qwz3vh7mohbouizd36ywnxeid.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv6",
         "address": "::",
         "port": 9735
      },
      {
         "type": "ipv4",
         "address": "0.0.0.0",
         "port": 9735
      }
   ],
   "version": "0.10.0",
   "blockheight": 680035,
   "network": "bitcoin",
   "msatoshi_fees_collected": 391771796,
   "fees_collected_msat": "391771796msat",
   "lightning-dir": "/home/user/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment] 2021-04-24 13:04
As you guessed, that HTLC hitting its deadline is the cause of the closure. It must've been forwarded, and then one of the  downstream nodes failed, or the destination decided to hodl on to it (which is why we're been careful about mentioning that `htlc_accepted` hooks MUST NOT hold on to invoices for a long period of time).

Sadly this is how we have to handle misbehavior from downstream nodes, since we have to resolve the HTLC on-chain if we can't do so off-chain. You can likely follow the chain of closures from your channel down to the next node, see if any other channel of theirs closed and continue that way. Given that your peer is not connected, it is likely that it was that peer which failed to resolve the HTLC.

As for preventing this in future:

 - Pick peers you open channels with carefully to ensure they are online for this type of resolutions
 - If unsure have them open a channel to you, so they pay funding and an eventual close, then rebalance
 - Ensure you yourself are online as much as possible

Sadly this is the cost of being a routing node, the only way to ensure this happens as rarely as possible would be not to route payments, which puts you in full control of HTLC timing.

**Comment by m-schmoock** [comment] 2021-08-14 11:49
@cdecker
Do you want to keep this open as documentation on things that can happen or can we close it?

**Comment by cdecker** [comment] 2021-08-14 12:47
Let's close it, there is nothing actionable at this point 👍

**Closed by cdecker** 2021-08-14 12:47 UTC
Labels: question
