### ISSUE TITLE
Channel closed doe to update_fee out of range

### ISSUE THREAD

**Issue by jcsmesquita** [ElementsProject/lightning#1566] opened 2018-06-11 21:06 UTC
I'm running a c-lightning node ([link](https://1ml.com/node/024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca)) for satoshis.place and noticed the number of open channels is pretty low (between 10-20). Digging deeper I see a lot of channels have been opened to my node, then closed by my node due to an update_fee outside of range, example:

```
"status": [
  "CHANNELD_NORMAL:update_fee 9489 outside range 253-7070",
  "ONCHAIN:Tracking our own unilateral close",
  "ONCHAIN:All outputs resolved: waiting 71 more blocks before forgetting channel"
]
```

Is there anything I can do to loosen up this restriction?

Here's my config output:
```
{
  "# version": "v0.5.2-2016-11-21-2760-gd9eba0e9",
  "bitcoin-datadir": "<redacted>",
  "rgb": "42f474",
  "alias": "www.satoshis.place",
  "pid-file": "lightningd-bitcoin.pid",
  "log-level": "DEBUG",
  "log-prefix": "lightningd(26333):",
  "lightning-dir": "<redacted>",
  "rpc-file": "lightning-rpc",
  "daemon": "false",
  "ignore-fee-limits": false,
  "watchtime-blocks": 144,
  "max-locktime-blocks": 720,
  "funding-confirms": 3,
  "commit-fee-min": 200,
  "commit-fee-max": 2000,
  "commit-fee": 500,
  "default-fee-rate": 40000,
  "cltv-delta": 14,
  "cltv-final": 8,
  "commit-time": 10,
  "fee-base": 1000,
  "rescan": 15,
  "fee-per-satoshi": 10,
  "bind-addr": "0.0.0.0:9735",
  "announce-addr": "88.98.213.235:9735",
  "offline": "false",
  "autolisten": true,
  "network": "bitcoin",
  "allow-deprecated-apis": true,
  "autocleaninvoice-cycle": 0,
  "autocleaninvoice-expired-by": 0,
  "always-use-proxy": false
}
```

Thanks <3

**Comment by cdecker** [comment] 2018-06-11 21:30
Duplicate of #1560 

We have some idea on how to address this, by raising the acceptable fee range and smoothing fee transitions in order not to be so sensitive to our estimator getting it wrong.

**Comment by jcsmesquita** [comment] 2018-06-12 17:59
Thanks @cdecker, we can close this.
I asked roasbeef yesterday about this and he said it could be an issue with lnd nodes? They were fixing it / fixed it on master.

**Closed** 2018-06-12 17:59 UTC
Labels: duplicate, fee
