### ISSUE TITLE
Lightning_ processes go <defunct> on startup of daemon

### ISSUE THREAD

**Issue by RvMp** [ElementsProject/lightning#779] opened 2018-01-25 23:05 UTC
Lightning_ processes go <defunct> on startup of daemon. 
Seems to function normal so i'm not sure what is going wrong. Running 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

Running with bitcoin core (latest version) on ext4 filesystem (LVM). 

```
19093 16132 16132 16132 ?           -1 Ss       0   0:00  \_ sshd: ronald [priv]
16132 16233 16132 16132 ?           -1 S     1000   0:00  |   \_ sshd: ronald@pts/2
16233 16234 16234 16234 pts/2    17841 Ss    1000   0:00  |       \_ -bash
16234 16246 16246 16234 pts/2    17841 S        0   0:00  |           \_ sudo bash -l
16246 16252 16252 16234 pts/2    17841 S        0   0:00  |               \_ bash -l
16252 16264 16264 16234 pts/2    17841 S        0   0:00  |                   \_ su - lightning
16264 16265 16265 16234 pts/2    17841 S     1002   0:00  |                       \_ -su
16265 17841 17841 16234 pts/2    17841 S+    1002   0:00  |                           \_ ./lightningd/lightningd --network=testnet --lightning-dir=/home/lightning/.lightning-testnet --bitcoin-datadir /home/bitcoin/.bitcoin/testnet3 --alias test123 --log-level=debug
17841 17842 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_chann] <defunct>
17841 17843 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_closi] <defunct>
17841 17844 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_gossi] <defunct>
17841 17845 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_hsmd] <defunct>
17841 17846 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_oncha] <defunct>
17841 17847 17841 16234 pts/2    17841 Z+    1002   0:00  |                               \_ [lightning_openi] <defunct>
17841 17848 17841 16234 pts/2    17841 S+    1002   0:00  |                               \_ /home/lightning/lightning/lightningd/lightning_hsmd
17841 17849 17841 16234 pts/2    17841 S+    1002   0:00  |                               \_ /home/lightning/lightning/lightningd/lightning_gossipd
```

**Comment by RvMp** [comment] 2018-01-25 23:17
Might be because of https://github.com/ElementsProject/lightning/issues/780

**Comment by cdecker** [comment] 2018-02-11 18:55
@rustyrussell could it be processes are not reaped correctly under some conditions?

**Comment by Ulmo** [comment] 2018-02-11 23:12
I have trouble understanding the English of the following sentence as it relates to being a duplicate of my report:

"Lightning_ processes go on startup of daemon."

I can't make heads or tails of that sentence and what it is supposed to mean.  RvMp, can you clarify?

**Comment by RvMp** [comment] 2018-02-12 08:31
Yes I was. I think github didn’t like <defunct> in the body :-(

**Comment by RvMp** [comment] 2018-02-12 08:32
Try to type defunct with < and > around it. It is stripped :-)

**Closed** 2019-01-08 00:16 UTC
