### ISSUE TITLE
Intermittant node_announce sent before channel_announce?

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/lightning#278] opened 2017-09-15 00:39 UTC
Hit this one in test_onchain_invoice:

======================================================================
ERROR: test_onchain_invoice (__main__.LightningDTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_lightningd.py", line 490, in test_onchain_invoice
    .format(l3.info['id']))
  File "/home/rusty/devel/cvs/lightning/tests/utils.py", line 146, in wait_for_log
    return self.wait_for_logs([regex], timeout)
  File "/home/rusty/devel/cvs/lightning/tests/utils.py", line 123, in wait_for_logs
    raise TimeoutError('Unable to find "{}" in logs.'.format(exs))
TimeoutError: Unable to find "{re.compile('Received node_announcement for node 035cfe3c2950297df62fd18064d4a2aa4ae0dc956f5b9d2b9383067e66883390ed')}" in logs.

Here's the log message which explains it: (lightning-3):

  b'lightning_gossipd(5574): TRACE: Received node_announcement for node 035cfe3c2950297df62fd18064d4a2aa4ae0dc956f5b9d2b9383067e66883390ed'
  b'lightning_channeld(5710): TRACE: peer_in WIRE_CHANNEL_ANNOUNCEMENT'
  b'lightning_gossipd(5574): TRACE: Node not found, was the node_announcement preceeded by at least channel_announcement?'

Here's the test up to the failure:

    def test_onchain_invoice(self):
        # HTLC 1->2->3, 2->3 goes down (after letting first HTLC complete).
        disconnects = ['-WIRE_REVOKE_AND_ACK*3', 'permfail']
        l1 = self.node_factory.get_node()
        l2 = self.node_factory.get_node()
        l3 = self.node_factory.get_node(disconnect=disconnects)

        # l3 connects to l2, so l2 spins reconnecting and l3 drops to chain.
        l1.rpc.connect('localhost', l2.info['port'], l2.info['id'])
        l3.rpc.connect('localhost', l2.info['port'], l2.info['id'])
        self.fund_channel(l1, l2, 10**6)
        self.fund_channel(l3, l2, 10**6)

        # Give l2 some money to play with.
        self.pay(l3, l2, 2 * 10**8)

        # Must be bigger than dust!
        rhash = l3.rpc.invoice(10**8, 'onchain_invoice')['rhash']
        # Wait for route propagation.
        l1.bitcoin.rpc.generate(5)
        l1.daemon.wait_for_log('Received node_announcement for node {}'
                               .format(l3.info['id']))

Gah, no tar.xz support?  Yech, zip:
[test_onchain_invoice.zip](https://github.com/ElementsProject/lightning/files/1304955/test_onchain_invoice.zip)

**Comment by rustyrussell** [comment] 2017-09-20 03:40
OK, I think I see what's happening.  channeld's announce_channel sends channel_announcement to gossipd, then sends master a "channel_announced" message.  The master sends the node_announce message to gossipd, which it can read before it reads announce_channel from channeld.

Perhaps gossipd should simply watch for channel_announcements which refer to itself, and ping master for a node_announce the first time that happens?

**Comment by cdecker** [comment] 2017-10-31 10:48
Duplicate of #320

**Closed by cdecker** 2017-10-31 10:48 UTC
Labels: bug, gossip
