### ISSUE TITLE
Error reading a transaction from DB after upgrade from v0.8.2 to v0.9.0-1

### ISSUE THREAD

**Issue by cryptapus** [ElementsProject/lightning#3961] opened 2020-08-20 21:30 UTC
After upgrading from `v0.8.2` lightningd is crashing and not able to start.

I might have a non-standard setup here, my `v0.18.1` bitcoind is on a remote host on the same LAN. Debian Buster.

Here is my lightning config file:

    network=bitcoin
    alias=xxxxxxxx
    addr=xxx.xxx.xxx.xxx:9735
    bitcoin-cli=/home/<username>/bin/bitcoin-cli
    bitcoin-rpcconnect=xxx.xxx.xxx.xxx
    bitcoin-rpcuser=xxxxxxxxx
    bitcoin-rpcpassword=xxxxxxxx

Here is the output at startup:

    2020-08-20T21:xx:xx.327Z INFO database: Updating database from version 131 to 138
    2020-08-20T21:xx:xx.391Z INFO plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
    lightningd: bitcoin/tx.c:459: linearize_wtx: Assertion `len == written' failed.
    lightningd: FATAL SIGNAL 6 (version v0.9.0-1)
    0x55c4c2f5bf32 send_backtrace
            common/daemon.c:38
     0x55c4c2f5bfbc crashdump
            common/daemon.c:51
    0x7f141a0d983f ???
            ???:0
    0x7f141a0d97bb ???
            ???:0
    0x7f141a0c4534 ???
            ???:0
    0x7f141a0c440e ???
            ???:0
    0x7f141a0d2101 ???
            ???:0
    0x55c4c2f72cc0 linearize_wtx
            bitcoin/tx.c:459
    0x55c4c2f72cd4 wally_tx_clone
            bitcoin/tx.c:22
    0x55c4c2f72fdf bitcoin_tx_with_psbt
            bitcoin/tx.c:543
    0x55c4c2f89929 db_column_psbt_to_tx
            wallet/db.c:1585
    0x55c4c2f8fc66 wallet_stmt2channel
            wallet/wallet.c:1243
    0x55c4c2f90087 wallet_channels_load_active
            wallet/wallet.c:1366
    0x55c4c2f900ee wallet_init_channels
            wallet/wallet.c:1382
    0x55c4c2f4ad0f load_channels_from_wallet
            lightningd/peer_control.c:1503
    0x55c4c2f3b0ec main
            lightningd/lightningd.c:924
    0x7f141a0c609a ???
            ???:0
    0x55c4c2f2a149 ???
            ???:0
    0xffffffffffffffff ???
            ???:0
    Aborted

Any hints? Thanks!

**Comment by ZmnSCPxj** [comment] 2020-08-21 05:28
I do not think it is related to your bitcoind setup.  The traceback seems to indicate that this is a problem with the database..  Are you using SQLITE (default if you did not change anything from a stock install) or PostGreSQL (you should know if you are using PostGreSQL)?  To debug this we would need access to the DB I think.  Probably best to send to @cdecker as he is most familiar with the DB.

**Comment by cryptapus** [comment] 2020-08-21 05:42
SQLITE. This is an older c-lightning db that originally started from early days (maybe ~blk 550000) I think. This particular host I don't mind sharing the db privately if it's helpful.

**Comment by cdecker** [comment] 2020-08-26 12:26
Building a migration for this is a bit tricky since it requires us to fully load the channel into memory, in order to decide whether to drop it or not. But should be doable.

**Comment by cryptapus** [comment] 2020-08-26 16:42
If it's helpful, find me on irc and I can run some queries on the DBs that I have, maybe we can search for them before they are loaded?

Based on another node of the same vintage, I think these DBs could have started from ~`v0.5.2`. I noticed a few early channels that show up in `peerinfo` but do not in the `summary` pluggin if that means anything.

**Comment by cryptapus** [comment] 2020-08-29 19:27
Alternatively, since I've been _reckless_ in the past and this might be such an isolated issue, it might not be worth a code change. Could I just manually remove these kinds of transactions from my `channels` table? Any other tables I should edit without affecting my other good channels? Maybe `peers`... any other notable ones?

I'm happy to try a patch fix on this too, if it could conceivably help others.

**Comment by freerko** [comment] 2020-09-01 22:25
I might have the same(?) issue here, updated a >2 years old node with SQLite from v0.8.2.1 to v0.9.0 via the PPA and starting lightningd results in the error:

```
lightningd: bitcoin/tx.c:459: linearize_wtx: Assertion `len == written' failed.
lightningd: FATAL SIGNAL 6 (version 0.9.0-1)
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: FATAL SIGNAL 11 (version 0.9.0-1)
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: libbacktrace: no debug info in ELF executable
lightningd: Died with signal 11
```

 In my setup the bitcoind is on localhost.

**Comment by niftynei** [comment] 2020-09-03 03:27
A bit late to the party here, apologies. @cryptapus re:

> Any of these frames worth examining?

In the `db_column_psbt_to_tx` frame, can you print the `src` as hex? That'll be the raw bytes for the PSBT it's attempting to decode.

> This channel is from blk ~508000 and is a very low value, none on my side. I'm somewhat confident I've attempted a lightning-cli close on this in the distant past.

Regarding your other channel, on a different node, I'm not sure that I understand the issue. Is it that it's stuck in "SHUTTING_DOWN" and hasn't resolved/ closed? You might re-try force closing it. If that doesn't work and you have no money in it, you can use the `dev-forget-channel` command to wipe it (you'll need to configure with --enable-developer to get dev commands; `./configure --enable-developer`).

**Comment by cryptapus** [comment] 2020-09-03 09:54
@niftynei emailed you my gdb output.

Rolling back to `v0.8.2` from a backup (understood not safe but this is a test node) and running `dev-forget-channel` on the channel that looks suspiciously similar to the one above appears to solve this issue.

**Comment by freerko** [comment] 2020-09-07 17:28
Hi, what else can I do to start my lightning node again? I downloaded the clightning-v0.8.2.1-Ubuntu-18.04.tar.xz release and extracted the files over the ones from the PPA, but lightningd doesn't start and spits out the error "Refusing to migrate down from version 138 to 131".

**Comment by niftynei** [comment] 2020-09-07 20:44
@freerko working on a patch to get past the fail on start right now; should have it done shortly and it will ship in the RC we're cutting this week :crossed_fingers:

**Comment by niftynei** [comment] 2020-09-08 22:08
Good news, this appears to be fixed in master as of this very moment, confirmed broken in v0.9.0. You'll still need to force close/forget the channels that are affected by this, but your node should start without a problem. I'm going to attribute this fix to the work @jgriffiths has been doing on libwally in the past few months.

cc @freerko if you want to try out master or wait for the RC (which should be cut this week). @cryptapus thanks for the test data!

**Comment by cryptapus** [comment] 2020-09-09 11:53
@niftynei confirmed, `master` branch starts without issues, then with `--enable-developer` I've been able to remove this channel with `dev-forget-channel`. I'll leave this issue open for @freerko. Thanks!

**Closed** 2020-09-10 02:25 UTC
