### ISSUE TITLE
Failed connect out for ...

### ISSUE THREAD

**Issue by vedran6** [ElementsProject/lightning#785] opened 2018-01-26 03:15 UTC
When trying to connect to what seems to be a well connected testnet node, I get the following error:

```
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
lightning_gossipd(32761): TRACE: Failed connected out for 037a07ab833a6e09c922c48e01068b6fea276b63ee843ee892932ff965a1768031, will try again
...
```

Two issues here:

1) it's unclear why the connection is failing
2) `lightningd` keeps trying to connect to this peer indefinitely, instead of failing and giving up at some point. The CLI command simply hangs, and killing it manually causes the shell to come back, but `lightningd` keeps trying to connect in the background.

**Comment by cdecker** [comment] 2018-01-26 12:28
Duplicate of #748

**Closed by cdecker** 2018-01-26 12:28 UTC
