### ISSUE TITLE
old channeld process laying around?

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#976] opened 2018-02-11 17:16 UTC
### Issue and Steps to Reproduce

```
$ ps uxf # I deleted some irrelevent lines
ulmo     32068  0.0  0.0  11220  1992 pts/2    S    Jan28   0:00 /usr/local/libexec/c-lightning/lightning_channeld
ulmo     29376  3.2  3.1 143964 127068 pts/1   S    Feb09 123:24  |   |   \_ lightningd --network bitcoin --log-level=debug --ignore-fee-limits=false --log-file=/home/ulmo/log/log.29267.5 --alias=Ionic.Release
ulmo     29377  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_chann] <defunct>
ulmo     29378  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_closi] <defunct>
```
```
$ ls -l /proc/32068/fd
total 0
lrwx------ 1 ulmo staff 64 Feb 11 17:07 0 -> socket:[9163785]
lrwx------ 1 ulmo staff 64 Feb 11 17:07 1 -> /dev/pts/2
lrwx------ 1 ulmo staff 64 Feb 11 17:06 2 -> /dev/pts/2
lrwx------ 1 ulmo staff 64 Feb 11 17:07 3 -> socket:[9160832]
lrwx------ 1 ulmo staff 64 Feb 11 17:07 4 -> socket:[9161772]
lrwx------ 1 ulmo staff 64 Feb 11 17:07 5 -> socket:[9161520]
```

### `getinfo` output
```
{ "id" : "kindofnotyourbusiness", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "1111.2222.3333.4444", "port" : 9735 }, 
                { "type" : "ipv6", "address" : "face::kind:of:not:your:business", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1904-g2a979a2", "blockheight" : 508694, "network" : "bitcoin" }
```

**Comment by Ulmo** [comment] 2018-02-11 17:16
The older process is probably from an older version.  I attempt to update lightningd in a reasonable manner for every new long term invocation.

**Comment by cdecker** [comment] 2018-02-11 18:55
Duplicate of #779

**Closed by cdecker** 2018-02-11 18:55 UTC

**Comment by Ulmo** [comment] 2018-02-11 23:18
My process is not defunct as it is in #779:

$ ps axf
ulmo     32068  0.0  0.0  11220  1992 pts/2    S    Jan28   0:00 /usr/local/libexec/c-lightning/lightning_channeld

The above is not marked defunct; there are defunct processes marked defunct; I'm not complaining about those.  Those seem like a minor bug.  Here are my defunct processes that I'm not complaining about here:

ulmo     29376  3.4  3.1 143964 127796 pts/1   S    Feb09 142:36  |   |   \_ lightningd --network bitcoin --log-level=debug --ignore-fee-limits=false --log-file=/home/ulmo/log/log.29267.5 --alias=Ionic.Release
ulmo     29377  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_chann] <defunct>
ulmo     29378  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_closi] <defunct>
ulmo     29379  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_gossi] <defunct>
ulmo     29380  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_hsmd] <defunct>
ulmo     29381  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_oncha] <defunct>
ulmo     29382  0.0  0.0      0     0 pts/1    Z    Feb09   0:00  |   |       \_ [lightning_openi] <defunct>

The problem is an older than lightningd process.

**Comment by Ulmo** [comment] 2018-02-11 23:22
Ok, due to Github rules as follows, I must re-open the above by making a copy.

How to re-open an issue in github

Github has very simple rights/privileges (and even simpler management for them).

If you are not a collaborator of a repo, then (in regards to issues)

    you can open issues
    you can comment on all existing issues (open or closed)
    you can close your own issues
    you can re-open your own issues *if you closed them yourself
    you cannot close or re-open issues opened by someone else
    you cannot re-open your own issues if a repo collaborator closed them
