### ISSUE TITLE
Crash after double spend attempt following un-cooperative channel closure.

### ISSUE THREAD

**Issue by alecalve** [ElementsProject/lightning#777] opened 2018-01-25 21:36 UTC
For some reason, my node tried to commit a double spend when re-reacting to an already closed channel after I restarted the node. Let me know if you need more details.

```
lightningd(7830): Broadcasting tx [snip]: 25 error code: -25
error message:
Missing inputs
*** Error in `./lightningd/lightningd': realloc(): invalid next size: 0x0000000002db5bb0 ***
======= Backtrace: =========
[snip]
Fatal signal 6. 0x410673 log_crash
        lightningd/log.c:462
0x7fcb309404af ???
        ???:0
0x7fcb30940428 ???
        ???:0
0x7fcb30942029 ???
        ???:0
0x7fcb309827e9 ???
        ???:0
0x7fcb3098e4a9 ???
        ???:0
0x7fcb3098f838 ???
        ???:0
0x464c6b tal_resize_
        ccan/ccan/tal/tal.c:738
0x462a6a do_vfmt
        ccan/ccan/tal/str/str.c:61
0x462b78 tal_vfmt
        ccan/ccan/tal/str/str.c:91
0x4493da db_exec
        wallet/db.c:237
0x44966c db_commit_transaction
        wallet/db.c:292
0x4230da sd_msg_read
        lightningd/subd.c:508
0x457975 next_plan
        ccan/ccan/io/io.c:59
0x45844c do_plan
        ccan/ccan/io/io.c:387
0x45848a io_ready
        ccan/ccan/io/io.c:397
0x459d48 io_loop
        ccan/ccan/io/poll.c:305
0x40efd2 main
        lightningd/lightningd.c:347
0x7fcb3092b82f ???
        ???:0
0x403168 ???
        ???:0
0xffffffffffffffff ???
        ???:0
Log dumped in crash.log
[snip]
Aborted (core dumped)
```

**Comment by jb55** [comment] 2018-01-25 21:48
do you have a more detailed log by any chance (via `--log-level=debug`) ?

**Comment by alecalve** [comment] 2018-01-25 21:53
Let me enable this and restart the node, hopefully it'll reproduce

**Comment by cdecker** [comment] 2018-01-25 22:02
That's interesting, since it is trying to fmt a fixed string and is failing to do so.

**Comment by alecalve** [comment] 2018-01-25 22:12
Unfortunately, I wasn't able to reproduce after restarting with `--log-level=debug`

**Comment by cdecker** [comment] 2018-02-06 15:31
Closing for now since we can't reproduce the issue. Please reopen if the error returns and provide as much context as possible :wink:

**Closed by cdecker** 2018-02-06 15:31 UTC
