### ISSUE TITLE
Long periods of unresponsiveness every time a block is added

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#5682] opened 2022-10-31 16:33 UTC
### Issue and Steps to Reproduce
```
$ gnuplot --persist 3< <(grep -Fa -A1 'Adding block' /var/log/lightningd.log | awk '
    match($0, /^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2})\.[0-9]{3}Z/, m) {
        time = mktime(m[1]" "m[2]" "m[3]" "m[4]" "m[5]" "m[6]" 0", 1)
    }
    start { print time - start ; start = 0 }
    /Adding block/ { start = time }
') <<END
set style histogram rowstacked gap 0
set style fill solid 0.5 border lt -1
set xlabel "Duration of quiescence (seconds)"
set ylabel "Number of blocks"
binwidth = 5
set boxwidth binwidth
bin(x) = binwidth * (floor(x / binwidth) + 0.5)
plot "/proc/self/fd/3" using (bin($1)):(1.0) smooth freq with boxes notitle
END
```
![chart](https://user-images.githubusercontent.com/797782/199053879-20b777fb-9a92-4640-8972-7199671fa53b.svg)

This histogram shows the elapsed time from each "Adding block" log message until the immediately succeeding message in the log. My node is very busy and normally spews many pages of log messages every second, but whenever a block is found, the whole world grinds to a standstill, often for upwards of two minutes. During these standstills, all RPC calls through `lightning-cli` hang, and they only return after block processing has finished. I strongly suspect that all HTLC additions and removals in channels are also being deferred until after block processing has finished. If so, this implies a rather huge thorn in the user experience for any Lightning users trying to route payments through CLN nodes. Indeed, I suspect a significant fraction of routing delays in the Lightning Network may be directly attributable to this issue in CLN. I have personally experienced slow payments from my Phoenix wallet in periods immediately following when a new block has been found.

What in the world is `lightningd` doing that takes so darn long whenever a block is found, and why isn't the work being done by a subdaemon? This has an odor reminiscent of doing work in the UI thread in a graphical application. Always do work in a background worker thread, and then post results back to the UI thread when finished. I would think an equivalent notion for CLN, its being a multi-process, single-threaded application, would be to have a subdaemon (`topology`?) do the work and post its findings back to `lightningd`.

### `getinfo` output
I am running [`v0.11.2-gentoo-r107`](https://github.com/whitslack/lightning/tree/v0.11.2-gentoo-r107).

**Comment by feelus** [comment] 2022-11-11 12:20
Hey @whitslack what DB and storage/backup storage are you using?

Just wanted to mention that I had the same issue running `v0.12.1` when I stored `lightningd.sqlite3` on a remote sshfs partition. I think it has to do something with [sqlite3 transactions](https://www.sqlite.org/tempfiles.html#rollback_journals), which create a journal file and it has to wait for IO to finish. As you said, any RPC calls would block for a while, for me usually around 30sec. I've since moved my main and backup `lightningd.sqlite3` locations to an SSD and now `Adding block` messages take roughly 100ms.

**Comment by whitslack** [comment] 2022-11-11 17:38
@feelus: I switched to PostgreSQL years ago because SQLite was so slow. The database isn't the bottleneck. While my node is unresponsive, `lightningd` is pegging the CPU. I'm thinking of trying to profile it to find out where it's spending so much time. I'm wondering if it's doing something stupid like iterating through each transaction input in the block and, for each of those, iterating through each channel to see if that channel's funding transaction has been spent by that input. That's a pattern that would appear to work fine for a few channels but could become quite slow for a thousand channels.

Or maybe it's related to #5292, where I have a few channels that have mistakenly been searching for their HTLC timeout transactions in the blockchain for tens of thousands of blocks now. Maybe there's a linked list containing tens of thousands of redundant event listeners that's being traversed for each and every transaction input in the block.

Or maybe it's related to the fact that my `lightningd` balloons out to around 5 GB of memory usage during startup, yet most of that memory gets swapped out and never referenced again.

I often wonder whether the CLN devs "eat their own dogfood." By that, I mean, do they actually use the software they're developing in a production, enterprise-scale environment? Do they have nodes that are years old and that have grown up through past versions of the software that contained bugs that may have left the database in states that they don't anticipate? I'm sure CLN performs great on a young node with a handful of just-opened channels and blocks that contain only a few transactions (i.e., the integration testing environment), but when you've had thousands of channels that have forwarded tens of millions of HTLCs, and when you have multiple channels that are stuck in buggy, half-closed states, it seems to have some scaling issues.

**Comment by whitslack** [comment] 2022-11-11 20:41
I can confirm that CLN holds up payment forwards during the freezes. I just tested a Lightning withdrawal from Purse.io through my CLN node to my Breez mobile wallet, and the payment appeared as "Pending" in my Breez wallet just as lightningd was entering an "Adding block" hang, and it remained in that state for the next minute or so until lightningd finished adding the block and resumed processing messages from channeld subdaemons, whereafter my incoming payment in Breez was finalized in less than a second.

So CLN is definitely degrading the UX of payment routing in the Lightning Network. I feel like a bad steward now, knowing how many payments get routed through my node and how all these users are often having to wait around for minutes for their Lightning transactions to go through.

**Comment by whitslack** [comment] 2022-11-12 00:35
![lightningd_pstat](https://user-images.githubusercontent.com/797782/201447649-7d8acea3-3cc4-4ee3-b495-e2d58b467ac2.svg)
**Exercise:** Can you spot where the blocks occurred? :wink:

Particularly noteworthy is that the CPU time spent in kernel mode ("sys%" in the chart) goes to zero during the stalls, meaning that `lightningd` is doing some heavy internal crunching without making (m)any system calls.

**Comment by whitslack** [comment] 2022-11-12 03:22
Alright, so I rigged up a script to attach [OProfile](https://oprofile.sourceforge.io/) to `lightningd` as soon as `lightning-cli help` takes more than 1 second to return and then to interrupt the profiler when the RPC does finally return, so now I have a profile that's fairly tightly focused on the hang. As expected, 99.7% of samples showed `lightningd` executing inside `get_new_block`. I think I'm going to have to rebuild CLN with `-Og` to disable function inlining so I can see exactly which leaf functions are taking up so much time.

**Comment by cdecker** [comment] 2022-11-13 14:38
I wonder if the `utxoset` table is the bottleneck: when processing a block we will add the new outputs to that table to verify future `channel_announcements` and mark the spent ones as spent. This obviously can result in thousands of queries being sent synchronously to postgres, and if the latency to the DB is significant that can accumulate quickly, even without actual processing happening (just RTT accumulating).

Can you maybe report the size of `utxoset` and the ping between node and DB server? I have been looking into making the `utxoset` queries async, so we can enqueue them all, and then wait for the last one to complete, preventing delays to accumulate like this.

**Comment by cdecker** [comment] 2022-11-13 14:49
Come to think of it, while the accumulating RTT could explain the delay, it does not explain the high CPU usage, so likely we need to really look into what it's doing. Do you have experience with flamegraphs? They can be a very effective tool to pin down where we spend how much time, even without restarts (ptrace). There are various flamegraph implementations, my favorite being [this one](https://github.com/flamegraph-rs/flamegraph) since it does everything automatically and you don't have to handle perf profile files etc.

**Comment by whitslack** [comment] 2022-11-14 08:29
> Can you maybe report the size of `utxoset` and the ping between node and DB server?

@cdecker:
```
lightning=> select pg_size_pretty(pg_table_size('utxoset')) as table_only, pg_size_pretty(pg_total_relation_size('utxoset')) as table_plus_indices;
table_only         | 162 MB
table_plus_indices | 595 MB
```
`lightningd` is communicating with PostgreSQL via a local Unix domain socket. I don't know of any way to ping that, but I think it's safe to assume it's as fast as any other local IPC. Anyway, you're correct that `lightningd` would not be pegging the CPU if the RTT delays to the PostgreSQL server were the issue.

I've just rebuilt CLN with `-Og` to get better stack traces. I'll be restarting my node on the new build in a little while. I also added some debug logging of function call timings to help narrow down which part of `get_new_block` is taking so long. I'll comment again later with my findings.

**Comment by whitslack** [comment] 2022-11-15 07:36
I have some results to share. There appear to be two different classes of slow `get_new_block`.

**Class 1: `filter_block_txs` called**
```
2022-11-15T01:03:50.186Z DEBUG   lightningd: *#* entering get_new_block
2022-11-15T01:03:50.186Z DEBUG   lightningd: *#* calling add_tip
2022-11-15T01:03:50.187Z DEBUG   lightningd: *#* entering add_tip
2022-11-15T01:03:50.187Z DEBUG   lightningd: *#* calling wallet_block_add
2022-11-15T01:03:50.254Z DEBUG   lightningd: *#* wallet_block_add took 67 ms
2022-11-15T01:03:50.254Z DEBUG   lightningd: *#* calling topo_add_utxos
2022-11-15T01:03:50.444Z DEBUG   lightningd: *#* topo_add_utxos took 189 ms
2022-11-15T01:03:50.444Z DEBUG   lightningd: *#* calling topo_update_spends
2022-11-15T01:03:50.444Z DEBUG   lightningd: *#* entering topo_update_spends
2022-11-15T01:03:50.696Z DEBUG   lightningd: *#* calling wallet_utxoset_get_spent
2022-11-15T01:03:50.697Z DEBUG   lightningd: *#* wallet_utxoset_get_spent took 1 ms
2022-11-15T01:03:50.697Z DEBUG   lightningd: *#* calling gossipd_notify_spends
2022-11-15T01:03:50.697Z DEBUG   lightningd: *#* gossipd_notify_spends took 0 ms
2022-11-15T01:03:50.698Z DEBUG   lightningd: *#* topo_update_spends took 253 ms
2022-11-15T01:03:50.698Z DEBUG   lightningd: *#* topo_update_spends took 253 ms
2022-11-15T01:03:50.698Z DEBUG   lightningd: *#* calling filter_block_txs
2022-11-15T01:05:34.393Z DEBUG   lightningd: *#* filter_block_txs took 103694 ms
2022-11-15T01:05:34.393Z DEBUG   lightningd: *#* calling block_map_add
2022-11-15T01:05:34.393Z DEBUG   lightningd: *#* block_map_add took 0 ms
2022-11-15T01:05:34.393Z DEBUG   lightningd: *#* add_tip took 104205 ms
2022-11-15T01:05:34.393Z DEBUG   lightningd: *#* add_tip took 104205 ms
2022-11-15T01:05:34.395Z DEBUG   lightningd: *#* calling notify_block_added
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* notify_block_added took 16 ms
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* calling try_extend_tip
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* entering try_extend_tip
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* calling bitcoind_getrawblockbyheight
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* bitcoind_getrawblockbyheight took 0 ms
2022-11-15T01:05:34.414Z DEBUG   lightningd: *#* try_extend_tip took 0 ms
2022-11-15T01:05:34.415Z DEBUG   lightningd: *#* try_extend_tip took 1 ms
2022-11-15T01:05:34.417Z DEBUG   lightningd: *#* get_new_block took 104229 ms
```

**Class 2: `rebroadcast_txs` called**
```
2022-11-14T12:36:18.670Z DEBUG   lightningd: *#* entering get_new_block
2022-11-14T12:36:18.670Z DEBUG   lightningd: *#* calling updates_complete
2022-11-14T12:36:18.670Z DEBUG   lightningd: *#* entering updates_complete
2022-11-14T12:36:18.670Z DEBUG   lightningd: *#* calling watch_topology_changed
2022-11-14T12:36:18.866Z DEBUG   lightningd: *#* watch_topology_changed took 195 ms
2022-11-14T12:36:18.866Z DEBUG   lightningd: *#* calling notify_new_block
2022-11-14T12:36:18.889Z DEBUG   lightningd: *#* notify_new_block took 23 ms
2022-11-14T12:36:18.889Z DEBUG   lightningd: *#* calling rebroadcast_txs
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* rebroadcast_txs took 26417 ms
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* calling next_topology_timer
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* next_topology_timer took 0 ms
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* updates_complete took 26636 ms
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* updates_complete took 26636 ms
2022-11-14T12:36:45.307Z DEBUG   lightningd: *#* get_new_block took 26636 ms
```

With this information in hand, my next step will be to push my timing debugs down into `filter_block_txs` and `rebroadcast_txs` to see why *they're* so slow.

**Comment by whitslack** [comment] 2022-11-15 11:03
`filter_block_txs` is spending essentially all of its time in calls to `we_broadcast`:
```
2022-11-15T11:00:13.868Z DEBUG   lightningd: *#* entering filter_block_txs
2022-11-15T11:00:13.868Z DEBUG   lightningd: *#* entering loop over b->full_txs
2022-11-15T11:01:17.340Z DEBUG   lightningd: *#* loop over b->full_txs took 63470 ms
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* did 3517 outer, 7133 inner loop iterations
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent     12 ms in bitcoin_tx_input_get_txid
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent      5 ms in txowatch_hash_get
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent      0 ms in wallet_transaction_add
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent      0 ms in txowatch_fire
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent     62 ms in txfilter_match
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent      0 ms in wallet_extract_owned_outputs
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent      1 ms in watching_txid
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent  63349 ms in we_broadcast
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* spent     11 ms in txwatch_inform
2022-11-15T11:01:17.341Z DEBUG   lightningd: *#* calling tal_free(b->full_txs)
2022-11-15T11:01:17.496Z DEBUG   lightningd: *#* tal_free(b->full_txs) took 155 ms
2022-11-15T11:01:17.496Z DEBUG   lightningd: *#* calling tal_free(b->txids)
2022-11-15T11:01:17.502Z DEBUG   lightningd: *#* tal_free(b->txids) took 3 ms
2022-11-15T11:01:17.507Z DEBUG   lightningd: *#* filter_block_txs took 63638 ms
```
You might think it's strange that `we_broadcast` is taking so much time since it's a very simple function that linearly scans the `outgoing_txs` list for a given `txid`. Well, the `outgoing_txs` list is enormous and apparently getting bigger all the time. And this explains why `rebroadcast_txs` is taking a long time too.
```
2022-11-15T11:01:39.310Z DEBUG   lightningd: *#* entering rebroadcast_txs
2022-11-15T11:01:39.310Z DEBUG   lightningd: *#* entering loop over topo->outgoing_txs
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 13381 ms
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* did 122649 loop iterations
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* spent  13365 ms in wallet_transaction_height
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* spent      0 ms in tal_strdup
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* spent      0 ms in tal_arr_expand
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* calling broadcast_remainder
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* broadcast_remainder took 0 ms
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* rebroadcast_txs took 13382 ms
```
The loop in `rebroadcast_txs` iterates over the `outgoing_txs` list. You can see in the above log that this loop made 122649 iterations. This means there were 122649 elements in the `outgoing_txs` list at that time. In fact, the list grows quite rapidly, as evidenced in successive runs of `rebroadcast_txs` since node startup:
```
2022-11-15T09:48:14.243Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 4 ms
2022-11-15T09:48:14.243Z DEBUG   lightningd: *#* did 28 loop iterations
--
2022-11-15T10:02:27.104Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 2199 ms
2022-11-15T10:02:27.104Z DEBUG   lightningd: *#* did 21071 loop iterations
--
2022-11-15T10:05:33.956Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 2985 ms
2022-11-15T10:05:33.956Z DEBUG   lightningd: *#* did 29352 loop iterations
--
2022-11-15T10:13:52.379Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 4886 ms
2022-11-15T10:13:52.379Z DEBUG   lightningd: *#* did 45743 loop iterations
--
2022-11-15T10:32:49.576Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 8924 ms
2022-11-15T10:32:49.576Z DEBUG   lightningd: *#* did 79810 loop iterations
--
2022-11-15T10:36:49.018Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 9327 ms
2022-11-15T10:36:49.018Z DEBUG   lightningd: *#* did 85889 loop iterations
--
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 13381 ms
2022-11-15T11:01:52.692Z DEBUG   lightningd: *#* did 122649 loop iterations
```
This bit of `chaintopology.c` looks highly suspect:
https://github.com/ElementsProject/lightning/blob/fda3904d8c4d657985568f34444b3f59b2527aae/lightningd/chaintopology.c#L209-L212
The transaction is added to the `outgoing_txs` list blindly without checking whether it's already present in the list. Frankly that should be a *set*, not a list, shouldn't it? :thinking:

**Comment by cdecker** [comment] 2022-11-15 12:40
Good investigation, that looks like something we should (and can) optimize quite easily:

 - Skip transactions that are already marked as confirmed
 - Do not add transactions blindly to the list
 - Use a better lookup (`htable` to easily locate transactions of interest rather than having a quadratic algo

**Comment by cdecker** [comment] 2022-11-15 14:29
With the exception of the first point (we don't keep confirmed txs in the list after all), these proposals have been implemented in #5715

**Comment by whitslack** [comment] 2022-11-15 20:53
Testing now.

**Comment by whitslack** [comment] 2022-11-16 03:02
#5715 resolves this issue. The `outgoing_txs` htable still appears to be monotonically increasing in size (never shrinking), but it's a tiny trickle now.
```
2022-11-16T01:35:26.499Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 3 ms
2022-11-16T01:35:26.499Z DEBUG   lightningd: *#* did 25 loop iterations
--
2022-11-16T01:45:27.015Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 4 ms
2022-11-16T01:45:27.015Z DEBUG   lightningd: *#* did 36 loop iterations
--
2022-11-16T01:59:30.472Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 4 ms
2022-11-16T01:59:30.472Z DEBUG   lightningd: *#* did 36 loop iterations
--
2022-11-16T02:21:06.882Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 6 ms
2022-11-16T02:21:06.882Z DEBUG   lightningd: *#* did 37 loop iterations
--
2022-11-16T02:46:51.739Z DEBUG   lightningd: *#* loop over topo->outgoing_txs took 4 ms
2022-11-16T02:46:51.739Z DEBUG   lightningd: *#* did 37 loop iterations
```

`filter_block_txs` is behaving nicely now:
```
2022-11-16T02:46:51.245Z DEBUG   lightningd: *#* entering filter_block_txs
2022-11-16T02:46:51.245Z DEBUG   lightningd: *#* entering loop over b->full_txs
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* loop over b->full_txs took 24 ms
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* did 2905 outer, 6057 inner loop iterations
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in bitcoin_tx_input_get_txid
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      1 ms in txowatch_hash_get
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in wallet_transaction_add
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in txowatch_fire
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent     17 ms in txfilter_match
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in wallet_extract_owned_outputs
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in watching_txid
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in we_broadcast
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* spent      0 ms in txwatch_inform
2022-11-16T02:46:51.270Z DEBUG   lightningd: *#* calling tal_free(b->full_txs)
2022-11-16T02:46:51.351Z DEBUG   lightningd: *#* tal_free(b->full_txs) took 80 ms
2022-11-16T02:46:51.353Z DEBUG   lightningd: *#* calling tal_free(b->txids)
2022-11-16T02:46:51.355Z DEBUG   lightningd: *#* tal_free(b->txids) took 0 ms
2022-11-16T02:46:51.356Z DEBUG   lightningd: *#* filter_block_txs took 111 ms
```

@cdecker: Ship it! :rocket:

**Closed** 2022-11-18 12:39 UTC
