### ISSUE TITLE
Crash when attempting to connect to lnd node

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/lightning#396] opened 2017-12-01 16:07 UTC
Happens consistently.

7b20226a736f6e727063223a2022322e30222c2020226572726f7222203a2022686f7374206c6e642e626974726566696c6c2e636f6d3a39373335206e6f742076616c6964222c2022696422203a20226c696768746e696e672d636c692d323334313922207d0a
+70.018892994 lightning_gossipd(23263):DEBUG: TRACE: req: type WIRE_GOSSIPCTL_PEER_ADDRHINT len 38
+70.018959724 lightningd(23254):jcon fd 15:DEBUG: Closing (Bad file descriptor)
+70.019015884 lightning_gossipd(23263):DEBUG: TRACE: req: type WIRE_GOSSIPCTL_REACH_PEER len 35
+70.019075152 lightning_gossipd(23263):DEBUG: TRACE: Can't open 0 socket for 029bc664f7a44356b0add76acf585c1e7e8185fbe23971e7d51ab43f149ae7899a (Protocol not supported), giving up
+134.852067598 lightningd(23254):INFO: Connected json input
+134.852097414 lightningd(23254):jcon fd 15:IO-IN: 7b20226d6574686f6422203a2022636f6e6e656374222c2022696422203a20226c696768746e696e672d636c692d3233343733222c2022706172616d7322203a
+134.852107667 lightningd(23254):jcon fd 15:IO-IN: 205b2022303239626336363466376134343335366230616464373661636635383563316537653831383566626532333937316537643531616234336631343961
+134.852117733 lightningd(23254):jcon fd 15:IO-IN: 653738393961222c202235322e31382e36312e35303a39373335225d207d
+134.852313627 lightning_gossipd(23263):DEBUG: TRACE: req: type WIRE_GOSSIPCTL_PEER_ADDRHINT len 42
+134.852344435 lightning_gossipd(23263):DEBUG: TRACE: req: type WIRE_GOSSIPCTL_REACH_PEER len 35
+134.943773446 lightning_gossipd(23263):DEBUG: TRACE: Connected out for 029bc664f7a44356b0add76acf585c1e7e8185fbe23971e7d51ab43f149ae7899a
+134.943886308 lightning_gossipd(23263):DEBUG: TRACE: Initiator: Act 1
+134.943949382 lightning_gossipd(23263):DEBUG: TRACE: Initiator: Act 2
+135.035738538 lightning_gossipd(23263):DEBUG: TRACE: Initiator: Act 3
+135.127079848 lightning_gossipd(23263):INFO: UPDATE WIRE_GOSSIP_PEER_CONNECTED
+135.127192496 lightning_gossipd(23263):INFO: UPDATE WIRE_GOSSIP_PEER_CONNECTED
+135.127323177 lightningd(23254):jcon fd 15:DEBUG: Success
+135.127428453 lightningd(23254):BROKEN: FATAL SIGNAL 6 RECEIVED
+135.138623300 lightningd(23254):BROKEN: backtrace: lightningd/log.c:440 (log_crash) 0x40f7a0
+135.138666435 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc809b4af
+135.138679813 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc809b428
+135.138694841 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc809d029
+135.138707477 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc8093bd6
+135.138718406 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc8093c81
+135.139079718 lightningd(23254):BROKEN: backtrace: lightningd/jsonrpc.c:404 (command_success) 0x40c66c
+135.140076650 lightningd(23254):BROKEN: backtrace: lightningd/peer_control.c:317 (connect_succeeded) 0x415ae6
+135.140096099 lightningd(23254):BROKEN: backtrace: lightningd/peer_control.c:630 (peer_connected) 0x4165e4
+135.140329702 lightningd(23254):BROKEN: backtrace: lightningd/gossip_control.c:84 (gossip_msg) 0x4076c3
+135.140736933 lightningd(23254):BROKEN: backtrace: lightningd/subd.c:480 (sd_msg_read) 0x42250f
+135.140752686 lightningd(23254):BROKEN: backtrace: lightningd/subd.c:316 (read_fds) 0x421eea
+135.140976263 lightningd(23254):BROKEN: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x4548a0
+135.140990561 lightningd(23254):BROKEN: backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x455377
+135.141001324 lightningd(23254):BROKEN: backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x4553b5
+135.141186909 lightningd(23254):BROKEN: backtrace: ccan/ccan/io/poll.c:305 (io_loop) 0x456c73
+135.141457526 lightningd(23254):BROKEN: backtrace: lightningd/lightningd.c:334 (main) 0x40e218
+135.141472492 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x7f5cc808682f
+135.141486416 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0x4030f8
+135.141493779 lightningd(23254):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff

**Comment by rustyrussell** [comment] 2017-12-02 23:04
Consistent?  That seems really weird since this is a simple test.

1.  Do you have complete crash.log?
2.  Does it still happen after 'make distclean'?

**Comment by instagibbs** [comment] 2017-12-03 19:26
Issue went away, I'll make sure to capture logs and try the make distclean next time it happens.

**Comment by cdecker** [comment] 2017-12-04 09:22
Just tried to connect to that node myself, it seems to work. For future reference it's 029bc664f7a44356b0add76acf585c1e7e8185fbe23971e7d51ab43f149ae7899a@52.18.61.50@9735.

**Comment by rustyrussell** [comment] 2018-02-14 04:32
Closing due to age and lack or reproduction.

**Closed by rustyrussell** 2018-02-14 04:32 UTC
