### ISSUE TITLE
endrawtx exit 25, gave error code: -25?error message:?Missing inputs?

### ISSUE THREAD

**Issue by valuead** [ElementsProject/lightning#1750] opened 2018-07-25 07:34 UTC
0e721920
2018-07-25T07:33:16.956Z lightningd(19070): sendrawtx exit 25, gave error code: -25?error message:?Missing inputs?
2018-07-25T07:33:16.956Z lightningd(19070): Broadcasting tx 0200000000010115a422f698cc1a3695326bfdcdfacb8887a50d9adb0e0c5af4d2c41e8ceea4de00000000000027d48001909d070000000000220020c4ebfe2b221933b2365b75642668e053df6f2b93a5b0a35b7b23288d4fc00d8f0400483045022100e0ceb134d561bb8a7580396f98785f5ff14145195b89b18c243bb032222b9691022077a7459397ca4b7a2533b8bdf31aa081a87e07eb6b5213ff260b047dc96987fa0147304402201e0da41d4e58b5f887ca12294a687857974a169d459b8622c3e6206d06f0d8030220371531b5b3da6dac5cd92411e9aec90534ebc439e7a6957a444e6a80b236789f01475221022c0e786c27e48e1cad9420bc960b06cfedf372f580bbb9b8b0948700e827bdab2103695949e83b90e4be33f2477a187be7cca8b9c89df8497ba4dee20c6a78bf2e7252ae0e721920: 25 error code: -25?error message:?Missing inputs?![screen shot 2018-07-25 at 11 31 08 am](https://user-images.githubusercontent.com/9205462/43189052-5a54cc66-8ffe-11e8-8815-b89a6bceda87.png)

**Comment by cdecker** [comment] 2018-07-25 13:37
Duplicate of #767

**Closed by cdecker** 2018-07-25 13:37 UTC
