### ISSUE TITLE
Stuck transaction 

### ISSUE THREAD

**Issue by MrTheSoulz** [ElementsProject/lightning#7149] opened 2024-03-15 11:35 UTC
Hello, i've been struggling to get rid of a transaction that got stuck and never reached mempool. I force closed it after a week of waiting to see if it would make it into mempool. Now it has been stuck at "AWAITING_UNILATERAL" for more then a week.

```
{
         "id": "0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266",
         "connected": false,
         "num_channels": 1,
         "features": "800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000808252a1",
         "channels": [
            {
               "state": "AWAITING_UNILATERAL",
               "scratch_txid": "f571088e3e45f85adf928e7a573bd7b8dc2f6e4d8e734ab6507b3eca35df88fc",
               "last_tx_fee_msat": 1996000,
               "feerate": {
                  "perkw": 2758,
                  "perkb": 11032
               },
               "direction": 1,
               "channel_id": "1c803f0ec713d6e70a2b2cd942ac9c0fb44f92abefa51b7448be9559cf8e56a7",
               "funding_txid": "a7568ecf5995be48741ba5efab924fb40f9cac42d92c2b0ae7d613c70e3f801c",
               "funding_outnum": 0,
               "close_to_addr": "bc1qs37c0p6rh5dfa9nm42vyr7uqazugdu7qd23d0x",
               "close_to": "0014847d878743bd1a9e967baa9841fb80e8b886f3c0",
               "private": false,
               "opener": "local",
               "closer": "local",
               "alias": {
                  "local": "7230408x4766966x34389"
               },
               "features": [
                  "option_static_remotekey"
               ],
               "funding": {
                  "local_funds_msat": 149430000,
                  "remote_funds_msat": 0,
                  "pushed_msat": 0
               },
               "to_us_msat": 149430000,
               "min_to_us_msat": 149430000,
               "max_to_us_msat": 149430000,
               "total_msat": 149430000,
               "fee_base_msat": 1000,
               "fee_proportional_millionths": 10,
               "dust_limit_msat": 546000,
               "max_total_htlc_in_msat": 18446744073709551615,
               "their_reserve_msat": 1494000,
               "our_reserve_msat": 1494000,
               "spendable_msat": 142045000,
               "receivable_msat": 0,
               "minimum_htlc_in_msat": 0,
               "minimum_htlc_out_msat": 1,
               "maximum_htlc_out_msat": 147936000,
               "their_to_self_delay": 144,
               "our_to_self_delay": 144,
               "max_accepted_htlcs": 30,
               "state_changes": [
                  {
                     "timestamp": "2024-03-05T10:15:13.710Z",
                     "old_state": "CHANNELD_AWAITING_LOCKIN",
                     "new_state": "CHANNELD_SHUTTING_DOWN",
                     "cause": "user",
                     "message": "User or plugin invoked close command"
                  },
                  {
                     "timestamp": "2024-03-05T10:24:37.057Z",
                     "old_state": "CHANNELD_SHUTTING_DOWN",
                     "new_state": "AWAITING_UNILATERAL",
                     "cause": "user",
                     "message": "Forcibly closed by `close` command timeout"
                  }
               ],
               "status": [
                  "Loaded from database"
               ],
               "in_payments_offered": 0,
               "in_offered_msat": 0,
               "in_payments_fulfilled": 0,
               "in_fulfilled_msat": 0,
               "out_payments_offered": 0,
               "out_offered_msat": 0,
               "out_payments_fulfilled": 0,
               "out_fulfilled_msat": 0,
               "htlcs": []
            }
         ]
      },
```
when i try to force close it using:
 ```
 bitcoin-lightning-cli.sh close 0217890e3aad8d35bc054f43acc00084b25229ecff0ab68debd82883ad65ee8266 10
```
       
 i get the error:
 ```
 {
   "code": -1,
   "message": "Peer has no active channel"
}
```

Doing some googling i've found theres' supossed to be a command "dev-forget-channel" but i cant seem to be able to enable it. I think i have the developer flag set, when i execute "help" i get:
```
...
=== developer ===

dev-listaddrs [bip32_max_index]
    Show addresses list up to derivation {index} (default is the last bip32 index)

dev-rescan-outputs 
    Synchronize the state of our funds with bitcoind

---
```
but dev-forget-channel is not listed and trying it results in:
```
{
   "code": -32601,
   "message": "Unknown command 'dev-forget-channel'"
}
```

I opened a Issue on the docker repo to try and get some help, but so far no luck. Is this command still valid? if so is it what i should use and could i get some help enabling it?

Issue on the docker repo:
https://github.com/btcpayserver/btcpayserver-docker/issues/884
(Contains information on how i tried to enable developer mode)

Thanks!

**Comment by cdecker** [comment] 2024-03-17 12:30
The funding transaction apparently never confirmed, since I can't find it on the blockchain. This means that it was just created with too little fees, causing it to drop from the mempool of most nodes, and never confirming. It also means that after 2 weeks the outputs were marked as unreserved again, and ready to be spent, and the peer was allowed to forget about the channel.

So the conclusion is: no funds ever left your wallet, there is no close going on, and you likely already allocated the funds somewhere else.

Be sure you understand the effects of `dev-forget-channel` especially as to how you need to ensure the funding TX never ends up confirming (double spend it if it hasn't already been). Then you need to start the developer mode in CLN v24.02 onwards add the `--developer` flag, before that version you'll have to recompile with `./configure --enable-developer && make`.

**Closed by cdecker** 2024-03-17 12:30 UTC
Labels: cause::highfee
