### ISSUE TITLE
Handle escaping in JSONRPC parser and CLI client

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#607] opened 2018-01-15 07:48 UTC
Two bugs:

1. `lightning-cli` doesn't properly escape special characters when encoding JSON strings.

   ```bash
   $ lightning-cli invoice 100 1 'test"test'
   lightning-cli: Non-object response ''

   # lightningd logs
   Invalid token in json input: '{ "method" : "invoice", "id" : "lightning-cli-3209", "params" : [ 100, 1, "test"test"] }'
   ```

2. Even when escaped on the client side, `lightningd` doesn't properly parse JSON with escaped characters.

   ```bash
   $ lightning-cli invoice 100 1 'test\"test'
   lightning-cli: Non-object response ''

   # lightningd logs
   Invalid token in json input: '{ "method" : "invoice", "id" : "lightning-cli-3616", "params" : [ 100, 1, "test\"test"] }'
   ```

**Comment by ZmnSCPxj** [comment] 2018-01-15 10:17
Possible duplicate of #387

**Comment by cdecker** [comment] 2018-03-07 20:45
Closing as a duplicate of #387

**Closed by cdecker** 2018-03-07 20:45 UTC
