### ISSUE TITLE
Lightning Payment is taking Ages - Error 206 

### ISSUE THREAD

**Issue by realcryptominer** [ElementsProject/lightning#1135] opened 2018-02-28 13:10 UTC
I have installed LN Testnet on Linux VPS - Ubuntu 16.04 successfully.
Both testnet bitcoind and LN are synchronized with the current block height.

The channel is successfully opened and have 10,000 satoshis in it. 

However, when I first time tried to bought starblocks coffee with it, it gave me error 206 which is too high network fees. The default is set to 0.5%.

So I changed the fees to 1% and boom... I was able to buy the starbucks coffee yesterday night first time.

However, it was my first and last time.

Since then I am unable to buy the coffee. The payment is stucked and hanged now.

I have screen recorded everything. Here is the YouTube video link of this issue. Its just 3 mins video.

https://youtu.be/YTsQffWooP8

Kindly help me to buy starblocks coffee!

**Comment by cdecker** [comment] 2018-02-28 20:42
Can you provide us with the logs? Starting `lightningd` with the `--log-level=debug` option should give you a pretty good idea what's going on. Usually when it hangs like this it's attempting multiple routes.

**Comment by realcryptominer** [comment] 2018-03-01 02:58
Yes sure... I have started lightning with debug loglevel and this time it shows error 205 instead 206. Probably because the previous channel has been closed.

https://youtu.be/1iQHlkBVmP0

**Comment by realcryptominer** [comment] 2018-03-01 03:35
Okk so I have now connected with the same peer and opened and funded the new channel.

cli/lightning-cli connect 0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31@77.251.249.36:9735

cli/lightning-cli fundchannel 0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31 10000

This is the node which has set fees more than default fees 0.5%. I have again funded the channel and the channel is active now.

See the following video please.

https://youtu.be/LVNuK-vW2JA

**Comment by cdecker** [comment] 2018-03-01 13:56
That log is rather noisy, you can `dev-fail` channels 7 and 8, they'll not recover. Stopping the video sometimes shows a lot of `UNKNOWN_NEXT_PEER` which indicates that your client tried to use a channel that was closed, or forgotten. On testnet that is sadly a common occasion, and the existence of `dev-forget-channel` and some nodes not pruning their network view isn't making this any easier. 

Probably we need to increase the disable timeout for channels with temporary failures. @ZmnSCPxj am I correct in assuming that `UNKNOWN_NEXT_PEER` is a permanent failure that removes the edge from the network forever? If not, I think it should be.

Also @realcryptominer it'd be much easier if you started `lightningd` as follows:

```
lightningd/lightningd --log-level=debug --network=testnet |& logfile.txt
```

That'll create a `logfile.txt` that you can share by posting to pastebin or gist.

**Comment by ZmnSCPxj** [comment] 2018-03-01 14:03
`WIRE_UNKNOWN_NEXT_PEER` is  `PERM|10`, so it is indeed a permanent error.  It is a channel-level error (node-level errors have a `NODE` bit set), so only the specific channel is failed.  Permanent errors are handled as below:

https://github.com/ElementsProject/lightning/blob/cb6820d44504430d971ae604c3d02b81862c4c1f/gossipd/routing.c#L1212-L1226

**Comment by ZmnSCPxj** [comment] 2019-06-13 05:34
Is this issue still relevant? I believe #1153 is a duplicate of this, and #1153 has been resolved, so will close "soon".

**Closed** 2019-06-17 04:04 UTC
Labels: json-rpc, pending-fix-confirmation
