### ISSUE TITLE
txprepare destinationAddress:all slow 1 "[\"yourOutpoint\"]" sends everything to the change address

### ISSUE THREAD

**Issue by gabridome** [ElementsProject/lightning#4258] opened 2020-12-04 08:09 UTC
### Issue and Steps to Reproduce
I have tried to use `txprepare` to send the whole amount of one UTXO to and address of my personal wallet.

I have used the syntax on the subject:
```
lightning-cli txprepare myPersonalWalletAddress:all slow 1 "[\"nodeOutpoint\"]"

{
   "unsigned_tx": "0200000......",
   "txid": "cd5..."
}
bitcoin-cli decoderawtransaction 020000...
{
  "txid": "cd5...",
  "hash": ".....",
  "version": 2,
  "size": 82,
  "vsize": 82,
  "weight": 328,
  "locktime": 659783,
  "vin": [
    {
      "txid": "fkkb...",
      "vout": 1,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 4294967293
    }
  ],
  "vout": [
    {
      "value": 0.0029888929,
      "n": 0,
      "scriptPubKey": {
        "asm": "0 8...",
        "hex": "00...",
        "reqSigs": 1,
        "type": "witness_v0_keyhash",
        "addresses": [
          "bc1...." <<<<<<<<<<<<<<<<<<<<< not myPersonalWalletDestinationAddress
        ]
      }
    }
  ]
}

```
The destination address in the output is one of the change addresses of my node.

### `getinfo` output
```
{
   "id": "02....",
   "alias": "mynode",
   "color": "27ckhs",
   "num_peers": 0,
   "num_pending_channels": 0,
   "num_active_channels": 0,
   "num_inactive_channels": 0,
   "address": [
      {
         "type": "torv3",
         "address": "onionaddress.onion",
         "port": 9735
      }
   ],
   "binding": [
      {
         "type": "ipv4",
         "address": "127.0.0.1",
         "port": 9735
      }
   ],
   "version": "v0.9.2",
   "blockheight": 659883,
   "network": "bitcoin",
   "msatoshi_fees_collected": 838,
   "fees_collected_msat": "838msat",
   "lightning-dir": "/home/username/.lightning/bitcoin"
}
```

**Comment by cdecker** [comment] 2020-12-04 11:06
I have reproduced this and fixed it in a branch: https://github.com/cdecker/lightning/tree/issue-4258

Just want to check whether this also solves #4238, since the broken array syntax looks pretty much the same.

**Comment by gabridome** [comment] 2020-12-04 11:18
So, if I understand this well, the problem is due to the fact:

1. That I didn't enclose the output address and the amount i in square brackets
2. That the software, instead of giving a parsing error, has sent the whole amount to a change address.

The right syntax should be:

```
lightning-cli txprepare "[\"myPersonalWalletAddress:all\"]" slow 1 "[\"nodeOutpoint\"]"
```
Writing this just anyone who maybe experiencing the same problem.

**Comment by cdecker** [comment] 2020-12-04 13:47
> The right syntax should be:
> 
> ```
> lightning-cli txprepare "[\"myPersonalWalletAddress:all\"]" slow 1 "[\"nodeOutpoint\"]"
> ```
> 
> Writing this just anyone who maybe experiencing the same problem.

I'm afraid that is also not quite correct, though with #4259 this would get caught and would return an error message. I allowed myself to fix up your example, so future users can find it easily.

**Comment by cdecker** [comment] 2020-12-04 13:51
If you're interested, the fix is in https://github.com/ElementsProject/lightning/pull/4259/commits/4274985ea39d8e209a4d01988e64d49095d3e3a9:

Malformed arguments would get interpreted as a zero-length array (`tok->type == JSMN_STRING -> tok->size = 0`) and therefore we would create a tx with 0 desired outputs, leaving just the change output as observed.

**Comment by gabridome** [comment] 2020-12-04 13:58
so:
```
lightning-cli txprepare "{[\"myPersonalWalletAddress:all\"]}" slow 1 "[\"nodeOutpoint\"]"
```
or
```
lightning-cli txprepare "{[\"myPersonalWalletAddress\":\"all\"]}" slow 1 "[\"nodeOutpoint\"]"
```
?
I would opt for the second.

**Closed** 2020-12-08 20:26 UTC
