### ISSUE TITLE
JSONRPC does not accept numeric message ids

### ISSUE THREAD

**Issue by shesek** [ElementsProject/lightning#948] opened 2018-02-07 18:18 UTC
Some recent update made lightningd's JSONRPC server stop accepting numeric message ids. This broke compatibility with [BHB's lightning-client-js](https://github.com/BHBNETWORK/lightning-client-js), which (a fork of) is also used in Lightning Charge.

```
--> { "method": "listinvoices", "params": [], "id": 1 }
<-- { "jsonrpc": "2.0",  "error" : { "code" : -32600, "message" : Expected string/primitive for id }, "id" : null }

--> { "method": "listinvoices", "params": [], "id": "1" }
<-- { "jsonrpc": "2.0", "result" : { "invoices" : [  ] }, "id" : "1" }

**Comment by rustyrussell** [comment] 2018-02-07 22:52
I can't reproduce this :(

The 'Expected string/primitive' message is correct: we accept either a string or a primitive (eg. number) as id.  That hasn't changed.

I tested by sending this exact string (in case there was something else weird about the order), and indeed, got the expected result:

```
{ "jsonrpc": "2.0", "result" : { "invoices" : 
	[  ] }, "id" : 1 }
```

If this is reproducible, it's easy to patch lightnignd to report what it thinks it saw as 'id'...

**Comment by isghe** [comment] 2018-02-08 00:16
please define if `id` should be a number or a string; mixing the definition between number and string, for sure will be a disaster.

**Comment by ZmnSCPxj** [comment] 2018-02-08 01:22
@isghe the [JSON RPC 2.0 spec](http://www.jsonrpc.org/specification) itself allows `id` to be either a number or string:

>**id**<br>
>An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null and Numbers SHOULD NOT contain fractional parts

**Comment by shesek** [comment] 2018-02-09 14:00
I have a lightningd binary that I can definitely reproduce this against, but re-building from source appears to resolve it. Is there a way to tell which commit my binary was compiled from? (the version reported by lightningd refers to the commit back when v0.5.2 was tagged)

**Comment by cdecker** [comment] 2018-02-09 14:03
`lightning-cli getinfo` will tell you the commit that it was built with in the `version`.

**Comment by shesek** [comment] 2018-02-09 16:14
`getinfo` returns `v0.5.2-2016-11-21-1886-gb3d4e16`, but I'm unable to find the `gb3d4e16` commit.

**Comment by cdecker** [comment] 2018-02-09 16:36
That'd be b3d4e16 the `g` prefix is just to indicate a git commit. It's only a 3 day old commit, but we had a few changes to the JSON-RPC parsing.

**Comment by shesek** [comment] 2018-02-10 11:44
Oops, you're of course correct, the `g` prefix had me confused.

I'm able to reproduce this against my existing binaries that report being built from b3d4e161b5b361bb0b86fb35530d994908412633, but not when re-building from b3d4e161b5b361bb0b86fb35530d994908412633.

My binaries and a [reproduction script](https://gist.githubusercontent.com/shesek/e7e1587082768e407e228c0ebb4d9014/raw/26aac4e73f4cec546313cd1d56f2cce1f1a20172/test.sh) are available at https://gist.github.com/e7e1587082768e407e228c0ebb4d9014

```bash
$ git clone https://gist.github.com/e7e1587082768e407e228c0ebb4d9014.git && cd e7e1587082768e407e228c0ebb4d9014 && ./test.sh

...

+ bitcoind -regtest -datadir=/tmp/tmp.m5b9QqDUTT/bitcoin
+ sleep 2
+ ./lightningd --network=regtest --bitcoin-datadir=/tmp/tmp.m5b9QqDUTT/bitcoin --lightning-dir=/tmp/tmp.m5b9QqDUTT/lightning --log-file=debug.log
2018-02-10T11:38:37.104Z lightningd(11800): Creating configuration directory /tmp/tmp.m5b9QqDUTT/lightning
+ echo '{"id":1,"method":"getinfo","params":[]}'
+ nc -q 1 -U /tmp/tmp.m5b9QqDUTT/lightning/lightning-rpc
{ "jsonrpc": "2.0",  "error" : { "code" : -32600, "message" : Expected string/primitive for id }, "id" : null }
+ echo '{"id":"1","method":"getinfo","params":[]}'
+ nc -q 1 -U /tmp/tmp.m5b9QqDUTT/lightning/lightning-rpc
{ "jsonrpc": "2.0", "result" : { "id" : "0234cf540c238d7e5dc9a789abb5843b623178f1cf38307cca3b9bea9d2c814238", "port" : 9735, "address" : 
        [  ], "version" : "v0.5.2-2016-11-21-1886-gb3d4e16", "blockheight" : 0, "network" : "regtest" }, "id" : "1" }

```

**Comment by cdecker** [comment] 2018-02-10 13:22
Tried to bisect this for fun, but going back to December 1. doesn't reproduce this issue, so probably it was introduced and fixed somewhere inbetween.

I'm tempted to just close this issue.

**Comment by cdecker** [comment] 2018-02-14 18:30
The pending multirpc PR #994 explicitly tests for numeric IDs, so I think we can close this since we can't reproduce it.

**Closed by cdecker** 2018-02-14 18:30 UTC
