### ISSUE TITLE
WIRE_FINAL_EXPIRY_TOO_SOON error after doing 50+ sendpay

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#224] opened 2017-08-22 21:04 UTC
I have things setup to mostly automatically establish connection and for a test have a simplistic single channel at a time, serial sendpay loop.

Basically, it iterates:

client node: gets rhash
client node: sendpay to rhash
host node: receives payment and sends new rhash

It completes each payment lightning fast :)

until it gets the final expiry too soon error. Maybe I am not setting some parameter, but I dont see anywhere that I can set anything other than "delay", which I havent changed and is using the default value of 10. In any case, I think default operation should allow as many sendpays to be called as quickly as possible. In my case, there is a few network hops between each sendpay

here is the last of the printouts on the client side:
lightningd(31433): Sending 100000000 over 1 hops to deliver 100000000
lightningd_channel(31609): REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
lightningd_channel(31609): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
sendpay rhash.(9fff95f734cc8db69f6115f9a6668555bcbbea9ee5d90512a8055558c584fdbb) 0.00100000 to [{"id":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc","channel":"65939:1:0","msatoshi":100000000,"delay":10}] -> {"preimage":"3442df50c57d11d9e7f18ac7a751754561abd6e3fb1377d6aed0fc99b74245e3"} preimage.3442df50c57d11d9e7f18ac7a751754561abd6e3fb1377d6aed0fc99b74245e3
hostrhash update.(d87bb61b1cb03e93e5a3f64ca2a76f4383ee6346910d46d6d999df8d1c1eda81)
client onechop.({"method":"onechip","label":"03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821_68","sender":"6e8cfb1dbe5d5c23e42e29debf80fdbf62ec3e6de0f87f76d8dbf82745f2c51e","peerid":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc","hostrhash":["d87bb61b1cb03e93e5a3f64ca2a76f4383ee6346910d46d6d999df8d1c1eda81"],"pubkeys":["ff2f8ea2846a92e84d9afe6de34c40571ba78575cb27f57539e7ee586d264223"],"LN_port":9735,"chipsize":100000,"hostip":"127.0.0.1","hostid":"02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc"})
lightningd(31433): Sending 100000000 over 1 hops to deliver 100000000
lightningd_channel(31609): REPLY WIRE_CHANNEL_OFFER_HTLC_REPLY with 0 fds
lightningd_channel(31609): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(31609): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd(31433): peer 02779b57b66706778aa1c7308a817dc080295f3c2a6af349bb1114b8be328c28dc: htlc 69 failed from 0th node with code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)

on the host side:
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd(8990): Resolving invoice '03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821_68' with HTLC 68
completed! {"label":"03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821_68","rhash":"9fff95f734cc8db69f6115f9a6668555bcbbea9ee5d90512a8055558c584fdbb","msatoshi":100000000,"complete":true}
rhash.({"rhash":"d87bb61b1cb03e93e5a3f64ca2a76f4383ee6346910d46d6d999df8d1c1eda81"}) -> d87bb61b1cb03e93e5a3f64ca2a76f4383ee6346910d46d6d999df8d1c1eda81
updated rhash for 03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821 to d87bb61b1cb03e93e5a3f64ca2a76f4383ee6346910d46d6d999df8d1c1eda81
delpaidinvoice.(03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821_68) -> ({"label":"03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821_68","rhash":"9fff95f734cc8db69f6115f9a6668555bcbbea9ee5d90512a8055558c584fdbb","msatoshi":100000000})
lightningd_channel(9160): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd(8990): peer 03b03efcf647e6dd48b949e5b1f7e9e064257a5c48c2d56b1334b283b48338f821: failed htlc 69 code 0x0011 (WIRE_FINAL_EXPIRY_TOO_SOON)
lightningd_channel(9160): UPDATE WIRE_CHANNEL_SENDING_COMMITSIG
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_REVOKE
lightningd_channel(9160): UPDATE WIRE_CHANNEL_GOT_COMMITSIG

If the WIRE_FINAL_EXPIRY_TOO_SOON can be made to go away, I think I can get 1000 sendpay done in a few seconds once all the debug prints are taken out. I didnt time the above sequence, but it did 68 payments pretty much as soon as the channel was ready

**Comment by cdecker** [comment] 2017-08-29 14:16
I think this is a duplicate of #233, closing this for now. Feel free to re-open if it is a distinct issue.

**Closed by cdecker** 2017-08-29 14:16 UTC
