### ISSUE TITLE
Crash: "Cannot allocate memory"

### ISSUE THREAD

**Issue by kallerosenbaum** [ElementsProject/lightning#855] opened 2018-01-31 07:39 UTC
### Issue and Steps to Reproduce

Two nights in a row I've had a crash with "Cannot allocate memory".  Snippet from console:

```lightning_gossipd(29538): TRACE: Received channel_announcement for channel 1260955:16:0
lightning_gossipd(29538): UPDATE WIRE_GOSSIP_GET_TXOUT
lightning_gossipd(29538): TRACE: Received channel_update for channel 1260955:16:0(0)
lightning_gossipd(29538): TRACE: Replacing existing update
bitcoin-cli exec failed: Cannot allocate memory
lightningd(29530): bitcoin-cli exec failed: Cannot allocate memory
Log dumped in crash.log
lightningd(29530): FATAL SIGNAL 6 RECEIVED
lightningd(29530): backtrace: lightningd/log.c:436 (log_crash) 0x41071c
lightningd(29530): backtrace: (null):0 ((null)) 0x7fe0c82b44af
lightningd(29530): backtrace: (null):0 ((null)) 0x7fe0c82b4428
lightningd(29530): backtrace: (null):0 ((null)) 0x7fe0c82b6029
lightningd(29530): backtrace: lightningd/log.c:525 (fatal) 0x410b56
lightningd(29530): backtrace: lightningd/bitcoind.c:182 (next_bcli) 0x403d2b
lightningd(29530): backtrace: lightningd/bitcoind.c:242 (start_bitcoin_cli) 0x40400a
lightningd(29530): backtrace: lightningd/bitcoind.c:551 (process_getblock) 0x404f12
lightningd(29530): backtrace: lightningd/bitcoind.c:159 (bcli_finished) 0x403c3f
lightningd(29530): backtrace: ccan/ccan/io/poll.c:183 (destroy_conn) 0x45a1b6
lightningd(29530): backtrace: ccan/ccan/io/poll.c:189 (destroy_conn_close_fd) 0x45a1d6
lightningd(29530): backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x464401
lightningd(29530): backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x4648b2
lightningd(29530): backtrace: ccan/ccan/tal/tal.c:509 (tal_free) 0x464cc5
lightningd(29530): backtrace: ccan/ccan/io/io.c:443 (io_close) 0x458e3e
lightningd(29530): backtrace: ccan/ccan/io/poll.c:309 (io_loop) 0x45a5b4
lightningd(29530): backtrace: lightningd/lightningd.c:347 (main) 0x40f161
lightningd(29530): backtrace: (null):0 ((null)) 0x7fe0c829f82f
lightningd(29530): backtrace: (null):0 ((null)) 0x403168
lightningd(29530): backtrace: (null):0 ((null)) 0xffffffffffffffff
Fatal signal 6. 0x410802 log_crash
	lightningd/log.c:462
0x7fe0c82b44af ???
	???:0
0x7fe0c82b4428 ???
	???:0
0x7fe0c82b6029 ???
	???:0
0x410b56 fatal
	lightningd/log.c:525
0x403d2b next_bcli
	lightningd/bitcoind.c:182
0x40400a start_bitcoin_cli
	lightningd/bitcoind.c:242
0x404f12 process_getblock
	lightningd/bitcoind.c:551
0x403c3f bcli_finished
	lightningd/bitcoind.c:159
0x45a1b6 destroy_conn
	ccan/ccan/io/poll.c:183
0x45a1d6 destroy_conn_close_fd
	ccan/ccan/io/poll.c:189
0x464401 notify
	ccan/ccan/tal/tal.c:240
0x4648b2 del_tree
	ccan/ccan/tal/tal.c:400
0x464cc5 tal_free
	ccan/ccan/tal/tal.c:509
0x458e3e io_close
	ccan/ccan/io/io.c:443
0x45a5b4 io_loop
	ccan/ccan/io/poll.c:309
0x40f161 main
	lightningd/lightningd.c:347
0x7fe0c829f82f ???
	???:0
0x403168 ???
	???:0
0xffffffffffffffff ???
	???:0
Log dumped in crash.log
lightning_channeld: Writing out status 32768 len 44: Broken pipe
Aborted (core dumped)
```
### `free` output *without* lightningd running

```
$ free
              total        used        free      shared  buff/cache   available
Mem:        4037352     2115884      124880       38212     1796588     1653654
Swap:       2357400     1188004     1169396
```

### `getinfo` output
$ cli/lightning-cli getinfo
```
{ "id" : "0259f20b1ef9eedd0f7b4d415c0d365059099bfa29021f6190401ba8e8e5abc1ad", "port" : 9735, "address" : 
	[ 
		{ "type" : "ipv4", "address" : "46.59.13.35", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-1704-gd36fa33", "blockheight" : 1260939, "network" : "testnet" }
```

### `listpeers` output

```
$ cli/lightning-cli listpeers
{ "peers" : 
	[ 
		{ "id" : "0260a9711694672b4fd55add53def7cdbd18d767f455b052e0ff63e651548c6c56", "connected" : false, "channels" : 
			[ 
				{ "state" : "CHANNELD_AWAITING_LOCKIN", "funding_txid" : "579fb4678e9c962a08bc6329d4d6ee7a958a9204f7eadb52ef511155a2e227c7", "msatoshi_to_us" : 100000000, "msatoshi_total" : 100000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "02359ebb074ce6a511a55e8375e7b0170b65133fec3eba46319adfc4402d220d3e", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "02359ebb074ce6a511a55e8375e7b0170b65133fec3eba46319adfc4402d220d3e", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "03fdefe424b480b7d8f1a0b3dcb20f637ee56f330ee311402ad37049ebebce03f1", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "0231eee2441073c86d38f6085aedaf2bb7ad3d43af4c0e2669c1edd1a7d566ce31", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_OUR_UNILATERAL", "short_channel_id" : "1260899:89:0", "funding_txid" : "123c8b6fdea4df97093a7861d0e683ee8dcfec2efeaff2c22eef91aba8aaf88a", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "03656a4c737b98b7ca5ad1ee4b411f5929f53552018b3925f341bcfa1c832287b7", "connected" : true, "netaddr" : 
			[ "104.131.26.124:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1260899:87:1", "funding_txid" : "a448f6a802f9493282f7a4b0ad19daaa70f8d35c1b8eeeb22342bf3762cf4035", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "03f113414ebdc6c1fb0f33c99cd5a1d09dd79e7fdf2468cf1fe1af6674361695d2", "connected" : true, "netaddr" : 
			[ "5.102.147.62:9735" ], "channels" : 
			[ 
				{ "state" : "CHANNELD_NORMAL", "owner" : "lightning_channeld", "short_channel_id" : "1260899:88:0", "funding_txid" : "4e738d8adc12bf95cacae857135a3313de761f485e44a80576cf8071e405ab81", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "03f84fc72e22d73db3c1130af5d20195f70d94e341be58c42b789ada2220938988", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03f84fc72e22d73db3c1130af5d20195f70d94e341be58c42b789ada2220938988", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03d9607671bbb5521a0ab59ade726277125934aae89ba278db4916f99179a5466b", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03987a79dfd6089487cc8b3611a94fda8e21a927cd0a0cf381193491b62a7e7190", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03987a79dfd6089487cc8b3611a94fda8e21a927cd0a0cf381193491b62a7e7190", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03987a79dfd6089487cc8b3611a94fda8e21a927cd0a0cf381193491b62a7e7190", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "02f6725f9c1c40333b67faea92fd211c183050f28df32cac3f9d69685fe9665432", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "id" : "0298d0c6987e2e64451c7f723e15aff4dfca92f0e3973d214e206257abb0d1dd55", "connected" : false, "channels" : 
			[ 
				{ "state" : "ONCHAIND_OUR_UNILATERAL", "short_channel_id" : "1259064:38:0", "funding_txid" : "6413f240480f3a74eaa8ca7813fca838b4d360133f4c6073b7e80949266e1aa5", "msatoshi_to_us" : 1000000000, "msatoshi_total" : 1000000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 6, "max_accepted_htlcs" : 483 } ] }, 
		{ "id" : "03d9607671bbb5521a0ab59ade726277125934aae89ba278db4916f99179a5466b", "connected" : false, "channels" : 
			[ 
				{ "state" : "OPENINGD", "dust_limit_satoshis" : 0, "max_htlc_value_in_flight_msat" : 0, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "to_self_delay" : 0, "max_accepted_htlcs" : 0 } ] }, 
		{ "state" : "GOSSIPING", "id" : "0326f926fcfe6f5bdcbeaed831ac479d9e41b399078f9eff2575c3ae25164c9c5a", "netaddr" : 
			[ "[::ffff:188.166.104.224]:39200" ], "connected" : true, "owner" : "lightning_gossipd" }, 
		{ "state" : "GOSSIPING", "id" : "034725c18651ace5f07ee7e958473726f38b2af123eefbd127124134c2c0e11263", "netaddr" : 
			[ "[::ffff:52.88.168.137]:35354" ], "connected" : true, "owner" : "lightning_gossipd" } ] }
```

**Comment by cdecker** [comment] 2018-01-31 10:40
When does this happen? Right after startup or after running for a while?

**Comment by kallerosenbaum** [comment] 2018-01-31 11:41
The crash.log file says:

```
+51649.018391906 lightning_gossipd(29538):DEBUG: TRACE: Ignoring node announcement, it's outdated.
+51649.018668493 lightning_gossipd(29538):DEBUG: TRACE: Received channel_announcement for channel 1260955:16:0
+51649.018837291 lightning_gossipd(29538):DEBUG: UPDATE WIRE_GOSSIP_GET_TXOUT
+51649.018946645 lightning_gossipd(29538):DEBUG: TRACE: Received channel_update for channel 1260955:16:0(0)
+51649.019046525 lightning_gossipd(29538):DEBUG: TRACE: Replacing existing update
+51649.095508983 lightningd(29530):BROKEN: bitcoin-cli exec failed: Cannot allocate memory
+51651.734253564 lightningd(29530):BROKEN: FATAL SIGNAL 6 RECEIVED
+51652.035214770 lightningd(29530):BROKEN: backtrace: lightningd/log.c:436 (log_crash) 0x41071c
+51652.050589363 lightningd(29530):BROKEN: backtrace: (null):0 ((null)) 0x7fe0c82b44af
+51652.050630882 lightningd(29530):BROKEN: backtrace: (null):0 ((null)) 0x7fe0c82b4428
+51652.050638762 lightningd(29530):BROKEN: backtrace: (null):0 ((null)) 0x7fe0c82b6029
+51652.050649344 lightningd(29530):BROKEN: backtrace: lightningd/log.c:525 (fatal) 0x410b56
```

Not sure what the unit of the timestamp is, but I guess it's ~14 hours (51652/3600)..

**Comment by kallerosenbaum** [comment] 2018-01-31 16:39
Currently running it using `valgrind --tool=massif` in case it happens again. Not sure that's the best option, so please let me know if something else is preferable.

**Comment by cdecker** [comment] 2018-01-31 18:33
You can probably try `dev-memleak` and see what the largest allocations are.

**Comment by kallerosenbaum** [comment] 2018-02-08 07:40
This hasn't happened again. It happened two nights in a row and not again since this bug report. The above info is all I have. I'm OK with you closing this.

**Comment by cdecker** [comment] 2018-02-09 14:26
Hm, that's strange. I'll close this for now, but please reopen should it happen again. Thank you very much for the report @kallerosenbaum

**Closed by cdecker** 2018-02-09 14:26 UTC
Labels: needinfo

**Comment by alecalve** [comment] 2018-03-04 15:43
I had this happen to me too several times now:

```
bitcoin-cli exec failed: Cannot allocate memory
Log dumped in crash.log
Fatal signal 6. 0x4153fb log_crash
        lightningd/log.c:530
0x7fb3c783e4af ???
        ???:0
0x7fb3c783e428 ???
        ???:0
0x7fb3c7840029 ???
        ???:0
0x41574f fatal
        lightningd/log.c:593
0x4040e0 next_bcli
        lightningd/bitcoind.c:213
0x4043c3 start_bitcoin_cli
        lightningd/bitcoind.c:275
0x405669 bitcoind_getblockhash_
        lightningd/bitcoind.c:682
0x4073a0 try_extend_tip
        lightningd/chaintopology.c:437
0x436408 timer_expired
        common/timeout.c:40
0x413ac0 main
        lightningd/lightningd.c:413
0x7fb3c782982f ???
        ???:0
0x4033f8 ???
        ???:0
0xffffffffffffffff ???
        ???:0
Log dumped in crash.log
```

Logs:

```
2018-03-04T15:39:36.532Z lightningd(21557): subd lightning_channeld failed: Cannot allocate memory
2018-03-04T15:39:36.532Z lightningd(21557): 0271d98f7dfe66198f045690f552a9126abb0aa1585f0061854e780b7e08e6dccd chan #9: Could not subdaemon channel: Cannot allocate memory
2018-03-04T15:39:36.532Z lightningd(21557): 0271d98f7dfe66198f045690f552a9126abb0aa1585f0061854e780b7e08e6dccd chan #9: Peer transient failure in CHANNELD_NORMAL: Failed to subdaemon channel
2018-03-04T15:39:36.533Z lightning_gossipd(21574): Forgetting remote peer 0271d98f7dfe66198f045690f552a9126abb0aa1585f0061854e780b7e08e6dccd
2018-03-04T15:39:36.533Z lightning_gossipd(21574): req: type WIRE_GOSSIPCTL_REACH_PEER len 35
2018-03-04T15:39:36.539Z lightning_gossipd(21574): Connected out for 0271d98f7dfe66198f045690f552a9126abb0aa1585f0061854e780b7e08e6dccd
2018-03-04T15:39:36.548Z lightning_gossipd(21574): peer_out WIRE_INIT
2018-03-04T15:39:36.549Z lightningd(21557): bitcoin-cli exec failed: Cannot allocate memory
2018-03-04T15:39:44.909Z lightningd(21557): FATAL SIGNAL 6 RECEIVED
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: lightningd/log.c:504 (log_crash) 0x415315
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: (null):0 ((null)) 0x7fb3c783e4af
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: (null):0 ((null)) 0x7fb3c783e428
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: (null):0 ((null)) 0x7fb3c7840029
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: lightningd/log.c:593 (fatal) 0x41574f
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: lightningd/bitcoind.c:213 (next_bcli) 0x4040e0
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: lightningd/bitcoind.c:275 (start_bitcoin_cli) 0x4043c3
2018-03-04T15:39:45.844Z lightningd(21557): backtrace: lightningd/bitcoind.c:682 (bitcoind_getblockhash_) 0x405669
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: lightningd/chaintopology.c:437 (try_extend_tip) 0x4073a0
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: common/timeout.c:40 (timer_expired) 0x436408
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: lightningd/lightningd.c:413 (main) 0x413ac0
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: (null):0 ((null)) 0x7fb3c782982f
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: (null):0 ((null)) 0x4033f8
2018-03-04T15:39:45.845Z lightningd(21557): backtrace: (null):0 ((null)) 0xffffffffffffffff
```

**Comment by alecalve** [comment] 2018-03-04 15:46
FYI, the version that crashed was running f32ebb7dcad5903bfecbc01176f0ea7d67946532

**Comment by kallerosenbaum** [comment] 2019-01-11 08:04
This happened again (now using v0.6.2). Full crash log attached. Others have also reported this since the bug was closed, so I'm afraid this is still a thing. Should we reopen? 

```
+428476.276999509 lightningd(18428):BROKEN: bitcoin-cli exec failed: Cannot allocate memory
+428476.690962808 lightningd(18428):BROKEN: FATAL SIGNAL 6 (version v0.6.2)
+428476.691021730 lightningd(18428):BROKEN: backtrace: common/daemon.c:42 (crashdump) 0x434d40
+428476.691035451 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0x7f5cbeb634af
+428476.691047047 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0x7f5cbeb63428
+428476.691056613 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0x7f5cbeb65029
+428476.691066277 lightningd(18428):BROKEN: backtrace: lightningd/log.c:614 (fatal) 0x419e69
+428476.691075986 lightningd(18428):BROKEN: backtrace: lightningd/bitcoind.c:234 (next_bcli) 0x4045cc
+428476.691087645 lightningd(18428):BROKEN: backtrace: lightningd/bitcoind.c:301 (start_bitcoin_cli) 0x40490b
+428476.691098742 lightningd(18428):BROKEN: backtrace: lightningd/bitcoind.c:730 (bitcoind_getblockhash_) 0x405c69
+428476.691111642 lightningd(18428):BROKEN: backtrace: lightningd/chaintopology.c:696 (try_extend_tip) 0x4085ea
+428476.691122825 lightningd(18428):BROKEN: backtrace: common/timeout.c:39 (timer_expired) 0x43b9ac
+428476.691133764 lightningd(18428):BROKEN: backtrace: lightningd/lightningd.c:755 (main) 0x418132
+428476.691144572 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0x7f5cbeb4e82f
+428476.691154142 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0x403618
+428476.691162730 lightningd(18428):BROKEN: backtrace: (null):0 ((null)) 0xffffffffffffffff
```
[crash.log.20190109194617.gz](https://github.com/ElementsProject/lightning/files/2748575/crash.log.20190109194617.gz)

**Comment by kallerosenbaum** [comment] 2019-01-11 08:09
@cdecker I can't find out how to run `dev-memleak` that you refered to in https://github.com/ElementsProject/lightning/issues/855#issuecomment-362027186, could you expand a bit on `dev-memleak`? Thanks.

**Comment by chrisguida** [comment] 2019-06-26 15:32
I am getting this error with c-lightning v0.7.0-397-g22600fa:

```2019-06-26T15:29:44.904Z lightningd(23534): bitcoin-cli exec failed: Cannot allocate memory
2019-06-26T15:29:44.999Z lightningd(23534): FATAL SIGNAL 6 (version v0.7.0-397-g22600fa)
2019-06-26T15:29:45.002Z lightningd(23534): backtrace: common/daemon.c:45 (send_backtrace) 0x563572e71ab2
2019-06-26T15:29:45.002Z lightningd(23534): backtrace: common/daemon.c:53 (crashdump) 0x563572e71afd
2019-06-26T15:29:45.002Z lightningd(23534): backtrace: (null):0 ((null)) 0x7fc3bf419f1f
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: (null):0 ((null)) 0x7fc3bf419e97
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: (null):0 ((null)) 0x7fc3bf41b800
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: lightningd/log.c:647 (fatal) 0x563572e5c4e5
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: lightningd/bitcoind.c:241 (next_bcli) 0x563572e4c295
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: lightningd/bitcoind.c:308 (start_bitcoin_cli) 0x563572e4c404
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: lightningd/bitcoind.c:684 (process_getblockhash_for_txout) 0x563572e4cb6a
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: lightningd/bitcoind.c:214 (bcli_finished) 0x563572e4c97b
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/io/poll.c:244 (destroy_conn) 0x563572e9f74c
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/io/poll.c:250 (destroy_conn_close_fd) 0x563572e9f76e
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/tal/tal.c:235 (notify) 0x563572ea72b3
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/tal/tal.c:397 (del_tree) 0x563572ea7317
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/tal/tal.c:481 (tal_free) 0x563572ea7874
2019-06-26T15:29:45.003Z lightningd(23534): backtrace: ccan/ccan/io/io.c:450 (io_close) 0x563572e9e46a
2019-06-26T15:29:45.004Z lightningd(23534): backtrace: ccan/ccan/io/poll.c:449 (io_loop) 0x563572e9fd36
2019-06-26T15:29:45.004Z lightningd(23534): backtrace: lightningd/lightningd.c:823 (main) 0x563572e5abe5
2019-06-26T15:29:45.004Z lightningd(23534): backtrace: (null):0 ((null)) 0x7fc3bf3fcb96
2019-06-26T15:29:45.004Z lightningd(23534): backtrace: (null):0 ((null)) 0x563572e4bbc9
2019-06-26T15:29:45.004Z lightningd(23534): backtrace: (null):0 ((null)) 0xffffffffffffffff```

**Comment by cdecker** [comment] 2019-06-29 15:25
Just wanted to clarify this a bit more: we are not crashing on the first of these errors, we will keep retrying for 1 minute, after which we report the error and bail out:

https://github.com/ElementsProject/lightning/blob/fc6de9443f4e2f18bbd53719d730e83b289f59c7/lightningd/bitcoind.c#L145-L155

The reason for this is that we are highly dependent on being able to talk to the bitcoin network, and if that connectivity is not guaranteed, we may be putting funds at risk. Crashing in this case is the strongest signal that something is wrong that we can give. I know the backtrace makes it look like it is a bug that can be addressed by adding more code, but it really should be an explicit call to action to the user to take a closer look at their setup. We are unlikely to stop erroring out and just stop outright, what we could do however is remove the backtrace which may be confusing people into thinking this is an unwanted crash.

**Comment by chrisguida** [comment] 2019-06-29 15:54
Thanks for the reply! This actually has to do with a memory leak in the bitcoin node I'm using, [sPRUNED](https://github.com/gdassori/spruned/issues/100), and has nothing to do with c-lightning. Apologies, and the error appears to be working as designed :)

**Comment by cdecker** [comment] 2019-06-29 16:01
@chrisguida no problem at all :+1:
