### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#701] opened 2018-01-21 16:56 UTC
I had a crash a few days ago.  I attached output.
stdout & stderr:
[output.txt](https://github.com/ElementsProject/lightning/files/1649934/output.txt)
file in .lightning:
[crash.log](https://github.com/ElementsProject/lightning/files/1649932/crash.log)

**Comment by Ulmo** [comment] 2018-01-21 16:59
Since there's no "git version" command that does what I think it should, I found a "git log" command and copied the top of that; maybe someone can trace that to what version this is:

commit fc151e10cdad4beb4b6a07f48117e30943af5d7d
Author: Rusty Russell <rusty@rustcorp.com.au>
Date:   Mon Jan 15 15:13:08 2018 +1030

    test_lightning.py: check error on too-large funding tx.
    
    Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>

**Comment by jb55** [comment] 2018-01-21 18:18
Make sure you have (at least) bitcoind v0.15.1.0

**Comment by Ulmo** [comment] 2018-01-26 03:30
Thank you.  I tend to build latest from git for bitcoin at the same time as lightning.

**Comment by cdecker** [comment] 2018-02-06 15:44
This was most likely caused by `bitcoind` not returning a valid response to `estimatesmartfee`, which we were unable to parse, and thus preferred to crash the entire daemon. The call to `fatal` has since been removed and we are now more forgiving when parsing the response from `estimatesmartfee`. Should be fixed.

**Closed by cdecker** 2018-02-06 15:44 UTC
