### ISSUE TITLE
payments without an invoice (or partial payments)?

### ISSUE THREAD

**Issue by jl777** [ElementsProject/lightning#210] opened 2017-08-12 12:55 UTC
Probably not possible due to all the setup that is needed, but I want to setup a channel where the sender can determine how much to pay.

Since everything is based on a specific invoice, the receiver would need to issue N invoices to cover the max possible amount? Hopefully there is mechanism to issue a very large invoice and receive partial payment on it.

Maybe since the amount is specified in the route, it is as simple as changing the "msatoshi" value?

sorry for all the questions, just catching up with your cool tech!

**Comment by cdecker** [comment] 2017-08-12 13:19
No problem @jl777, always good to have a fresh set of eyes going through things to find stuff that needs improvement.

The "spontaneous payment"/donation use-case is definitely something we want to integrate, however since we need the recipient to atomically trigger the individual hops once it receives the transfer we need to keep the hash. We are brainstorming on the [spec wiki](https://github.com/lightningnetwork/lightning-rfc/wiki/Brainstorming#spontaneous-payments) (though admittedly it's still a bit vague) on how to do this, but I'm afraid it won't make it into spec v1.0. If you have a good idea on how to do this I'd like to invite you to participate in the discussion in the spec repo [lightningnetwork/lightning-rfc](https://github.com/lightningnetwork/lightning-rfc).

As for the changing of the amount, `lightningd` currently plays nice and returns what it perceives as a transfer that is too large/too small instead of just pocketing it. We can certainly add support for invoices that do not specify an amount later on.

**Comment by jl777** [comment] 2017-08-12 13:27
Why couldnt it just accept a "too small" amount, maybe by automatically issuing a new invoice that is an exact match.

It seems that would have minimal impact on the internals and allow the donation usecase immediately. Just make a very large invoice(s) and publish the rhashes for them. Then a donating node would randomly pick one of the rhashes, send a "too small" payment, which triggers an automatic invoice creation and automatic substitution of the new rhash for the one that was sent in. 

I guess the published rhashes would never actually be used, until someone made a full donation so it would even be able to be published on websites "donate to <rhash>"

Not sure if the auto-rhash substitution rises to a changing the spec level, but I can open an issue there for this if you think it is better there

**Comment by cdecker** [comment] 2017-08-12 13:33
The problem is that if any of the `rhash`es is reused for more than one payment then we might have a situation where an intermediate node knows the `preimage` of that `rhash`, so it could claim the amount without forwarding the payment to the intended recipient, basically pocketing the money itself. The problem is compounded by the fact that a potential sender can't just monitor to see which `rhash`es have been used because only nodes on the path that originally used that `rhash` will be aware of it.

`rhash` reuse is a really dangerous thing and we should avoid it at all costs.

**Comment by jl777** [comment] 2017-08-12 13:36
OK, so there does need to be a protocol change.

a sendpay with an actual rhash not specified, but rather a referenced rhash. and the actual rhash that is an exact match is returned. Then there is no reuse of rhash.

Or how about the sendpay gets an rhash returned for the actual rhash that was used and it is clear that it wont be the same rhash value if the amount sent is too small

**Comment by cdecker** [comment] 2017-08-12 13:48
Sorry, you lost me there. The requirements are as follows:

- The recipient needs to know the `preimage` of the `rhash` such that `rhash = Hash(preimage)`
- The sender needs to know a `rhash` for which the recipient knows the `preimage` to initiate the transfer
- The `rhash` must not be reused for multiple payments

Eventually we may swap out the hash for some other function (EC operation) that allows us to deterministically generate unique values for `rhash` for which we know the recipient knows the `preimage`, e.g., provide a signature for this HD key derived from your `node_id`, but all of this are protocol level discussions which we should move over to the spec repo.

**Comment by jl777** [comment] 2017-08-12 13:57
OK, I was not aware of these requirements. What is needed is a way for the sender to request an rhash for a specific payment amount. I will make an issue in the spec repo.

Unless you can use hash(sharedsecret + origrhash + newamount + unixtimestamp) as the new rhash

The idea is to have a generator rhash that is never actually used, other than to autocreate partial payment rhashes. Since the pubkeys are known for both parties, the sharedsecret is known only to the two parties, which I believe prevents anybody in the route from stealing it as they wont actually know the rhash used.

a timestamp field would need to be added to the sendpay, which would limit to one payment per second, which seems fine.

So, sendpay changed to have a timestamp and a derived rhash when the amount is not a perfect match.

**Comment by cdecker** [comment] 2017-08-12 14:05
Yep, that sounds about right. We have some space in the onion packet to stuff a random secret `paysecret` in that can be mixed into the preimage sort of like `rhash = Hash(paysecret || node_id)` and communicate all the necessary information that way. I should probably write that one up and see what people think about that.

Ok, moving the discussion to the spec repo, closing this issue for now.

**Closed by cdecker** 2017-08-12 14:05 UTC
Labels: enhancement
