### ISSUE TITLE
building with osx fails

### ISSUE THREAD

**Issue by gruve-p** [ElementsProject/lightning#6139] opened 2023-04-01 16:12 UTC
### Issue
Building on [v22.11.1](https://github.com/ElementsProject/lightning/releases/tag/v22.11.1) works fine
Building on [v23.02.2: CBDC Backing Layer III](https://github.com/ElementsProject/lightning/releases/tag/v23.02.2) fails

### Steps to Reproduce on macos 12
brew install wget autoconf automake libtool python@3.10 gmp gnu-sed gettext libsodium protobuf
ln -s /usr/local/Cellar/gettext/0.20.1/bin/xgettext /usr/local/opt
export PATH="/usr/local/opt:$PATH"
brew install sqlite
export LDFLAGS="-L/usr/local/opt/sqlite/lib"
export CPPFLAGS="-I/usr/local/opt/sqlite/include"

### `getinfo` output

2023-04-01T15:40:41.2270000Z In file included from plugins/sql.c:25:
2023-04-01T15:40:41.2271170Z plugins/sql-schema_gen.h:1:4: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2271870Z -n "{
2023-04-01T15:40:41.2272080Z    ^
2023-04-01T15:40:41.2275230Z plugins/sql-schema_gen.h:1:2: error: use of undeclared identifier 'n'
2023-04-01T15:40:41.2275890Z -n "{
2023-04-01T15:40:41.2276300Z  ^
2023-04-01T15:40:41.2277110Z plugins/sql-schema_gen.h:1:3: error: expected ';' after top level declarator
2023-04-01T15:40:41.2277610Z -n "{
2023-04-01T15:40:41.2277800Z   ^
2023-04-01T15:40:41.2277960Z   ;
2023-04-01T15:40:41.2278360Z plugins/sql-schema_gen.h:2:5: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2278730Z -n \"listchannels\":
2023-04-01T15:40:41.2278920Z     ^
2023-04-01T15:40:41.2279320Z plugins/sql-schema_gen.h:3:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2282850Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"channels\"],\"properties\":{\"channels\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"source\",\"destination\",\"short_channel_id\",\"direction\",\"public\",\"amount_msat\",\"message_flags\",\"channel_flags\",\"active\",\"last_update\",\"base_fee_millisatoshi\",\"fee_per_millionth\",\"delay\",\"htlc_minimum_msat\",\"features\"],\"properties\":{\"source\":{\"type\":\"pubkey\",\"\":\"\"},\"destination\":{\"type\":\"pubkey\",\"\":\"\"},\"short_channel_id\":{\"type\":\"short_channel_id\",\"\":\"\"},\"direction\":{\"type\":\"u32\",\"\":\"\"},\"public\":{\"type\":\"boolean\",\"\":\"\"},\"amount_msat\":{\"type\":\"msat\",\"\":\"\"},\"message_flags\":{\"type\":\"u8\",\"\":\"\"},\"channel_flags\":{\"type\":\"u8\",\"\":\"\"},\"active\":{\"type\":\"boolean\",\"\":\"\"},\"last_update\":{\"type\":\"u32\",\"\":\"\"},\"base_fee_millisatoshi\":{\"type\":\"u32\",\"\":\"\"},\"fee_per_millionth\":{\"type\":\"u32\",\"\":\"\"},\"delay\":{\"type\":\"u32\",\"\":\"\"},\"htlc_minimum_msat\":{\"type\":\"msat\",\"\":\"\"},\"\":{},\"htlc_maximum_msat\":{\"type\":\"msat\",\"\":\"\"},\"features\":{\"type\":\"hex\",\"\":\"\"}}}}}}-n ,\"listforwards\":
2023-04-01T15:40:41.2284850Z   ^
2023-04-01T15:40:41.2285350Z plugins/sql-schema_gen.h:4:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2291260Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"forwards\"],\"properties\":{\"forwards\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"in_channel\",\"in_msat\",\"status\",\"received_time\"],\"properties\":{\"in_channel\":{\"type\":\"short_channel_id\",\"\":\"\"},\"in_htlc_id\":{\"type\":\"u64\",\"\":\"\"},\"in_msat\":{\"type\":\"msat\",\"\":\"\"},\"status\":{\"type\":\"string\",\"enum\":[\"offered\",\"settled\",\"local_failed\",\"failed\"],\"\":\"\"},\"received_time\":{\"type\":\"number\",\"\":\"\"},\"out_channel\":{\"type\":\"short_channel_id\",\"\":\"\"},\"out_htlc_id\":{\"type\":\"u64\",\"\":\"\"},\"style\":{\"type\":\"string\",\"enum\":[\"legacy\",\"tlv\"],\"\":\"\"}},\"allOf\":[{\"if\":{\"required\":[\"out_msat\"]},\"then\":{\"additionalProperties\":false,\"required\":[\"fee_msat\",\"out_msat\",\"out_channel\"],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"fee_msat\":{\"type\":\"msat\",\"\":\"\"},\"out_msat\":{\"type\":\"msat\",\"\":\"\"}}},\"else\":{\"additionalProperties\":false,\"required\":[],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{}}}},{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"settled\",\"failed\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[\"resolved_time\"],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"resolved_time\":{\"type\":\"number\",\"\":\"\"}}},\"else\":{\"additionalProperties\":false,\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{}}}},{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"local_failed\",\"failed\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"failcode\":{\"type\":\"u32\",\"\":\"\"},\"failreason\":{\"type\":\"string\",\"\":\"\"}}},\"else\":{\"additionalProperties\":false,\"required\":[],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{}}}}]}}}}-n ,\"listhtlcs\":
2023-04-01T15:40:41.2294530Z   ^
2023-04-01T15:40:41.2294990Z plugins/sql-schema_gen.h:5:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2297870Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"htlcs\"],\"properties\":{\"htlcs\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"short_channel_id\",\"id\",\"expiry\",\"direction\",\"amount_msat\",\"payment_hash\",\"state\"],\"properties\":{\"short_channel_id\":{\"type\":\"short_channel_id\",\"\":\"\"},\"id\":{\"type\":\"u64\",\"\":\"\"},\"expiry\":{\"type\":\"u32\",\"\":\"\"},\"amount_msat\":{\"type\":\"msat\",\"\":\"\"},\"direction\":{\"type\":\"string\",\"enum\":[\"out\",\"in\"],\"\":\"\"},\"payment_hash\":{\"type\":\"hash\",\"\":\"\"},\"state\":{\"type\":\"string\",\"enum\":[\"SENT_ADD_HTLC\",\"SENT_ADD_COMMIT\",\"RCVD_ADD_REVOCATION\",\"RCVD_ADD_ACK_COMMIT\",\"SENT_ADD_ACK_REVOCATION\",\"RCVD_REMOVE_HTLC\",\"RCVD_REMOVE_COMMIT\",\"SENT_REMOVE_REVOCATION\",\"SENT_REMOVE_ACK_COMMIT\",\"RCVD_REMOVE_ACK_REVOCATION\",\"RCVD_ADD_HTLC\",\"RCVD_ADD_COMMIT\",\"SENT_ADD_REVOCATION\",\"SENT_ADD_ACK_COMMIT\",\"RCVD_ADD_ACK_REVOCATION\",\"SENT_REMOVE_HTLC\",\"SENT_REMOVE_COMMIT\",\"RCVD_REMOVE_REVOCATION\",\"RCVD_REMOVE_ACK_COMMIT\",\"SENT_REMOVE_ACK_REVOCATION\"],\"\":\"\"}}}}}}-n ,\"listinvoices\":
2023-04-01T15:40:41.2299720Z   ^
2023-04-01T15:40:41.2300160Z plugins/sql-schema_gen.h:6:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2304660Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"invoices\"],\"properties\":{\"invoices\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"label\",\"payment_hash\",\"status\",\"expires_at\"],\"properties\":{\"label\":{\"type\":\"string\",\"\":\"\"},\"description\":{\"type\":\"string\",\"\":\"\"},\"payment_hash\":{\"type\":\"hash\",\"\":\"\"},\"status\":{\"type\":\"string\",\"enum\":[\"unpaid\",\"paid\",\"expired\"],\"\":\"\"},\"expires_at\":{\"type\":\"u64\",\"\":\"\"},\"amount_msat\":{\"type\":\"msat\",\"\":\"\"},\"bolt11\":{\"type\":\"string\",\"\":\"\"},\"bolt12\":{\"type\":\"string\",\"\":\"\"},\"local_offer_id\":{\"type\":\"hash\",\"\":\"\"},\"invreq_payer_note\":{\"type\":\"string\",\"\":\"\"}},\"allOf\":[{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"paid\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[\"pay_index\",\"amount_received_msat\",\"paid_at\",\"payment_preimage\"],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"pay_index\":{\"type\":\"u64\",\"\":\"\"},\"amount_received_msat\":{\"type\":\"msat\",\"\":\"\"},\"paid_at\":{\"type\":\"u64\",\"\":\"\"},\"payment_preimage\":{\"type\":\"secret\",\"\":\"\"}}},\"else\":{\"additionalProperties\":false,\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{}}}}]}}}}-n ,\"listnodes\":
2023-04-01T15:40:41.2306980Z   ^
2023-04-01T15:40:41.2307440Z plugins/sql-schema_gen.h:7:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2312570Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"nodes\"],\"properties\":{\"nodes\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"nodeid\"],\"properties\":{\"nodeid\":{\"type\":\"pubkey\",\"\":\"\"},\"last_timestamp\":{\"type\":\"u32\",\"\":\"\"}},\"allOf\":[{\"if\":{\"required\":[\"last_timestamp\"]},\"then\":{\"additionalProperties\":false,\"required\":[\"nodeid\",\"last_timestamp\",\"alias\",\"color\",\"features\",\"addresses\"],\"properties\":{\"\":{},\"\":{},\"\":{},\"alias\":{\"type\":\"string\",\"\":\"\",\"maxLength\":32},\"color\":{\"type\":\"hex\",\"\":\"\",\"minLength\":6,\"maxLength\":6},\"features\":{\"type\":\"hex\",\"\":\"\"},\"addresses\":{\"type\":\"array\",\"\":\"\",\"items\":{\"type\":\"object\",\"required\":[\"type\",\"port\"],\"additionalProperties\":true,\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"dns\",\"ipv4\",\"ipv6\",\"torv2\",\"torv3\",\"websocket\"],\"\":\"\"},\"port\":{\"type\":\"u16\",\"\":\"\"}},\"if\":{\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"dns\",\"ipv4\",\"ipv6\",\"torv2\",\"torv3\"]}}},\"then\":{\"required\":[\"type\",\"address\",\"port\"],\"additionalProperties\":false,\"properties\":{\"\":{},\"\":{},\"address\":{\"type\":\"string\",\"\":\"\"}}},\"else\":{\"required\":[\"type\",\"port\"],\"additionalProperties\":false,\"properties\":{\"\":{},\"\":{}}}}}}},\"else\":{\"additionalProperties\":false,\"properties\":{\"\":{}}}},{\"if\":{\"required\":[\"option_will_fund\"]},\"then\":{\"additionalProperties\":true,\"required\":[\"option_will_fund\"],\"properties\":{\"option_will_fund\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"lease_fee_base_msat\",\"lease_fee_basis\",\"funding_weight\",\"channel_fee_max_base_msat\",\"channel_fee_max_proportional_thousandths\",\"compact_lease\"],\"properties\":{\"lease_fee_base_msat\":{\"type\":\"msat\",\"\":\"\"},\"lease_fee_basis\":{\"type\":\"u32\",\"\":\"\"},\"funding_weight\":{\"type\":\"u32\",\"\":\"\"},\"channel_fee_max_base_msat\":{\"type\":\"msat\",\"\":\"\"},\"channel_fee_max_proportional_thousandths\":{\"type\":\"u32\",\"\":\"\"},\"compact_lease\":{\"type\":\"hex\",\"\":\"\"}}}}}}]}}}}-n ,\"listoffers\":
2023-04-01T15:40:41.2324290Z   ^
2023-04-01T15:40:41.2325190Z plugins/sql-schema_gen.h:8:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2327050Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"offers\"],\"properties\":{\"offers\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"offer_id\",\"active\",\"single_use\",\"bolt12\",\"used\"],\"properties\":{\"offer_id\":{\"type\":\"hash\",\"\":\"\"},\"active\":{\"type\":\"boolean\",\"\":\"\"},\"single_use\":{\"type\":\"boolean\",\"\":\"\"},\"bolt12\":{\"type\":\"string\",\"\":\"\"},\"used\":{\"type\":\"boolean\",\"\":\"\"},\"label\":{\"type\":\"string\",\"\":\"\"}}}}}}-n ,\"listpeers\":
2023-04-01T15:40:41.2328120Z   ^
2023-04-01T15:40:41.2328830Z plugins/sql-schema_gen.h:9:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2329350Z plugins/sql-schema_gen.h:10:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2329890Z plugins/sql-schema_gen.h:11:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2335030Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"added\":\"v23.05\",\"required\":[\"closedchannels\"],\"properties\":{\"closedchannels\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"channel_id\",\"opener\",\"private\",\"total_msat\",\"total_local_commitments\",\"total_remote_commitments\",\"total_htlcs_sent\",\"funding_txid\",\"funding_outnum\",\"leased\",\"final_to_us_msat\",\"min_to_us_msat\",\"max_to_us_msat\",\"close_cause\"],\"properties\":{\"peer_id\":{\"type\":\"pubkey\",\"\":\"\"},\"channel_id\":{\"type\":\"hash\",\"\":\"\"},\"short_channel_id\":{\"type\":\"short_channel_id\",\"\":\"\"},\"alias\":{\"type\":\"object\",\"required\":[],\"properties\":{\"local\":{\"type\":\"short_channel_id\",\"\":\"\"},\"remote\":{\"type\":\"short_channel_id\",\"\":\"\"}}},\"opener\":{\"type\":\"string\",\"enum\":[\"local\",\"remote\"],\"\":\"\"},\"closer\":{\"type\":\"string\",\"enum\":[\"local\",\"remote\"],\"\":\"\"},\"private\":{\"type\":\"boolean\",\"\":\"\"},\"channel_type\":{\"type\":\"object\",\"\":\"\",\"additionalProperties\":false,\"required\":[\"bits\",\"names\"],\"properties\":{\"bits\":{\"type\":\"array\",\"\":\"\",\"items\":{\"type\":\"u32\",\"\":\"\"}},\"names\":{\"type\":\"array\",\"\":\"\",\"items\":{\"type\":\"string\",\"enum\":[\"static_remotekey/even\",\"anchor_outputs/even\",\"anchors_zero_fee_htlc_tx/even\",\"scid_alias/even\",\"zeroconf/even\"],\"\":\"\"}}}},\"total_local_commitments\":{\"type\":\"u64\",\"\":\"\"},\"total_remote_commitments\":{\"type\":\"u64\",\"\":\"\"},\"total_htlcs_sent\":{\"type\":\"u64\",\"\":\"\"},\"funding_txid\":{\"type\":\"txid\",\"\":\"\"},\"funding_outnum\":{\"type\":\"u32\",\"\":\"\"},\"leased\":{\"type\":\"boolean\",\"\":\"\"},\"funding_fee_paid_msat\":{\"type\":\"msat\",\"\":\"\"},\"funding_fee_rcvd_msat\":{\"type\":\"msat\",\"\":\"\"},\"funding_pushed_msat\":{\"type\":\"msat\",\"\":\"\"},\"total_msat\":{\"type\":\"msat\",\"\":\"\"},\"final_to_us_msat\":{\"type\":\"msat\",\"\":\"\"},\"min_to_us_msat\":{\"type\":\"msat\",\"\":\"\"},\"max_to_us_msat\":{\"type\":\"msat\",\"\":\"\"},\"last_commitment_txid\":{\"type\":\"hash\",\"\":\"\"},\"last_commitment_fee_msat\":{\"type\":\"msat\",\"\":\"\"},\"close_cause\":{\"type\":\"string\",\"enum\":[\"unknown\",\"local\",\"user\",\"remote\",\"protocol\",\"onchain\"],\"\":\"\"}}}}}}-n ,\"listtransactions\":
2023-04-01T15:40:41.2338520Z   ^
2023-04-01T15:40:41.2339000Z plugins/sql-schema_gen.h:12:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2343380Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"transactions\"],\"properties\":{\"transactions\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"hash\",\"rawtx\",\"blockheight\",\"txindex\",\"locktime\",\"version\",\"inputs\",\"outputs\"],\"properties\":{\"hash\":{\"type\":\"txid\",\"\":\"\"},\"rawtx\":{\"type\":\"hex\",\"\":\"\"},\"blockheight\":{\"type\":\"u32\",\"\":\"\"},\"txindex\":{\"type\":\"u32\",\"\":\"\"},\"locktime\":{\"type\":\"u32\",\"\":\"\"},\"version\":{\"type\":\"u32\",\"\":\"\"},\"inputs\":{\"type\":\"array\",\"\":\"\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"txid\",\"index\",\"sequence\"],\"properties\":{\"txid\":{\"type\":\"txid\",\"\":\"\"},\"index\":{\"type\":\"u32\",\"\":\"\"},\"sequence\":{\"type\":\"u32\",\"\":\"\"},\"type\":{\"type\":\"string\",\"enum\":[\"theirs\",\"deposit\",\"withdraw\",\"channel_funding\",\"channel_mutual_close\",\"channel_unilateral_close\",\"channel_sweep\",\"channel_htlc_success\",\"channel_htlc_timeout\",\"channel_penalty\",\"channel_unilateral_cheat\"],\"\":\"\"},\"channel\":{\"type\":\"short_channel_id\",\"\":\"\"}}}},\"outputs\":{\"type\":\"array\",\"\":\"\",\"items\":{\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"index\",\"amount_msat\",\"scriptPubKey\"],\"properties\":{\"index\":{\"type\":\"u32\",\"\":\"\"},\"amount_msat\":{\"type\":\"msat\",\"\":\"\"},\"scriptPubKey\":{\"type\":\"hex\",\"\":\"\"},\"type\":{\"type\":\"string\",\"enum\":[\"theirs\",\"deposit\",\"withdraw\",\"channel_funding\",\"channel_mutual_close\",\"channel_unilateral_close\",\"channel_sweep\",\"channel_htlc_success\",\"channel_htlc_timeout\",\"channel_penalty\",\"channel_unilateral_cheat\"],\"\":\"\"},\"channel\":{\"type\":\"short_channel_id\",\"\":\"\"}}}}}}}}}-n ,\"listsendpays\":
2023-04-01T15:40:41.2346320Z   ^
2023-04-01T15:40:41.2346780Z plugins/sql-schema_gen.h:13:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2351090Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"payments\"],\"properties\":{\"payments\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"id\",\"payment_hash\",\"status\",\"groupid\",\"created_at\",\"amount_sent_msat\"],\"properties\":{\"id\":{\"type\":\"u64\",\"\":\"\"},\"groupid\":{\"type\":\"u64\",\"\":\"\"},\"partid\":{\"type\":\"u64\",\"\":\"\"},\"payment_hash\":{\"type\":\"hash\",\"\":\"\"},\"status\":{\"type\":\"string\",\"enum\":[\"pending\",\"failed\",\"complete\"],\"\":\"\"},\"amount_msat\":{\"type\":\"msat\",\"\":\"\"},\"destination\":{\"type\":\"pubkey\",\"\":\"\"},\"created_at\":{\"type\":\"u64\",\"\":\"\"},\"amount_sent_msat\":{\"type\":\"msat\",\"\":\"\"},\"label\":{\"type\":\"string\",\"\":\"\"},\"bolt11\":{\"type\":\"string\",\"\":\"\"},\"description\":{\"type\":\"string\",\"\":\"\"},\"bolt12\":{\"type\":\"string\",\"\":\"\"}},\"allOf\":[{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"complete\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[\"payment_preimage\"],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"payment_preimage\":{\"type\":\"secret\",\"\":\"\"}}}},{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"failed\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"erroronion\":{\"type\":\"hex\",\"\":\"\"}}}},{\"if\":{\"properties\":{\"status\":{\"type\":\"string\",\"enum\":[\"pending\"]}}},\"then\":{\"additionalProperties\":false,\"required\":[],\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{}}}}]}}}}-n ,\"bkpr-listaccountevents\":
2023-04-01T15:40:41.2353930Z   ^
2023-04-01T15:40:41.2354400Z plugins/sql-schema_gen.h:14:3: warning: missing terminating '"' character [-Winvalid-pp-token]
2023-04-01T15:40:41.2358860Z {\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"type\":\"object\",\"additionalProperties\":false,\"required\":[\"events\"],\"properties\":{\"events\":{\"type\":\"array\",\"items\":{\"type\":\"object\",\"additionalProperties\":true,\"required\":[\"account\",\"type\",\"tag\",\"credit_msat\",\"debit_msat\",\"currency\",\"timestamp\"],\"properties\":{\"account\":{\"type\":\"string\",\"\":\"\"},\"type\":{\"type\":\"string\",\"enum\":[\"onchain_fee\",\"chain\",\"channel\"],\"\":\"\"},\"tag\":{\"type\":\"string\",\"\":\"\"},\"credit_msat\":{\"type\":\"msat\",\"\":\"\"},\"debit_msat\":{\"type\":\"msat\",\"\":\"\"},\"currency\":{\"type\":\"string\",\"\":\"\"},\"timestamp\":{\"type\":\"u32\",\"\":\"\"}},\"allOf\":[{\"if\":{\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"chain\"]}}},\"then\":{\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"outpoint\":{\"type\":\"string\",\"\":\"\"},\"blockheight\":{\"type\":\"u32\",\"\":\"\"},\"origin\":{\"type\":\"string\",\"\":\"\"},\"payment_id\":{\"type\":\"hex\",\"\":\"\"},\"txid\":{\"type\":\"txid\",\"\":\"\"},\"description\":{\"type\":\"string\",\"\":\"\"}},\"required\":[\"outpoint\",\"blockheight\"],\"additionalProperties\":false}},{\"if\":{\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"onchain_fee\"]}}},\"then\":{\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"txid\":{\"type\":\"txid\",\"\":\"\"}},\"required\":[\"txid\"],\"additionalProperties\":false}},{\"if\":{\"properties\":{\"type\":{\"type\":\"string\",\"enum\":[\"channel\"]}}},\"then\":{\"properties\":{\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"\":{},\"fees_msat\":{\"type\":\"msat\",\"\":\"\"},\"is_rebalance\":{\"type\":\"boolean\",\"\":\"\"},\"payment_id\":{\"type\":\"hex\",\"\":\"\"},\"part_id\":{\"type\":\"u32\",\"\":\"\"}},\"additionalProperties\":false}}]}}}}-n ,\"bkpr-listincome\":
2023-04-01T15:40:41.2361690Z   ^
2023-04-01T15:40:41.2361890Z 17 warnings and 2 errors generated.
2023-04-01T15:40:41.2384000Z make: *** [plugins/sql.o] Error 1
2023-04-01T15:40:41.2396110Z rm external/x86_64-apple-darwin21.6.0/libwally-core-build/src/secp256k1/libsecp256k1.la
2023-04-01T15:40:41.2430620Z ##[error]Process completed with exit code 2.

**Comment by chrisguida** [comment] 2023-04-12 18:17
Duplicate of #6171 . Fixed by #6172 .

**Comment by vincenzopalazzo** [comment] 2023-04-12 18:23
Fixed by https://github.com/ElementsProject/lightning/pull/6172

Thanks @chrisguida

**Closed by vincenzopalazzo** 2023-04-12 18:23 UTC
