### ISSUE TITLE
Segmentation fault, running bitcoind on mainnet and lightningd on testnet

### ISSUE THREAD

**Issue by Head** [ElementsProject/lightning#583] opened 2018-01-12 23:10 UTC
Not quite sure if it's really a "bug", but at least it should somehow check the right network and not Segfault.
I was running bitcoind on mainnet and lightningd with `--network=testnet`. Then I connected using `cli/lightning-cli connect 02d28c3aac4b4f36746052a735831afbe65bc5698a7be5bd41b42fd1ddf2a1a358 45.63.87.131` and BAM:

lightningd(20780): Adding block 000000000000000000223055859dce9506a21368dee4d6f5591472ad53f82c90
lightningd(20780): Connected json input
lightning_gossipd(20789): TRACE: req: type WIRE_GOSSIPCTL_PEER_ADDRHINT len 42
lightning_gossipd(20789): TRACE: req: type WIRE_GOSSIPCTL_REACH_PEER len 35
lightningd(20780): Adding block 000000000000000000159ccd5cc2037cae25660ee109266c0ff2f8b0398f0c4a
lightning_gossipd(20789): TRACE: Connected out for 02d28c3aac4b4f36746052a735831afbe65bc5698a7be5bd41b42fd1ddf2a1a358
lightning_gossipd(20789): TRACE: Initiator: Act 1
lightning_gossipd(20789): TRACE: Initiator: Act 2
lightning_gossipd(20789): TRACE: Initiator: Act 3
lightning_gossipd(20789): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightning_gossipd(20789): UPDATE WIRE_GOSSIP_PEER_CONNECTED
lightningd(20780):jcon fd 14: Success
lightningd(20780):jcon fd 14: Closing (Bad file descriptor)
lightning_gossipd(20789): TRACE: req: type WIRE_GOSSIPCTL_HAND_BACK_PEER len 189
lightning_gossipd(20789): TRACE: hand_back_peer 02d28c3aac4b4f36746052a735831afbe65bc5698a7be5bd41b42fd1ddf2a1a358: now local again
lightningd(20780): Adding block 000000000000000000181b37f56af709ff480ee400a0c6e5c222fd4c2938cf15
lightningd(20780): Adding block 0000000000000000008b0f741e455fd34981c3922900d83030e3c2951d8e4f8f
lightningd(20780): Adding block 000000000000000000041438343a5a53711fb4b9b0897c653a84797e07a22333
lightning_gossipd(20789): TRACE: Received channel_announcement for channel 1194794:14:0
lightning_gossipd(20789): UPDATE WIRE_GOSSIP_GET_TXOUT
lightning_gossipd(20789): TRACE: Received channel_update for channel 1194794:14:0(0)
lightning_gossipd(20789): TRACE: Deferring update for pending channel 1194794:14:0(0)
lightning_gossipd(20789): TRACE: Received channel_update for channel 1194794:14:0(1)
lightning_gossipd(20789): TRACE: Deferring update for pending channel 1194794:14:0(1)
lightning_gossipd(20789): TRACE: Received channel_announcement for channel 1195299:5:0
lightning_gossipd(20789): UPDATE WIRE_GOSSIP_GET_TXOUT
lightning_gossipd(20789): TRACE: Received channel_update for channel 1195299:5:0(0)
lightning_gossipd(20789): TRACE: Deferring update for pending channel 1195299:5:0(0)
lightningd(20780): bitcoin-cli -testnet getblockhash 1194794: invalid blocknum?
lightningd(20780): FATAL SIGNAL 11 RECEIVED
Fatal signal 11. Log dumped in crash.log
Segmentation fault

**Comment by jb55** [comment] 2018-01-12 23:51
is your testnet node fully synced?

**Comment by cdecker** [comment] 2018-01-13 10:33
I ran into this problem as well when trying to run on mainnet yesterday, it seems that `gettxout` returns an empty result in some cases.

**Comment by Head** [comment] 2018-01-13 11:37
@jb55 my (pruned) mainnet bitcoin node is synced. Was not expecting anything to "work", but Segfaults shouldn't happen imho and could be a deeper laying bug.

@cdecker Do you know any mainnet node I could try to connect to? I didn't found ANY id & ip so I tried to connect to a testnet node (with my bitcoin mainnet - which I'm aware cannot work).

**Comment by cdecker** [comment] 2018-01-13 11:59
There's the mainnet.yalls.org node here 02eccebd9ed98f6d267080a58194dbe554a2b33d976eb95bb7c116d00fd64c4a13@45.77.7.202

**Comment by rustyrussell** [comment] 2018-01-16 01:14
This is caused by the same thing as #589 and was fixed in #604 

Thanks!

**Closed by rustyrussell** 2018-01-16 01:14 UTC
