### ISSUE TITLE
Long run of 8 days crash

### ISSUE THREAD

**Issue by Ulmo** [ElementsProject/lightning#1159] opened 2018-03-03 14:27 UTC
### Issue and Steps to Reproduce

Since one of my _lightningd_ ran for 8 days, I'm going to submit the crash for it, since it might have a different type of crash having run for so long.  

Here's the first and last 1,000 lines of the log file:
[longruncrash.txt](https://github.com/ElementsProject/lightning/files/1777536/longruncrash.txt)

### `getinfo` output
Please update template to say "getinfo output or started line in log file", since it gives the version number too and only it is available after crash.

2018-02-24T02:11:59.811Z lightningd(27864): Server started with public key 03a3c1fc0a489e2872a2afe8fa16c2714b5fe80d52d8c1ce8ecc4361a77391da82, alias Ionic.Release??? (color #03a3c1) and lightningd v0.5.2-2016-11-21-2092-g7c8883a

**Comment by cdecker** [comment] 2018-03-03 17:59
Still likely to be a duplicate of #1072.

**Closed by cdecker** 2018-03-03 17:59 UTC
