### ISSUE TITLE
How to pay to nonadvertised node - could not find a route

### ISSUE THREAD

**Issue by dslingo** [ElementsProject/lightning#2206] opened 2018-12-29 22:53 UTC
### Issue and Steps to Reproduce
Situation is:
1. trying to pay invoice generated by wallet app, invoice is on 1 sat
2. wallet app is configured to connect to one of the node of LN (in my case zigzag.io)
3. i have own node, configured, visible on LN map, two peers zigzag.io and rompert.com
4. to both peers channels fundchannel opened 300000sat and 12000sat
5. command executed: ./lightning-cli pay {bolt11 of invoice}, getting error "could not find a route"
6. i tryed to pay invoices generated by store.blockstream.com and get succeded
7. also if i try to pay invoice generated by my node but on wallet app it works fine!

Only difference i see between those that payee id from wallet app is not visible in LN,
getroute gives "could not find a route". Getroute executed on payee id from store.blockstream.com invoice gives routing results. Looks like id of wallet app is not advertized in LN network.
So how to pay this kind of invoice?
I just can add that the same invoice from wallet app is successfully payed from https://lightning-roulette.com/.
Also bolt11 structure generated by wallet app contains "fallbacks" field that contains BC wallet address. Mayby here is the secret?

**Comment by charltonh** [comment] 2019-01-02 07:01
I think I'm seeing the same problem in a different way.
I have been sending sats from my LBW android wallet to my CL and now I want to send those sats back to LBW.  In this case there is a channel directly connected from LBW to CL, but the LBW node is not on any of the gossip networks so it cannot find a route, despite the fact that it's directly connected!

https://paste.ee/p/KRnhz

The LBW wallet node is 023b03ddeae3fd2422ae57902bc4a60adac39fb1c73dd54d67f454ecb053fdf2b4 and the CL node is 026fe566f268b8e88512cfb8ffda1426416dde5f8bbf0badf43007165be0f2bf76.

**Comment by dslingo** [comment] 2019-01-02 11:58
i invetsigated problem little bit, and conclusion is that c-lng is not processing route hints (f field) of given invoice. In the source code You can see that they ask for route and if not found then pay transaction is failed. The route is not found because destination node is nonadvertised node. Workaround is to build manually routing path based on f field from invoice. But hen it is necessery to set correctly "delay" field otherwise You will get WIRE_EXPIRY_TOO_SOON. See also: https://github.com/ElementsProject/lightning/issues/2208

to make routing path manually:
1. call getroute to the node from f field of invoice, copy selected path array
2. as a last field of array add position with id of destination node and channel id from f field of invoice
3. fix delay field
4. use it in sendpay command

**Comment by dslingo** [comment] 2019-01-02 12:03
better way is to fix pay function:
static struct command_result *json_pay_try(struct pay *pay) in payalgo.c

**Comment by cdecker** [comment] 2019-01-02 17:44
We currently don't support the routeboost channels in an invoice. @rustyrussell is working on a `pay` plugin that supports them, and that should be available shortly.

**Comment by charltonh** [comment] 2019-01-02 17:57
If the route is directly connected to CL, CL should find it before it even consults any routing hints.

**Comment by cdecker** [comment] 2019-01-02 22:03
It will find routes that are using non-advertised local channel and advertised channels. It will not consider non-advertised non-local channels currently, but as I mentioned, a fix is underway :wink: 

As for @dslingo's procedure, that should work, but you might have to guess the fees for the last hop, so you might be better off by computing the last hop first and then going from the other endpoint of the hint. So in `a->...->c->d`, where `c->d` is the non-advertised channel that is given as a route hint, compute how much fees `f` `c` requires to send the target amount `a` over that channel, and then compute a route to `c` using `a+f` as the amount to transfer. That way you don't have to guess the fees.

**Comment by cdecker** [comment] 2019-01-06 20:53
Are we ok flagging this as a duplicate of #2163? @dslingo

**Comment by cdecker** [comment] 2019-01-12 22:01
Duplicate #2163

**Closed by cdecker** 2019-01-12 22:01 UTC
Labels: duplicate
