### ISSUE TITLE
Generic question

### ISSUE THREAD

**Issue by kalibox** [ElementsProject/lightning#4930] opened 2021-11-24 01:18 UTC
Hi, I have a non-tech question- say I opened a channel with 1m sats and due to liquidity shift, it now shows a lot less in "spendable" balance. If I were to close this channel will I only receive what the spendable balance shows or will it be the initial liquidity put in?

Thanks!

**Comment by ZmnSCPxj** [comment] 2021-11-24 04:27
You will receive *approximately* the spendable balance.  There is a reserve capacity (1% of total capacity) that is not included in spendable, but which is semantically "yours", but if you created the channel in the first place, onchain fees for closing will be deducted from that spendable + reserve amount.

**Comment by kalibox** [comment] 2021-11-24 09:29
Hey @ZmnSCPxj, thanks for that. I used the plugin and noticed that most of my channels are low on "spendable" and high on "receive". Whats the best way to balance my channels? 

Thanks.

**Comment by ZmnSCPxj** [comment] 2021-11-24 09:47
Which plugin are you talking about?  There are dozens in https://github.com/lightningd/plugins alone.

Just add more sats to your node and have [CLBOSS](https://github.com/ZmnSCPxj/clboss) manage it, is my personal recommendation.  Or if you distrust CLBOSS, add more sats to your node and open a channel and use the `rebalance` plugin manually.

**Comment by kalibox** [comment] 2021-11-24 10:50
I was specifically talking about the Summary plugin which shows you a graphical representation of liquidity and in my case my "OUT/OURS" is low across all channels. I'll explore the options you've listed. Thanks @ZmnSCPxj

**Comment by kalibox** [comment] 2021-11-24 12:08
`channels=

├0.0xxxxbtc    OUT/OURS ┼ IN/THEIRS   0.0xxxxbtc┤ SCID           FLAG AVAIL ALIAS
                       ╟─┤                      <deleted>  [__]  91%  <deleted>
                       ╟──────────────────────┤ <deleted> [__] 100%  <deleted>
                       ╟─────┤                  <deleted>  [__] 100%  <deleted>
                       ╟─┤                      <deleted>  [__]  99%  <deleted>
                       ╟─┤                     <deleted>  [__] 100%  <deleted>
                       ╟─────┤                  <deleted>   [__] 100%  <deleted>
                       ╟──┤                     <deleted>  [__] 100%  <deleted>
                       ╟┤                       <deleted>  [__]  99%  <deleted>
`

**Comment by kalibox** [comment] 2021-11-24 12:11
In the above scenario, I should try and close the 2nd channel right?

**Comment by ZmnSCPxj** [comment] 2021-11-24 13:30
Sure.  Though I do not know what your goal here is.  It looks to me that you used this node, then spent much of your funds on various things.  You *could* close channels, but why not keep them open in case in the future you ever need to receive funds over Lightning, you already have the incoming capacity?  It really depends on what you believe will happen in the foreseeable future.

**Comment by kalibox** [comment] 2021-11-24 13:51
Hey @ZmnSCPxj, really appreciate your time and response, thank you.

To be honest, I've not used the liquidity myself but I suspect my "spend" liquidity has been used up for routing transactions. I've made a few thousand sats.

My intention of closing channel was because I wanted to withdraw and reuse my liquidity to another node (triangulated) instead of having to pour more sats into my node. But from what I've understood and read here, I think adding sats is the way forward.

**Comment by andrewtoth** [comment] 2021-11-24 17:11
Hi @kalibox - from the displayed summary, it appears you have very little funds in any channel. When your node is used for routing transactions, some liquidity from one channel is moved from out to in, and an equivalent amount is moved from in to out in another one of your channels.. Since none of your channels seem to have any liquidity in out, it appears that funds were instead just spent and not routed.

**Comment by kalibox** [comment] 2021-11-24 17:27
Hey @andrewtoth, thanks for that. Ok, this is worrying because I haven't been spending anything via the lightning  node. Whats the best command to run to display node payment activity?

**Comment by andrewtoth** [comment] 2021-11-24 17:47
`listpays` should do it.

**Comment by kalibox** [comment] 2021-11-24 17:51
Thanks. I've run that command and the output is exactly as I see it via the Spark-wallet panel too. It doesn't add up, however, which is confusing?

**Comment by kalibox** [comment] 2021-11-24 21:13
Could my node have been compromised and I've not known about it?

**Comment by ZmnSCPxj** [comment] 2021-11-25 00:39
Maybe someone just speculatively made a large channel to you, "for the good of the network", or just for LOLs.  If what you see in Spark Wallet is correct by your memory, and it says an amount that you *know* should be there, then everything is fine.  Is the channel with large incoming capacity one you made yourself or was it created by the peer?  `listpeers` should be able to tell you who made the channel, in the `opener` key (`local` = you, `remote` = other).  If it was `remote`, then probably someone just saw your new node and decided to speculatively give you some capacity, in case you need it in the future.  For forwarding purposes, you might want to make some channels elsewhere, possibly triangled with that node.

**Comment by kalibox** [comment] 2021-11-25 01:01
Hi @ZmnSCPxj, thanks for that. I had opened that channel myself to the peer ("opener": "local",) and it was a triangle setup until the 3rd node disconnected from me which is what sparked this entire conversation. Prior to this I had 3x triangulated setups; two of which are still active in that formation.

**Comment by ZmnSCPxj** [comment] 2021-11-25 06:23
Hmm, if so then `listfunds` should tell you that you have onchain funds equal to the amount that you used to have?  If so you probably just need to open channels using those onchain funds.

**Comment by kalibox** [comment] 2021-11-25 09:24
Morning @ZmnSCPxj, yes under the "open channel" option in Spark Wallet I can see available funds are almost equal to the funds transferred in.

**Comment by kalibox** [comment] 2021-11-29 18:41
Hi, is there a better command than listfunds to see current usable UTXO balance on the node? Also, is the BOS equivalent for c-Lightning?

**Comment by andrewtoth** [comment] 2021-11-29 18:48
What do you mean by "better"? `listfunds` shows all confirmed UTXO balance. There isn't currently a way to view unconfirmed UTXOs.
I'm unfamiliar with BOS.

**Comment by kalibox** [comment] 2021-11-29 18:52
Hi @andrewtoth, apologies if the question came across as being awkward. So, listfunds is a good command but I find that it's missing some old transactions and doesn't show the current amount of unused UTXO that can be deployed towards a new channel. Does this make sense?

**Comment by andrewtoth** [comment] 2021-11-29 18:58
Ahh I see, you can run `listfunds true` to return historical spent outputs. For adding up the total amount of unspent, you can use the [summary](https://github.com/lightningd/plugins/tree/master/summary) plugin to show the total.

**Comment by kalibox** [comment] 2021-11-29 19:08
Ah nice. I'll check that out. To answer your other question- BoS is Balance of Satoshi which, apparently, is a rebalancing tool in the LND world. I've only just heard about it from a LND node operator. Thought it was intriguing.

**Comment by andrewtoth** [comment] 2021-11-29 19:22
There is also a [rebalance](https://github.com/lightningd/plugins/tree/master/rebalance) plugin for clightning. Although it doesn't have the greatest success rate :/.

**Comment by kalibox** [comment] 2021-11-30 02:34
Thanks @andrewtoth. Your comment doesn't inspire a lot of confidence ;) Is it worth trying it out or is there something else in the works that might be worth waiting for?

**Comment by ZmnSCPxj** [comment] 2021-11-30 05:30
Just try it out.  Or just run CLBOSS, it is awesome, for some definition of the word "awesome" (like, awww, what a cute little attempt at a node manager, has it had its diaper changed yet?)

**Comment by cdecker** [comment] 2021-12-02 10:36
> There is also a [rebalance](https://github.com/lightningd/plugins/tree/master/rebalance) plugin for clightning. Although it doesn't have the greatest success rate :/.

It might be worth noting that while not the fastest to rebalance channels as it tries a lot of different paths, it also doesn't cost to try those failed attempts. We are working on improving it, so hopefully we get better, but as ZmnSCPxj suggested, clboss is a good alternative that is getting quite a bit of attention.

**Closed** 2024-02-21 13:11 UTC
Labels: question, state::answered
