### ISSUE TITLE
CHANNELD_AWAITING_LOCKIN - 48 hours

### ISSUE THREAD

**Issue by JonnyMaK** [ElementsProject/lightning#1253] opened 2018-03-20 15:13 UTC
### Issue and Steps to Reproduce

Synced Bitcoind and Lightningd fully. Connected to two different nodes. Transferred funds from my bitcoin wallet. Try and fund channels, 48 hours of awaiting locking

### `getinfo` output
```
{ "id" : "0350ef95f8cf301c3cef4504dd8478c9c2a805172fb661a6c212108fdbf7301a70", "port" : 9735, "address" :
        [
                { "type" : "ipv4", "address" : "52.242.24.175", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2314-ged3984f", "blockheight" : 514388, "network" : "bitcoin" }
```
### `getlog` output
```
{ "creation_time" : "1521557240.030336194", "created_at" : "1521557240.030336194", "bytes_used" : 1734647, "bytes_max" : 20971520, "log" :
        [
                { "type" : "SKIPPED", "num_skipped" : 21 },
                { "type" : "INFO", "time" : "1.096228392", "source" : "lightningd(8):", "log" : "Server started with public key 0350ef95f8cf301c3cef4504dd8478c9c2a805172fb661a6c212108fdbf7301a70, alias light.videogames4bitcoin.com (color #0350ef) and lightningd v0.5.2-2016-11-21-2314-ged3984f" },
                { "type" : "SKIPPED", "num_skipped" : 11530 },
                { "type" : "INFO", "time" : "62.474603222", "source" : "lightningd(8):", "log" : "lightning_channeld-03ca035ea082d3ba5cba13890895a0818ee000a99d983ec6e65ebeb79fb6d986e3 chan #3: Peer connection lost" },
                { "type" : "INFO", "time" : "62.474646824", "source" : "lightningd(8):", "log" : "03ca035ea082d3ba5cba13890895a0818ee000a99d983ec6e65ebeb79fb6d986e3 chan #3: Peer transient failure in CHANNELD_AWAITING_LOCKIN: lightning_channeld: Owning subdaemon lightning_channeld died (62208)" },
                { "type" : "SKIPPED", "num_skipped" : 1077 } ] }
```

**Comment by cdecker** [comment] 2018-03-20 15:21
Can you share the output of `lightning-cli listpeers`? There are some nodes that are misbehaving badly in the network.

**Comment by JonnyMaK** [comment] 2018-03-20 15:32
{ "peers" :
        [
                { "id" : "03ca035ea082d3ba5cba13890895a0818ee000a99d983ec6e65ebeb79fb6d986e3", "connected" : true, "netaddr" :
                        [ "155.4.193.242:9735" ], "alias" : "Yo", "color" : "ffa947", "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "20f9abcb483653482c4ace41ed0fd24d13ffb793062ce15e8d448510fc4f808f", "msatoshi_to_us" : 1146000, "msatoshi_total" : 1146000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "their_to_self_delay" : 144, "our_to_self_delay" : 144, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.", "CHANNELD_AWAITING_LOCKIN:Funding needs more confirmations." ] } ] },
                { "id" : "02c0ac82c33971de096d87ce5ed9b022c2de678f08002dc37fdb1b6886d12234b5", "connected" : true, "netaddr" :
                        [ "13.80.67.162:9735" ], "alias" : "⚡️ STAMPERY.com ⚡️", "color" : "aa0000", "channels" :
                        [
                                { "state" : "CHANNELD_AWAITING_LOCKIN", "owner" : "lightning_channeld", "funding_txid" : "527359b7b3b0ccbf1c3147eddd156425a148b07a3c457d79e9c227da057df629", "msatoshi_to_us" : 2000000, "msatoshi_total" : 2000000, "dust_limit_satoshis" : 546, "max_htlc_value_in_flight_msat" : 18446744073709551615, "channel_reserve_satoshis" : 0, "htlc_minimum_msat" : 0, "their_to_self_delay" : 144, "our_to_self_delay" : 144, "to_self_delay" : 144, "max_accepted_htlcs" : 483, "status" :
                                        [ "CHANNELD_AWAITING_LOCKIN:Reconnected, and reestablished.", "CHANNELD_AWAITING_LOCKIN:Funding needs more confirmations." ] } ] } ] }

**Comment by cdecker** [comment] 2018-03-20 15:40
Neither of the funding transactions is confirmed, this could be related to #1194, which resulted in funding transactions that would never confirm because `bitcoind` was returning a feerate that was too low. This should have been addressed in #1251, but those channels will not confirm any time soon. I'd suggest running

```
lightning-cli dev-forget-channel 03ca035ea082d3ba5cba13890895a0818ee000a99d983ec6e65ebeb79fb6d986e3
lightning-cli dev-forget-channel 02c0ac82c33971de096d87ce5ed9b022c2de678f08002dc37fdb1b6886d12234b5
lightning-cli dev-rescan-outputs
```

This'll forget the two channels, and sync your outputs with the blockchain so that you get your funds back. After that you can update to the latest `master` and try again.

**Comment by JonnyMaK** [comment] 2018-03-20 15:54
Thank you! 

Those channels are now forgotten and funds are returned safely home.

Can I ask how to update to the latest master? I'm still relatively new at this. Just trying to learn as much as possible before the revolution happens

**Comment by cdecker** [comment] 2018-03-20 16:22
Assuming you have checked out through `git` and compiled it yourself, the following should work:

```
git pull origin master
make clean default install
```

**Comment by cdecker** [comment] 2018-03-26 17:10
Closing since the original issue was addressed

**Closed by cdecker** 2018-03-26 17:10 UTC
Labels: channeld, duplicate, tx
