### ISSUE TITLE
No way to cancel a pending payment with a dead peer?

### ISSUE THREAD

**Issue by artlav** [ElementsProject/lightning#1537] opened 2018-06-02 11:33 UTC
So i wanted to pay for something, got a bolt11 invoice with a typical 15 minutes timer for the session validity.

I do a lightning-cli pay [bolt11], and nothing happens. Some looking around shows that the peer i had the only channel open with is down, so there is no way for it to proceed.

Ok, i'm in no hurry. Cancel the payment and wait for the peer to reappear, right? Well, no. I looked high and low and there does not seem to be any way to cancel a payment (one listed as "pending" in listpayments).

Ok then. The bolt11 had an expiry field, and it was correctly set to 15 minutes. The payment would auto-fail once that counts down, right? Nope. Hours later the payment is still pending.

At this point i'm not sure what would happen next, that is when the peer comes back online. Would the payment go through? Would it honour the expiry field instead? Would it get stuck there permanently?

This is, at best, an interface issue - not long ago someone proposed (#1088) to add a paycancel command or add a cancel option to pay command, but somehow that got lost in discussion. I think that would be quite useful.

At worst, this is a clear bug - a payment should not get stuck in pending mode past it's expiry even if the peer is missing.

**Comment by cdecker** [comment] 2018-06-02 11:58
The issue is a bit more complicated: if the peer died before you offered it the HTLC then the payment would indeed have died immediately. If however the HTLC was added to the channel, the peer might have forwarded it correctly and then died. In the latter case we really can't tell whether aborting is safe or not. Call it a Heisenberg Payment (TM). It could still go through or it might have stopped with your peer. If it went through the recipient may be able to tell you, but even if it didn't, it might just temporarily be stuck and might resume later.

This is intrinsic to the way the Lightning protocol forwards payments in the network, and we don't really have a solution just yet. The only way to be sure is to wait for the HTLC timeout to expire, which might be several days. In the meantime you can close the channel and open a new one with the remaining funds. The client will retrieve the funds once they are cleared.

**Comment by artlav** [comment] 2018-06-02 12:41
I see the wider problem, but what about a case where the payment haven't been tried at all?

If it wasn't clear, in my case the only channel's peer was down for hours by the time i tried to pay, so this looks like a way more clear cut situation. In fact, i think it should be able to just report the lack of connections at once.

**Comment by cdecker** [comment] 2018-06-02 14:12
In that case you should have received an error stating that no route could be found and that should have been the end of it, you're right. Could you provide us with the logs so we can figure out what got stuck there? It might just have been the channel not being marked as unavailable when we got disconnected. I'd guess that your node was restarted when the channel was active and then was unable to reconnect afterwards. If that's the case it was already fixed here 14dc7cacba3d4a8983812298b33fe20fda27a2cc, but will not unblock that payment.

The good news is that the HTLC not having been added to the channel means that the funds will not be locked, and you can `close`, wait for the close timeout and you'll have all funds available again.

**Comment by rustyrussell** [comment] 2018-06-24 08:41
We should get smarter with this. If we haven't heard from the peer recently, we should ping before sending the commitment_signed message. That way if they've vanished we can tell *before* committing.

**Closed** 2018-09-02 17:05 UTC
Labels: needinfo, protocol
