### ISSUE TITLE
paying to invoice with deschashonly=true not working

### ISSUE THREAD

**Issue by daywalker90** [ElementsProject/lightning#6085] opened 2023-03-10 22:45 UTC
very simple python script basically 2 lines:
`cln = LightningRpc("/home/bitcoin/.lightning/bitcoin/lightning-rpc")`
and then the call to pay and later invoice:

```
cln.pay(bolt11="lnbc10n1pjqh27app5wrx6rpq6utf5n8hggj6y2z44cdw47syrtpf93j6p78c8x2wldafshp5mg0dq0gh9jdm5l9h5p43tq8kvpz3k958hrv86pmq02vmw2uyc92qcqzpgxqzpusp57dt9lfdgs9dz9thrh8emnpl8dnlll2fqptftq64ayl205l7qh90s9qyyssqquhv5flwksfe492046rlffxknjp5x4ptf2sl5cjhasvge9rvrtfzdy5xk98fs9kd0je9gghs327c7vjhw4cd3qy2zlydaaknprryehqpqnpgc7", description='[["text/plain","Funding @odell on stacker.news"],["text/identifier","odell@stacker.news"]]')
```

```
pyln.client.lightning.RpcError: RPC call failed: method: pay, payload: {'bolt11': 'lnbc10n1pjqh27app5wrx6rpq6utf5n8hggj6y2z44cdw47syrtpf93j6p78c8x2wldafshp5mg0dq0gh9jdm5l9h5p43tq8kvpz3k958hrv86pmq02vmw2uyc92qcqzpgxqzpusp57dt9lfdgs9dz9thrh8emnpl8dnlll2fqptftq64ayl205l7qh90s9qyyssqquhv5flwksfe492046rlffxknjp5x4ptf2sl5cjhasvge9rvrtfzdy5xk98fs9kd0je9gghs327c7vjhw4cd3qy2zlydaaknprryehqpqnpgc7', 'description': '[["text/plain","Funding @odell on stacker.news"],["text/identifier","odell@stacker.news"]]'}, error: {'code': -32602, 'message': 'Invalid bolt11: h: does not match description'}
```

```
lcli decode lnbc10n1pjqh27app5wrx6rpq6utf5n8hggj6y2z44cdw47syrtpf93j6p78c8x2wldafshp5mg0dq0gh9jdm5l9h5p43tq8kvpz3k958hrv86pmq02vmw2uyc92qcqzpgxqzpusp57dt9lfdgs9dz9thrh8emnpl8dnlll2fqptftq64ayl205l7qh90s9qyyssqquhv5flwksfe492046rlffxknjp5x4ptf2sl5cjhasvge9rvrtfzdy5xk98fs9kd0je9gghs327c7vjhw4cd3qy2zlydaaknprryehqpqnpgc7
{
   "type": "bolt11 invoice",
   "currency": "bc",
   "created_at": 1678486493,
   "expiry": 60,
   "payee": "03cc1d0932bb99b0697f5b5e5961b83ab7fd66f1efc4c9f5c7bad66c1bcbe78f02",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "description_hash": "da1ed03d172c9bba7cb7a06b1580f660451b1687b8d87d07607a99b72b84c154",
   "min_final_cltv_expiry": 40,
   "payment_secret": "f3565fa5a8815a22aee3b9f3b987e76cffffa9200ad2b06abd27d4fa7fc0b95f",
   "features": "024200",
   "payment_hash": "70cda1841ae2d3499ee844b4450ab5c35d5f4083585258cb41f1f07329df6f53",
   "signature": "30440220072eca27eeb4139a954fae87f4a4d69c8343542b4aa1fa6257ec188c946c1ad20220269286b14e9816cd7cb25422f08abd8f32577570d8808a17c8def6d308c64cdc",
   "valid": true
}
```
sha256sum seems fine:
`echo -n '[["text/plain","Funding @odell on stacker.news"],["text/identifier","odell@stacker.news"]]' | sha256sum
da1ed03d172c9bba7cb7a06b1580f660451b1687b8d87d07607a99b72b84c154  -`

double check the other way around:
```
cln.invoice(label="test22", amount_msat=1000, description='[["text/plain","Funding @odell on stacker.news"],["text/identifier","odell@stacker.news"]]', deschashonly=True)
```

```
lcli decode lnbc10n1pjqhvg9sp5s7cq5lz5j2sthtt7gcwnd4x765zp6mtwfhjx67hqvuqwefk5407spp5nd2ee7zqmm5q3leczxpju0cseucqlenzkqgqr7k5sh76599majkshp5mg0dq0gh9jdm5l9h5p43tq8kvpz3k958hrv86pmq02vmw2uyc92qxqyjw5qcqpjrzjqtz2wwgvts8z3ml4mqp55jwhyjgqkxtffr6hy0lvmzr4z2e0qqs0xz7s4vqqfucqqyqqqqqqqqqqqzsqyg9qyysgqyy3q3amsm7etpcyyy46n7hfc98feg495w7pq850xlzgdgagf97u9afnuvsf0zjkr7eggn4mwcqkm6hn9s309mk8schkf3quafrqqg9gpnyk9vs
{
   "type": "bolt11 invoice",
   "currency": "bc",
   "created_at": 1678487813,
   "expiry": 604800,
   "payee": "0380ef0209ff1b46c38a37cd40f613d1dae3eba481a909459d6c1434a0e56e5d8c",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "description_hash": "da1ed03d172c9bba7cb7a06b1580f660451b1687b8d87d07607a99b72b84c154",
   "min_final_cltv_expiry": 18,
   "payment_secret": "87b00a7c5492a0bbad7e461d36d4ded5041d6d6e4de46d7ae06700eca6d4abfd",
   "features": "024100",
   "routes": [
      [
         {
            "pubkey": "02c4a7390c5c0e28eff5d8034a49d724900b196948f5723fecd887512b2f0020f3",
            "short_channel_id": "774315x1267x1",
            "fee_base_msat": 0,
            "fee_proportional_millionths": 10,
            "cltv_expiry_delta": 34
         }
      ]
   ],
   "payment_hash": "9b559cf840dee808ff3811832e3f10cf300fe662b01001fad485fdaa14bbecad",
   "signature": "30440220212208f770dfb2b0e08425753f5d3829d39454b4778203d1e6f890d475092fb802205ea67c6412f14ac3f65089d76ec02dbd5e65845e5dd8f0c5ec98839d48c00415",
   "valid": true
}
```

I don't get it. hash seems fine.

**Comment by daywalker90** [comment] 2023-03-11 00:45
i'm aware that it works with simple descriptions like "test". But this one does not. I tried to .encode() the description but then i get `'bytes' object has no attribute 'to_json'`. I'm not in control of the description so i can't change it either. I need to know how to make this one work with the pyln-client.

**Comment by daywalker90** [comment] 2023-03-11 14:02
example python script:
```
#!/usr/bin/env python3
from pyln.client import LightningRpc
cln1 = LightningRpc("/tmp/l1-regtest/regtest/lightning-rpc")
cln2 = LightningRpc("/tmp/l1-regtest/regtest/lightning-rpc")


description='[["text/plain","Funding @odell on stacker.news"],["text/identifier","odell@stacker.news"]]'
invoice = cln1.invoice(label="test12345", amount_msat=1_000, description=description, deschashonly=True)
print(cln1.decode(invoice["bolt11"]))
print(cln2.pay(bolt11=invoice["bolt11"], description=description))
```

**Comment by arcbtc** [comment] 2023-03-13 10:33
They broke description_hash in 23. Soooo, yeah.

**Comment by daywalker90** [comment] 2023-03-13 11:18
tried the same thing with cln-plugin using `String::from("[[\"text/plain\",\"Funding @odell on stacker.news\"],[\"text/identifier\",\"odell@stacker.news\"]]")` same result as with pyln-client. The invoice gets generated with the correct hash but when paying to it, it fails.

**Comment by daywalker90** [comment] 2023-03-13 11:32
also, on the cli i could pay the invoice with `description="[[\"text/plain\",\"Funding @odell on stacker.news\"],[\"text/identifier\",\"odell@stacker.news\"]]"`

**Comment by evd0kim** [comment] 2023-06-12 13:50
Looks like non-issue for v23.05.
Added option into cln4rust for LNURL-Pay.
https://github.com/laanwj/cln4rust/pull/101.
It worked on the testnet.

**Comment by daywalker90** [comment] 2023-06-12 13:56
it might be an issue again if description is required even with allow-deprecated-apis=true (maybe in 23.08?). If this happens i would not know how pyln-client and cln-rpc would `pay` to lightning adresses.

**Comment by daywalker90** [comment] 2023-06-13 12:09
I'm so confused. Are plugins with pyln-client or cln-rpc supposed to be able to pay invoices with description_hash and description or not? Because if yes then this issue is about certain descriptions not working with pyln-client/cln-rpc while they do work directly on the cli.

**Comment by evd0kim** [comment] 2023-06-13 12:22
Oh, sorry. I thought the problem is that i couldn't generate such invoices. May be it shouldn't be closed indeed.

**Comment by vincenzopalazzo** [comment] 2023-06-13 14:00
Mh sorry I was answering the following message 

> it might be an issue again if a description is required even with allow-deprecated-apis=true 

Mh so there are more than a couple of things here, let's recap a little bit to answer your questions:

- Pyln-client and all the others should work without problems because there is no extra logic; they are just making an RPC JSON 2.0 request;
- If you are able to pay the same invoice from the command line, you should be able to pay also from a library;

You may be passing the wrong parameters to the pay argument, what are your commands to pass to lightning-cli
that worked?

**Comment by daywalker90** [comment] 2023-06-13 14:05
> also, on the cli i could pay the invoice with `description="[[\"text/plain\",\"Funding @odell on stacker.news\"],[\"text/identifier\",\"odell@stacker.news\"]]"`

**Closed** 2023-06-22 03:53 UTC
Labels: discussion
