### ISSUE TITLE
Mark certain routes as broken?

### ISSUE THREAD

**Issue by jb55** [ElementsProject/lightning#783] opened 2018-01-26 02:44 UTC
I don't yet know enough about routing internals so bear with me. This may be the next step in #635 ...

I noticed when I try to pay some invoices, some intermediate nodes reply with this message:

```
"failed: WIRE_UNKNOWN_NEXT_PEER (reply from remote)"
```

This leads to a more general problem of buggy/broken/rogue nodes that accidentally or purposefully disrupt routes. Perhaps we should mark these as temporarily broken and route around?

**Comment by ZmnSCPxj** [comment] 2018-01-26 06:44
#638 . Sorry for the slow progress...

**Comment by cdecker** [comment] 2018-01-26 13:05
@ZmnSCPxj no problem, you're doing an excellent job, I'd rather have slow steady progress than a quick fix that'll break soon again :wink:

**Comment by cdecker** [comment] 2018-01-26 13:06
I'll mark this as duplicate of #550

**Closed by cdecker** 2018-01-26 13:06 UTC

**Comment by jb55** [comment] 2018-01-26 14:57
So much to keep on top of! I'll try to catch up on what's been going on over there. Thanks!

**Comment by cdecker** [comment] 2018-01-26 18:32
I know, just noticed this myself :-)
