### ISSUE TITLE
docker logs bitcoind_mainnet --tail "10"

### ISSUE THREAD

**Issue by alibora** [ElementsProject/lightning#1368] opened 2018-04-12 12:12 UTC
I funding but I do not see my node channels.

https://bitnodes.earn.com/

35.196.254.121:9735 is unreachable.

-------------------------------------------------------------------------------------------------------------------

cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"

-------------------------------------------------------------------------------------------------------------------

lightning-cli getinfo

{ "id" : "0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95", "port" : 9735, "address" : 
        [ 
                { "type" : "ipv4", "address" : "35.196.254.121", "port" : 9735 } ], "version" : "v0.5.2-2016-11-21-2422-g286cfef", "blockheight" : 517853, "network" : "bitcoin" }

-------------------------------------------------------------------------------------------------------------------

lightning-cli listfunds

{ "outputs" : 
        [ 
                { "txid" : "48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a", "output" : 1, "value" : 73747, "status" : "unconfirmed" }, 
                { "txid" : "ad9691bafd34ce0308b335ded5276331996ffc57cfe05c50693ea73f684f9059", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "201e992dc6a5b5c5fabc2d4c15f1fb762a1808cc13dd3593227af97b528364fe", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "e3ecaa4ac946652c17a1d4ccd2f2f4601e8890fb6ae78dfab97fcc57bd414de5", "output" : 0, "value" : 2398, "status" : "unconfirmed" }, 
                { "txid" : "426a0d020e10035e385337328b1228c6a0b02ecd31b8f788e5623715692bbceb", "output" : 0, "value" : 10317, "status" : "unconfirmed" }, 
                { "txid" : "221171c8dd53f4e60f99e90e8082907de47198d8b00fe622dec06667e249ef49", "output" : 0, "value" : 2398, "status" : "unconfirmed" } ], "channels" : 
        [  ] }

-------------------------------------------------------------------------------------------------------------------

bitcoin-cli getnetworkinfo

{ "code" : -1, "message" : "Invalid feerate 10000nano" }
{
  "version": 160000,
  "subversion": "/Satoshi:0.16.0/",
  "protocolversion": 70015,
  "localservices": "000000000000040d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 33,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": ""
}

-------------------------------------------------------------------------------------------------------------------

bitcoin-cli getwalletinfo

{ "code" : -1, "message" : "Invalid feerate 10000nano" }
{
  "walletname": "wallet.dat",
  "walletversion": 159900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1521111161,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00000000,
  "hdmasterkeyid": "ff3c7d853379sa21e995df5e11dedbabb96d25xx"
}

-------------------------------------------------------------------------------------------------------------------

lightning-cli listpeers

{ "peers" : 
        [  ] }

-------------------------------------------------------------------------------------------------------------------

lightning-cli listconfigs
{ "# version" : "v0.5.2-2016-11-21-2422-g286cfef", "port" : 9735, "rgb" : "00008b", "alias" : "exchange", "pid-file" : "lightningd-bitcoin.pid", "channel-update-interval" : 604800,
 "log-level" : "DEBUG", "log-prefix" : "lightningd(1):", "lightning-dir" : "/root/.lightning", "rpc-file" : "lightning-rpc", "daemon" : "false", "ignore-fee-limits" : false, "lockt
ime-blocks" : 144, "max-locktime-blocks" : 432, "anchor-onchain" : 10, "anchor-confirms" : 3, "max-anchor-confirms" : 10, "commit-fee-min" : 200, "commit-fee-max" : 2000, "commit-f
ee" : 500, "override-fee-rates" : "20000/1245/253", "default-fee-rate" : 40000, "cltv-delta" : 14, "cltv-final" : 8, "max-htlc-expiry" : 720, "bitcoind-poll" : "30s", "commit-time"
 : "10ms", "fee-base" : 1000, "fee-per-satoshi" : 10, "ipaddr" : "35.196.254.121:9735", "network" : "bitcoin", "allow-deprecated-apis" : true, "autocleaninvoice-cycle" : 0, "autocl
eaninvoice-expired-by" : 0, "dev-no-reconnect" : "false", "dev-fail-on-subdaemon-fail" : "false", "dev-broadcast-interval" : 60000 }

**Comment by cdecker** [comment] 2018-04-12 16:14
I'm sorry, but I do not understand what the issue is, so here's my best guess what your issue could be:

 - https://bitnodes.earn.com/ shows Bitcoin nodes, not Lightning nodes
 - `listfunds` would show channels if you had any (seems you are not connected either according to `listpeers`)
 - Nodes will only ever appear in the network graphs once you have a public channel
 - Searching for your node in the history (`0230c8826852e2a39883f36233483419e9c139b644c696b8dbcca38fef7303ee95`) it seems you had at least one channel open at some point, but it was closed.

**Comment by alibora** [comment] 2018-04-13 08:42
Thank you for your answer.
how can i control what you say "close RPC call" ?

**Comment by alibora** [comment] 2018-04-13 09:01
this is the situation at the moment

docker logs bitcoind_mainnet --tail "10"

2018-04-13 08:48:03 socket receive timeout: 1201s
2018-04-13 08:50:15 socket send error Broken pipe (32)
2018-04-13 08:52:34 connect() to 210.26.51.241:8333 failed after select(): Connection refused (111)
2018-04-13 08:53:31 version handshake timeout from 16108
2018-04-13 08:53:47 socket send error Connection timed out (110)
2018-04-13 08:54:25 connect() to [2a02:1810:4d35:7c00:7140:79b7:f938:8198]:8333 failed: Cannot assign requested address (99)
2018-04-13 08:54:43 connect() to 46.34.207.188:8333 failed after select(): Connection refused (111)
2018-04-13 08:55:37 socket recv error Connection reset by peer (104)
2018-04-13 08:56:10 version handshake timeout from 16114
2018-04-13 08:58:06 version handshake timeout from 16121

**Comment by cdecker** [comment] 2018-04-13 09:13
That is `bitcoind`, not lightning, and those messages are perfectly allright, it's just trying to open more connections.

With close RPC call I mean you can close a channel by calling the following command:

```
lightning-cli close [node_id]
```

and `lightningd` will try to close the channel and return the funds to the internal wallet. Come to think of it, if you have created the channels, then went away without transferring anything, and then the counterparty decided to close then we'll also get this situation. Was your node offline for a long time during which the channels were closed?

**Comment by alibora** [comment] 2018-04-13 09:37
thank you very much for your help, but I am receiving this response:

root@instance-1:~# lightning-cli close 48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a
{ "code" : -1, "message" : "Could not find peer with that id" }
root@instance-1:~# lightning-cli close 9116baffcd53589bf46717af3ba1c665757bdcadcc823702056b6ec2e77021af
{ "code" : -1, "message" : "Could not find peer with that id" }
root@instance-1:~# lightning-cli close 6e44206e8be922fe605eff1c303a33e8b2f2c081322ebe416d8f2418afb30ac9
{ "code" : -1, "message" : "Could not find peer with that id" }
root@instance-1:~# lightning-cli close 48853e4adf8e0d03d0f6563069393c3ae948155fc21a1c81101c0364ff7d405a
{ "code" : -1, "message" : "Could not find peer with that id" }
root@instance-1:~# lightning-cli close 416365b10f4e2363ad36095574af59496d3194253600e2a8614b0b34cf1fdc45
{ "code" : -1, "message" : "Could not find peer with that id" }
root@instance-1:~# lightning-cli close d4a0e49eaadac91b82384371e2ba4ddaa582e794e224819d92cdbf4433f72ec0
{ "code" : -1, "message" : "Could not find peer with that id" }

**Comment by cdecker** [comment] 2018-04-13 14:32
They are already closed, so no need to close them. `close` takes the 33 byte nodeid, not the funding transaction, and will always start with `02...` or `03...` :wink:

**Closed by cdecker** 2018-04-13 14:32 UTC
