### ISSUE TITLE
No timeout on lightning-cli connect function

### ISSUE THREAD

**Issue by RvMp** [ElementsProject/lightning#748] opened 2018-01-23 22:32 UTC
When connecting to a lightning node that is not responding the connect functions stalls until it is cancelled with CTRL+C. Couldn’t find anything in the documentation about timeout parameters.

**Comment by jb55** [comment] 2018-01-24 08:11
Duplicate of #390

**Comment by cdecker** [comment] 2018-01-26 12:28
Closing as a duplicate of #390

**Closed by cdecker** 2018-01-26 12:28 UTC
