### ISSUE TITLE
"Stopped retrying during payment attempt" issue

### ISSUE THREAD

**Issue by fedsten** [ElementsProject/lightning#1917] opened 2018-09-08 14:52 UTC
I was trying to pay an invoice issued by a merchant using OpenNode, and the payment failed with the following error, followed by the description of the routes it attempted to take.

`"code" : 200, "message" : "Stopped retrying during payment attempt; continue monitoring with pay or listpayments"`

I tried to connect directly with the payee's node, without solving the issue. I then decided to open a channel directly with the payee's node, hoping to solve the problem, but instead, when trying to send the payment after the channel was successfully  open (I checked it was open with `listfunds`) I got this:

```
{ "code" : 200, "message" : "Stopped retrying during payment attempt; continue monitoring with pay or listpayments", "data" : 
{
  "getroute_tries": 1, 
  "sendpay_tries": 1, 
  "id": 17, 
  "payment_hash": "79a92f8aab6254124a4f9859311fc765d5fcd3f219cecfdabc7e255bd19b734d", 
  "destination": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
  "msatoshi": 50000000, 
  "msatoshi_sent": 50019020, 
  "timestamp": 1536402661, 
  "created_at": 1536402661, 
  "status": "pending", 
  "failures": [
  ]
} }
```

I tried to restart `lightningd`, I tried to attempt again the payment after some minutes but I was always obtaining the very same result. 
After several attempts, the invoice was going to expire so I asked for a new one and tried the payment once again. This time it was successful, but oddly instead of performing the payment through the existing opened channel, it seems it used a complex route:
```

{
  "id": 18, 
  "payment_hash": "6a2ab39ea7388704aa1db18fadc1ae9747df14cc3c0f4633293984321ae742a7", 
  "destination": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
  "msatoshi": 50000000, 
  "msatoshi_sent": 50085084, 
  "timestamp": 1536406419, 
  "created_at": 1536406419, 
  "status": "complete", 
  "payment_preimage": "c9a2e3bc5b0645b485277e0f0b50046465cb3fb04eae09a1cdbdf8ca8fd269d8", 
  "getroute_tries": 8, 
  "sendpay_tries": 8, 
  "route": [
    {
      "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "channel": "540483:1032:1", 
      "msatoshi": 50085084, 
      "delay": 144
    }
  ], 
  "failures": [
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50110282, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50173123, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50090956, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50030432, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50049514, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 18, 
      "erring_node": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
      "erring_channel": "0:0:0", 
      "route": [
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "540483:1032:1", 
          "msatoshi": 50021059, 
          "delay": 144
        }
      ]
    }, 
    {
      "message": "reply from remote", 
      "type": "FAIL_PAYMENT_REPLY", 
      "erring_index": 1, 
      "failcode": 4103, 
      "erring_node": "024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca", 
      "erring_channel": "539435:574:1", 
      "channel_update": "11f508742192a4adf3491d92e3ac1d6e7c1940c6e5a9fb92a9264dac5ae0b9f126ef88d67d4f16eb5402d1166823accbea95d4f34a427f31223c07c3f25f405b6fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d6190000000000083b2b00023e00015b93a5780000000e00000000000003e8000003e80000000a", 
      "route": [
        {
          "id": "024655b768ef40951b20053a5c4b951606d4d86085d51238f2c67c7dec29c792ca", 
          "channel": "539847:417:1", 
          "msatoshi": 50058660, 
          "delay": 446
        }, 
        {
          "id": "0367a20f89da5628f22da7549d44352b97e00d966f5962db06faf31c302b970687", 
          "channel": "539435:574:1", 
          "msatoshi": 50057160, 
          "delay": 432
        }, 
        {
          "id": "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f", 
          "channel": "539145:944:1", 
          "msatoshi": 50057109, 
          "delay": 288
        }, 
        {
          "id": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
          "channel": "539504:2073:0", 
          "msatoshi": 50056959, 
          "delay": 144
        }
      ]
    }
  ]
}
```

This is actually not the first time that I encounter this problem, I received the same error also in other occasions and it was often solved just by trying again, so it is not clear to me what is the nature of this error.

For reference, here there is the `getinfo` of my node:

```
{
  "id": "03b838eb5c974be4d86bfb763b2ae15dc89debb62cfbe20a3e7cd8cc82c254c6c0", 
  "alias": "ASTRAPE", 
  "color": "028500", 
  "port": 9735, 
  "address": [
  ], 
  "binding": [
    {
      "type": "ipv6", 
      "address": "::", 
      "port": 9735
    }
  ], 
  "version": "v0.6-173-g0b597f6", 
  "blockheight": 540492, 
  "network": "bitcoin"
}

```

**Comment by cdecker** [comment] 2018-09-08 19:50
Any idea what the receiving node is using? `failcode` 18 refers to the following error:

> The CLTV expiry is too close to the current block height for safe handling by the final node.
>
> type: 18 (final_incorrect_cltv_expiry)
> data:
>  [4:cltv_expiry]

Also, could you share the invoice you are attempting to pay? If that contains a CLTV and we are sending it correctly, then the invoice generation is at fault.

**Comment by cdecker** [comment] 2018-09-08 19:53
It could also be caused by your `lightningd` not being synced up with the blockchain, so that your current height + the CLTV delta < expected height on the receiving end.

**Comment by fedsten** [comment] 2018-09-08 21:04
The invoice I was attempting to pay was this one:

`lnbc500u1pde8g7xpp50x5jlz4tvf2pyjj0npvnz878vh2le5ljr88vlk4u0cj4h5vmwdxsdpzxysv89eqgf5hgcm0d9hzq3j4gssyg6trv5cqzys3qknkpspxrmgwaxf9rnh4xtm67ywn6rackglv75vucg3kne9juq4ghzfgaypshzskc4fs8p2k7c52s8qky2kknz6cw69zmlrznnkkjqqkknyyv`

Decoded:

```
{
  "currency": "bc", 
  "timestamp": 1536402374, 
  "created_at": 1536402374, 
  "expiry": 3600, 
  "payee": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
  "msatoshi": 50000000, 
  "description": "1 × Bitcoin FUD Dice", 
  "min_final_cltv_expiry": 144, 
  "payment_hash": "79a92f8aab6254124a4f9859311fc765d5fcd3f219cecfdabc7e255bd19b734d", 
  "signature": "3045022100882d3b060130f68774c928e77a997bd788e9e87dc591f67a8ce6111b4f2597010220545c494748185c50b62a981c2ab7b14540e0b1156b4c5ac3b4516fe314e76b48"
}
```

While the second one that eventually managed to go through using a long path is this one:

`lnbc500u1pde8v6ppp5dg4t88488zrsf2sakx86msdwjara79xv8s85vvef8xzryxh8g2nsdpzxysv89eqgf5hgcm0d9hzq3j4gssyg6trv5cqzysgum6qyteyhkgdgfcyy7xaevml6p867ar7vn7ej7kcsw64venm9dhm2h5vw05m4j22lt98x59tuaw6k8zd5dmvemgeupwyjj4fvxxuygpcdmkxm`

Decoded:

```
{
  "currency": "bc", 
  "timestamp": 1536406337, 
  "created_at": 1536406337, 
  "expiry": 3600, 
  "payee": "03abf6f44c355dec0d5aa155bdbdd6e0c8fefe318eff402de65c6eb2e1be55dc3e", 
  "msatoshi": 50000000, 
  "description": "1 × Bitcoin FUD Dice", 
  "min_final_cltv_expiry": 144, 
  "payment_hash": "6a2ab39ea7388704aa1db18fadc1ae9747df14cc3c0f4633293984321ae742a7", 
  "signature": "304402204737a0117925ec86a138213c6ee59bfe827d7ba3f327eccbd6c41daab333d95b02207daaf4639f4dd64a57d6539a855f3aed58e26d1bb66768cf02e24a554b0c6e11"
}
```

The receiving node is from OpenNode, that according to some Reddit discussion is using LND, but I'm not 100% sure.

Regarding the blockchain syncing, I believe it is unlikely for it to be the issue, the c-lightning node is  on a machine that is always running uninterruptedly bitcoind and has been synced for a long time.

**Comment by cdecker** [comment] 2018-09-09 06:42
Both invoices have the same final CLTV expiry, and the path we generated was respecting that constraint. I also think it's a `lnd` node since by default they'll ask for 1 day of locktime (144 blocks). Since you're saying that the second invoice went through and that you believe your node to be up to date, it might also be the `lnd` node not being synced, and enforcing that the final CLTV does not deviate too much from what it expects. This would be a bug on the `lnd` side, and bad for privacy since it does not allow hiding the final destination from the last hop.

Maybe @roasbeef can put my mind at ease about this?

**Comment by ZmnSCPxj** [comment] 2019-05-28 02:06
Is this still relevant? We no longer return `200`/`PAY_IN_PROGRESS` from `pay`.

**Comment by ZmnSCPxj** [comment] 2019-05-31 06:00
If no objections, I will close this soon.

**Closed** 2019-06-03 14:08 UTC
Labels: lnd-compat, needinfo, pending-fix-confirmation
