### ISSUE TITLE
Pulled April 27 Code / Fatal Error after some time. Was Dead. Managed a workaround.

### ISSUE THREAD

**Issue by Xian001** [ElementsProject/lightning#1441] opened 2018-04-30 01:00 UTC
### Issue and Steps to Reproduce
No clue how to reproduce. Node was chugging along fine at about 100 channels, then just up and died, constantly spitting out this error when I launch the node.
 
```
2018-04-30T00:58:23.137Z lightning_gossipd(14575): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-04-30T00:58:23.137Z lightning_gossipd(14575): UPDATE WIRE_GOSSIP_PEER_CONNECTED
2018-04-30T00:58:23.137Z lightningd(14567): 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: Peer has reconnected, state CHANNELD_NORMAL
2018-04-30T00:58:23.137Z lightningd(14567): Client: Received message 9 from client
2018-04-30T00:58:23.137Z lightningd(14567): lightning_channeld-03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: pid 14623, msgfd 23
2018-04-30T00:58:23.137Z lightningd(14567): 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: Already have funding locked in (and ready to announce)
2018-04-30T00:58:23.152Z lightningd(14567): Adding block 520459: 0000000000000000001ffacce0c948963de8649abb567b25fc8528171d95aeba
2018-04-30T00:58:24.228Z lightning_gossipd(14575): peer_in WIRE_INIT
2018-04-30T00:58:24.228Z lightningd(14567): lightning_channeld-02b7060f74b7e04d3d8af97fab20381fcc16f7a33c7e526fa5c9b96afdb288d7d2 chan #329: init LOCAL: remote_per_commit = 02f4aa024d95a0663a42766262b8d53d1f625f642fe85be759e468455fc757600d, old_remote_per_commit = 023f691de59b33fd41986832560118115fd728b201f57f53e21f088ed9e65b2ebe next_idx_local = 948 next_idx_remote = 948 revocations_received = 947 feerates 3549/3549 (range 253-15280)
2018-04-30T00:58:24.228Z lightningd(14567): lightning_channeld-022b679aa4b614266662f49cad70ab7e48d5bd2bc52df59c988fa85d280948e49f chan #343: init LOCAL: remote_per_commit = 02f3fe2fa8d12d8b69ea1ae17b34582c5aa92b14ba50f732175ead5ac8515e041a, old_remote_per_commit = 0391b57f2d26d598df345598cea0aa270daadbcb253ab5dd9b1d46647cfd3c0a1b next_idx_local = 494 next_idx_remote = 494 revocations_received = 493 feerates 3549/3549 (range 253-15280)
2018-04-30T00:58:24.230Z lightning_gossipd(14575): peer 031c527494f295220d26a1814c18e7db3f4f03203ce1a53a0b74b52ed570a3972a: reconnect for active peer
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-02b7060f74b7e04d3d8af97fab20381fcc16f7a33c7e526fa5c9b96afdb288d7d2 chan #329: peer_out WIRE_CHANNEL_REESTABLISH
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: init LOCAL: remote_per_commit = 036ca9c8d4ce6b83616df4e140daea19e62a42aec285be2c20266b9793b97cc130, old_remote_per_commit = 037ca3829a8c81d1a0cf53cd5492868030f60682201c0a02d432b8ba3ac04fba14 next_idx_local = 476 next_idx_remote = 476 revocations_received = 475 feerates 3549/3549 (range 253-15280)
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-022b679aa4b614266662f49cad70ab7e48d5bd2bc52df59c988fa85d280948e49f chan #343: peer_out WIRE_CHANNEL_REESTABLISH
2018-04-30T00:58:24.230Z lightning_gossipd(14575): FATAL SIGNAL 6
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: peer_out WIRE_CHANNEL_REESTABLISH
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: common/daemon.c:42 (crashdump) 0x416822
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-02b7060f74b7e04d3d8af97fab20381fcc16f7a33c7e526fa5c9b96afdb288d7d2 chan #329: Error reading gossip msg
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-022b679aa4b614266662f49cad70ab7e48d5bd2bc52df59c988fa85d280948e49f chan #343: Error reading gossip msg
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0x7f6f07dd04af
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-02b7060f74b7e04d3d8af97fab20381fcc16f7a33c7e526fa5c9b96afdb288d7d2 chan #329: Peer connection lost
2018-04-30T00:58:24.230Z lightningd(14567): 02b7060f74b7e04d3d8af97fab20381fcc16f7a33c7e526fa5c9b96afdb288d7d2 chan #329: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: Error reading gossip msg
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-022b679aa4b614266662f49cad70ab7e48d5bd2bc52df59c988fa85d280948e49f chan #343: Peer connection lost
2018-04-30T00:58:24.230Z lightningd(14567): 022b679aa4b614266662f49cad70ab7e48d5bd2bc52df59c988fa85d280948e49f chan #343: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0x7f6f07dd0428
2018-04-30T00:58:24.230Z lightningd(14567): lightning_channeld-03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: Peer connection lost
2018-04-30T00:58:24.230Z lightningd(14567): 03a9b9b4d5bff67fb90d7deaf7db842e3aa5e3abea58fa488a8af3d163679107d7 chan #328: Peer transient failure in CHANNELD_NORMAL: lightning_channeld: Owning subdaemon lightning_channeld died (62208)
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0x7f6f07dd2029
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:98 (call_error) 0x43dd99
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:170 (check_bounds) 0x43df56
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:178 (to_tal_hdr) 0x43df7d
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:504 (tal_free) 0x43e968
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/io/io.c:443 (io_close) 0x4321f0
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: gossipd/gossip.c:264 (destroy_reconnecting_peer) 0x403455
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:240 (notify) 0x43e10b
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:400 (del_tree) 0x43e5bc
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/tal/tal.c:511 (tal_free) 0x43e9ee
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: gossipd/gossip.c:270 (add_reconnecting_peer) 0x40348a
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: gossipd/gossip.c:455 (peer_connected) 0x403d49
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: gossipd/gossip.c:505 (peer_init_received) 0x403f1c
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: common/cryptomsg.c:158 (peer_decrypt_body) 0x415fcd
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x43156c
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/io/io.c:387 (do_plan) 0x432043
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/io/io.c:397 (io_ready) 0x432081
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: ccan/ccan/io/poll.c:310 (io_loop) 0x433bed
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: gossipd/gossip.c:2392 (main) 0x409307
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0x7f6f07dbb82f
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0x402ad8
2018-04-30T00:58:24.230Z lightning_gossipd(14575): backtrace: (null):0 ((null)) 0xffffffffffffffff
2018-04-30T00:58:24.230Z lightning_gossipd(14575): STATUS_FAIL_INTERNAL_ERROR: FATAL SIGNAL
```

Full logs: https://gist.github.com/cdecker/14673c7396bfb46ba462d8fc1458f365

**Comment by Xian001** [comment] 2018-04-30 01:47
Likely related to issue Crash on startup #1437

I've disabled the lnd port forward for the machine, and it seems to be loading up and getting it's marbles back.

Will re-enable the port-forward when she's caught up and see if things don't blow up again.

**Comment by ZmnSCPxj** [comment] 2018-04-30 05:08
I think more closely related to #1434.

**Comment by cdecker** [comment] 2018-04-30 10:10
I took the liberty of moving the logs into a separate [gist](https://gist.github.com/cdecker/14673c7396bfb46ba462d8fc1458f365) and just taking out an excerpt.

Indeed this is pretty much a duplicate of #1434, could this be related to a peer we are gossipping with reconnecting again?

**Comment by robtex** [comment] 2018-05-03 12:16
i haven't found anything in the log pointing to a specific peer, but it is hard to tell because it tries to connect to the entire world at the same time.
log:
```
2018-05-03T12:07:40.695Z lightning_gossipd(18487): Failed connected out for 03b08ad01f5473717ee0251777b80cf7effa70b681ec0b1cd5c49317e8ffc52447
2018-05-03T12:07:40.695Z lightning_gossipd(18487): ...will try again in 4 seconds
2018-05-03T12:07:40.695Z lightning_gossipd(18487): Received channel_announcement for channel 507867:766:0
2018-05-03T12:07:40.695Z lightning_gossipd(18487): UPDATE WIRE_GOSSIP_GET_TXOUT
2018-05-03T12:07:40.695Z lightning_gossipd(18487): Failed connected out for 02ef8eee471a04b6f5bc9eb69a2ea9625e71f3b93a5ee7dc6350474730cd1f29c9                                                                           2018-05-03T12:07:40.695Z lightning_gossipd(18487): ...will try again in 4 seconds
2018-05-03T12:07:40.695Z lightning_gossipd(18487): Failed connected out for 035add86d2f652cb15ff7550c3e97c93928b321e33a93d4e2a7a34b3f43a614f1f
2018-05-03T12:07:40.695Z lightning_gossipd(18487): ...will try again in 4 seconds
2018-05-03T12:07:40.695Z lightning_gossipd(18487): Failed connected out for 03fa0ef0845dbc299739e62c06e34aefda5b0a2e6ab3f6e4ca33f776ea12d7a3d5
2018-05-03T12:07:40.695Z lightning_gossipd(18487): ...will try again in 4 seconds
```

stderr:
```
lightning_gossipd: Fatal signal 6
0x415b25 crashdump
        common/daemon.c:37                                                                                                                                                                                               0x7f1d8623a4af ???                                                                                                                                                                                                               ???:0
0x7f1d8623a428 ???
        ???:0
0x7f1d8623c029 ???
        ???:0
0x43ae9f call_error
        ccan/ccan/tal/tal.c:98
0x43b05c check_bounds
        ccan/ccan/tal/tal.c:170
0x43b083 to_tal_hdr
        ccan/ccan/tal/tal.c:178
0x43ba6e tal_free
        ccan/ccan/tal/tal.c:504
0x42f56f io_close
        ccan/ccan/io/io.c:443
0x403235 destroy_reconnecting_peer
        gossipd/gossip.c:264
0x43b211 notify
        ccan/ccan/tal/tal.c:240
0x43b6c2 del_tree
        ccan/ccan/tal/tal.c:400
0x43baf4 tal_free
        ccan/ccan/tal/tal.c:511                                                                                                                                                                                          0x40326a add_reconnecting_peer
        gossipd/gossip.c:270
0x403b29 peer_connected
        gossipd/gossip.c:455
0x403cfc peer_init_received
        gossipd/gossip.c:505
0x415318 peer_decrypt_body
        common/cryptomsg.c:158
0x42e8eb next_plan
        ccan/ccan/io/io.c:59
0x42f3c2 do_plan
        ccan/ccan/io/io.c:387
0x42f400 io_ready
        ccan/ccan/io/io.c:397
0x430f6c io_loop
        ccan/ccan/io/poll.c:310
0x40918a main
        gossipd/gossip.c:2407
0x7f1d8622582f ???
        ???:0                                                                                                                                                                                                            0x402ad8 ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightningd: lightning_gossipd failed (signal 14), exiting.
```

**Closed** 2018-05-21 18:51 UTC
Labels: duplicate
